### ISSUE TITLE
Where is the refresh token?

### ISSUE THREAD

**Issue by kylesonaty** [pingidentity/mod_auth_openidc#100]
I am using mod_auth_openidc as a relying party and I am trying to locate the refresh token. I am using this sample app from the docs and looking in the session because that is where it says the refresh token is stored. 

```
<html>
  <body>
    <h1>Hello, <?php echo($_SERVER['REMOTE_USER']) ?></h1>
    <pre><?php print_r(apache_request_headers()); ?></pre>
    <h1>Session</h1>
    <pre><?php print_r($_SESSION); ?></pre>
  </body>
</html>
```
I removed a lot of the claims fro brevity and security.
```
Hello,

Array
(
    [OIDC_CLAIM_email_verified] => true
    [OIDC_CLAIM_amr] => password
    [OIDC_CLAIM_iat] => 1446495519
    [OIDC_CLAIM_auth_time] => 1446495517
    [OIDC_CLAIM_exp] => 1446499119
    [OIDC_CLAIM_nbf] => 1446495519
    [OIDC_access_token] => abc123
    [OIDC_access_token_expires] => 1446499491
)
Session

Array
(
)
```
 I tested using other clients and the token endpoint is issuing a refresh token. I have tried authorization code and hybrid flows. I am able to get claims and login successfully but there is no refresh token.

**Comment by zandbelt** [comment]
The refresh token is not exposed to the application. Its only purpose it to obtain a new access token; the complete refresh flow is handled by mod_auth_openidc as described here: https://github.com/pingidentity/mod_auth_openidc/wiki/Access-Tokens-and-Refresh-Tokens

So you can use that hook as described to refresh the access token without having to implement that call outside of `mod_auth_openidc`, also avoiding the need to expose and manage the `client_id`/`client_secret` outside as well.

**Comment by kylesonaty** [comment]
Thanks for the fast response. So you just pass in the old access token and that will then lookup the refresh token?

**Comment by zandbelt** [comment]
yes

**Comment by zandbelt** [comment]
Assuming that helped I'm closing the ticket.
