### ISSUE TITLE
Support for Apache 2.4.17 - cannot load module - undefined symbol: ap_requires

### ISSUE THREAD

**Issue by ngnanavadivel** [pingidentity/mod_auth_openidc#101]
We are trying to use mod_auth_openidc on Apache 2.4.17.

Apache 2.4.17 declares that ap_requires has been removed.

When mod_auth_openidc is being loaded by Apache 2.4.17,
it is failing with the message
"Can't load module mod_auth_openidc" - undefined symbol : ap_requires.

Please fix this.

**Comment by zandbelt** [comment]
You're loading a module that was compiled for Apache 2.2 in to an Apache 2.4 server; where/which binaries did you get and which platform are you on?

**Comment by ngnanavadivel** [comment]
mod_auth_openidc-1.8.6-1.el6.x86_64.rpm is what we used.

https://github.com/pingidentity/mod_auth_openidc/releases/download/v1.8.6/mod_auth_openidc-1.8.6-1.el6.x86_64.rpm

Out platform is: RHEL 6.7
Distributor ID: RedHatEnterpriseServer
Release:        6.7

**Comment by zandbelt** [comment]
RHEL's stock Apache server is 2.2, that's what the stock rpm is compiled for as well; for customized installations with 2.4 you need to compile your own module from source.

**Comment by Amrutapan** [comment]
I also get similar kind of error. undefined symbol: ap_get_exec_line. My Apache version is 2.4 and linux 7.

**Comment by dreua** [comment]
Make sure you don't accidentally installed `libapache2-mod-auth-openid` instead of `libapache2-mod-auth-openid*c*`. (Aka the dark side of tab-completion.)
