### ISSUE TITLE
Using mod_auth_openidc to authenticate multiple google domains

### ISSUE THREAD

**Issue by wint00** [pingidentity/mod_auth_openidc#107]
I am using this (http://stackoverflow.com/questions/26215409/google-authentication-for-gerrit-and-jenkins) answer to do authentication for an apache reverse proxy to gerrit. However, I'd like to add a second domain as well -- so authenticate either against foo.com or bar.com (both of which are google apps domains so google is used for both).

I've tried several obvious things like adding multiple OIDCAuthRequestParams lines and then adding several Require statements [Require claim hd:foo.com Require claim hd:bar.com] it just accepts the first one I list and ignores the second domain. When I try to add a comma separated list, it just allows all domains in (ie OIDCAuthRequestParams=foo.com, bar.com). In fact the Require statements don't seem to anything, only the OIDCAuthRequestParams seems to work and only for one domain. Any ideas on how I can make two different domains work given the set up for gerrit as listed above?

I'm using apache2.4 Ubuntu 15.10 and libapache2-mod-auth-openidc 1.6.0 Thanks.

**Comment by zandbelt** [comment]
Don't add any parameters to `OIDCAuthRequestParams` and let the user pick his own domain manually in the account chooser that Google provides and use multiple `Require hd:<domain>` statements.

**Comment by wint00** [comment]
Thanks so much. 

For completeness sake, those who are following the gerrit example, what worked for me was to not have a OIDCAuthRequestParams line at all, add the Require hd:<domain> lines that I needed AND remove the Require valid-user line. If I don't remove the Require valid-user it will allow any google domain including gmail.com.
