### ISSUE TITLE
Support requesting extra claims using the 'claims' request param

### ISSUE THREAD

**Issue by rebeckag** [pingidentity/mod_auth_openidc#111]
I have an OP which only returns additional claims in the ID Token if they are explicitly asked for using the ['claims' request parameter](http://openid.net/specs/openid-connect-core-1_0.html#ClaimsParameter).
Hence they are not possible to request using the 'scope' parameter.

I couldn't find any indication of support for this yet, could it be added anytime soon?

**Comment by zandbelt** [comment]
you can add arbitrary parameters to the authentication request, see: https://github.com/pingidentity/mod_auth_openidc/wiki#13-how-can-i-add-custom-parameters-to-the-authorization-request ; `"claims"` can be added in the same way; here's an example that includes claims:

     "access_type=offline&approval_prompt=force&claims=%7B%20%22id_token%22%20%3A%20%7B%20%22acr%22%20%3A%20%7B%20%22essential%22%20%3A%20true%2C%20%22values%22%20%3A%20%5B%22urn%3Amace%3Aincommon%3Aiap%3Asilver%22%5D%20%7D%20%7D%20%7D"

 let me know if that works for you

**Comment by rebeckag** [comment]
That works great, thanks for the pointer!
