### ISSUE TITLE
Authorization as query parameter

### ISSUE THREAD

**Issue by wyscan** [pingidentity/mod_auth_openidc#112]
It would be handy to have a configuration option (disabled by default) that would allow sending the bearer token as a query parameter.  I tried getting this to work using mod_headers but ran into numerous problems.  Although arguably less secure, which is why it would be disabled by default, this would make it easier to support tools that make it difficult to send headers (such as some Javascript or Gradle).

**Comment by zandbelt** [comment]
can you check if this branch works for you: https://github.com/pingidentity/mod_auth_openidc/tree/bearer-token-query-param

**Comment by wyscan** [comment]
It appears to work perfectly for me.  Thank you so much for the amazingly quick response.

**Comment by zandbelt** [comment]
I'll add an option to this branch for consuming it as an HTTP Post parameter as well, and make it configurable which of the variants will be accepted. After that I'll ask you to verify again, ok?

**Comment by wyscan** [comment]
I saw the merge back to master and tried it out.  I validated expected behavior with OIDCOAuthAcceptTokenAs set to nothing, query, post, and "query header".   Everything looks good.

**Comment by zandbelt** [comment]
Great! I did some testing myself with the same results so I decided to merge back right away. Thanks!
