### ISSUE TITLE
The module does not include 'token_endpoint_auth_method' in registration request.

### ISSUE THREAD

**Issue by rebeckag** [pingidentity/mod_auth_openidc#117]
Since the module [prioritizes 'client_secret_post'](https://github.com/pingidentity/mod_auth_openidc/blob/4c265ed1664a81202e02633563d0bf5e411499d0/src/metadata.c#L1038), the 'token_endpoint_auth_method' should always be included in the registration request.

The OP will assume 'client_secret_basic' if not explicitly specified (according to OIDC spec), which will cause the Token Request to fail if the OP tries to verify that the correct (according to what the client registered) client authentication method was used.

**Comment by zandbelt** [comment]
Yeah, I guess it is kind of a mismatch because `mod_auth_openidc` would take in to account what the OP has published in its discovery doc and take any of those. I guess looking at what the OP publishes and then register the intersection of what `mod_auth_openidc` supports is the right way to address this, agree?

**Comment by rebeckag** [comment]
Yes, agree.
Just note that it's not much of an intersection though since 'token_endpoint_auth_method' is a single value in the Registration Request, hence my thought about simply including whatever value has been selected from the providers metadata.

**Comment by zandbelt** [comment]
Ah, I see, coming up.

**Comment by zandbelt** [comment]
completely untested.. I hope you can provide feedback

**Comment by rebeckag** [comment]
As far as I can see it's working correctly: the 'token_endpoint_auth_method' has the value 'client_secret_post' in the registration request and the subsequent token request uses client_secret_post.
Tested with the latest source against a provider supporting both client_secret_basic and client_secret_post.

Thanks for the quick fix!
