### ISSUE TITLE
User Claims refresh time

### ISSUE THREAD

**Issue by biwerr** [pingidentity/mod_auth_openidc#119]
Is there an option to define expire time for the fechted UserInfo?

**Comment by zandbelt** [comment]
currently not so this would be a feature request for that

**Comment by zandbelt** [comment]
Do you agree it would be enough to take the expiry time from the access token as the refresh time? IOW. have the Authorization Server control the refresh time, and when the access token expires, the Client also fetches the user info again or do you want more control by the Client (i.e. mod_auth_openidc) by a static configuration setting?

**Comment by biwerr** [comment]
Expire time of access token would be an alternative, IMHO. But if you can't controll the access token expire time this would be an alternative way to fetch updated userdata.

**Comment by zandbelt** [comment]
Can you confirm that the latest commit provided the requested capability?

**Comment by biwerr** [comment]
Yes, it works. Thank you for the enhancement :)
