### ISSUE TITLE
Redirect loops with multiple google-account logins

### ISSUE THREAD

**Issue by sysadmin1139** [pingidentity/mod_auth_openidc#121]
We're still getting redirect loops (see #114 for the earlier issue). I think I've finally isolated it down to users habitually logged in to multiple google accounts in the same browser session (work and personal gmail). Those of us who don't do that, or do so rarely, never see it. The progression goes like this:

1. User logs in, gets the account-picker. Picks the right account.
2. Happily uses it for a while.
3. Steps away for a bit. At least 10 minutes.
4. Hits refresh, gets redirect-loop.
5. Clears cookies, GOTO 1.

The apache config we're running is a bit updated from the previous ticket, we're now using `OIDCUnAuthAction 401` on certain endpoints.

```apache
########################
### openidc
#########################
LoadModule auth_openidc_module /usr/lib/apache2/modules/mod_auth_openidc.so

## Google settings.
OIDCProviderMetadataUrl https://accounts.google.com/.well-known/openid-configuration
## Credentials and settings from the google developer console.

OIDCClientID thingsandstuff
OIDCClientSecret verysecretthings

OIDCCookiePath /
## Use session-server. The cookie method was SO BIG it was blowing things up.
## See https://github.com/pingidentity/mod_auth_openidc/wiki/Caching
OIDCSessionType server-cache
OIDCCacheType shm
OIDCCacheShmMax 900
## This must be the same across servers.
OIDCCryptoPassphrase moresecretthings
## See https://developers.google.com/accounts/docs/OAuth2Login#authenticationuriparameters
OIDCAuthRequestParams hd=example.com

## Set REMOTE_USER to the email address.
OIDCRemoteUserClaim email
OIDCScope "email"
#########################
### /openidc
#########################

<VirtualHost *:80>
ServerName k3.example.com
DocumentRoot     /opt/k3/src
ErrorLog         "/var/log/apache2/k3.example.com_error.log"
ServerSignature Off
CustomLog       "/var/log/apache2/k3.example.com_access.log" trueip_combined

# OpenID Connect via Google - domain-specific redirectURI and cookieDomain
OIDCRedirectURI https://k3.example.com/oidcoauth2
# The redirect URI needs to be able to set this cookies on this domain.
OIDCCookieDomain k3.example.com
# Set the inactivity timeout to something big.
OIDCSessionInactivityTimeout 32400

  <Location "/">
    AuthType openid-connect
    AuthName "Kibana"
    Require claim hd:example.com
  </Location>

  <LocationMatch /_aliases$>
    ProxyPassMatch http://172.16.22.21:9200
    OIDCUnAuthAction 401
    Order allow,deny
    Allow from all
  </LocationMatch>

  <LocationMatch /.*/_aliases$>
    ProxyPassMatch http://172.16.22.21:9200
    OIDCUnAuthAction 401
    Order allow,deny
    Allow from all
  </LocationMatch>

  <LocationMatch /_nodes$>
    ProxyPassMatch http://172.16.22.21:9200
    OIDCUnAuthAction 401
    Order allow,deny
    Allow from all
  </LocationMatch>

  <LocationMatch /.*/_mapping>
    ProxyPassMatch http://172.16.22.21:9200
    OIDCUnAuthAction 401
    Order allow,deny
    Allow from all
  </LocationMatch>

  <LocationMatch /.*/_search$>
    ProxyPassMatch http://172.16.22.21:9200
    OIDCUnAuthAction 401
    Order allow,deny
    Allow from all
  </LocationMatch>

  <LocationMatch /kibana-int/dashboard/.*$>
    ProxyPassMatch http://172.16.22.21:9200
    OIDCUnAuthAction 401
    Order allow,deny
    Allow from all
  </LocationMatch>

  <LocationMatch /kibana-int/temp.*$>
    ProxyPassMatch http://172.16.22.21:9200
    OIDCUnAuthAction 401
    Order allow,deny
    Allow from all
  </LocationMatch>

</VirtualHost>
```

My theory at this point is that the session-state negotiation somehow, maybe, triggers a fresh eval of claims, and we're blowing through one of the size-limits again since 2+ google accounts are delivering data. Are we being too greedy in our Claim/Scope?

**Comment by zandbelt** [comment]
Could you please add a debug log that shows this? I don't think it has to do with size anymore since the claims are no longer stored in the cookies. Also, which exact version are you on?

**Comment by zandbelt** [comment]
Looking a bit more at this, the description and the config don't seem to match: when the configuration is done as you pasted, including `OIDCAuthRequestParams hd=example.com`, the user would never be prompted with an account-picker since the `hd` param is there to skip account selection. Also the `OIDCSessionInactivityTimeout 32400` doesn't seem to match the 10 minutes in your description. Could it be that you're running multiple configs and this is the wrong one?

**Comment by sysadmin1139** [comment]
For version, I'm pretty sure we're running the 1.8.7 release

The discrepancy with `OIDCSessionInactivityTimeout` is something that stood out to me, as well. Those of us who don't regularly encounter the redirect-loop, actually get kicked out after 8 hours. Those that do, run into it with much shorter intervals. Why, I can't explain.

I have a second site, `kib.example.com` that has debug logging turned on, and never had the known-bad config on it. I'm asking our affected users to switch to that URL and see if they run into it.

**Comment by zandbelt** [comment]
that's all good info; it seems to be not directly related to timeouts then (well at least not to the inactivity timeout setting)

**Comment by sysadmin1139** [comment]
I have finally had it happen to me, and a slightly different site that doesn't see much use. In this case, I visited the site much earlier in the day, and just now got the redirect problem. Looking at cookies, there is a mega-cookie in there in spite of this site being set for `OIDCSessionType server-cache` (the cookie is 3372 characters). 

What's more, when I clear cookies for that site, the same very long `mod_auth_openidc_session` cookie gets acquired from somewhere. On the third connection (connecting to the RedirectURI after talking to google), a `mod_auth_openidc_session` cookie is set by the server, but the client already has the megacookie.

Looking at the browser traces, and digging through my own cookies, I finally noticed something very important. We have a web-app on a sub-page of `example.com` that is secured through this apache module, and no one has ever complained about it. It seems that cookie is getting passed on to the 'alert.example.com' (and `k3.example.com`), and *that* cookie, is a mega-cookie. But just small enough people don't notice on the sub-page, but using this plugin in the sub-domains is pushing the cookie-jar to overflowing. AHAH!

I was able to get a debug log of the session with the redirects. 
[apache-debug.zip](https://github.com/pingidentity/mod_auth_openidc/files/189060/apache-debug.zip)

The current server config is nearly identical to the one I posted, varying only in the details of the vhost itself; the OIDC settings are the same.

**Comment by zandbelt** [comment]
The log shows that that mega cookie wasn't set by this instance of mod_auth_openidc since a cookie gets presented right after a clean restart that shows a server side cache config. I believe the cookie is from a different config with a client side cache i.e. a different instance of mod_auth_openidc

**Comment by sysadmin1139** [comment]
You know, now that I look on things, I think I can make this go away by setting `OIDCCookieName` in the parent-domain configuration. That way, sub-domain usage of this module won't be getting a cookie for a different instance.

**Comment by zandbelt** [comment]
if you can confirm that the other mod_auth_openidc instance still has the client cookie setting we can close this

**Comment by sysadmin1139** [comment]
It most definitely does have it. 

----
**Primary cause**: A sub-domain server was setting a cookie for `.example.com`, which meant that the `mod_auth_openidc_session` cookie for *that* instance was being offered to `subdomain.example.com`, and was being rejected as invalid. 

----
**Primary fix**: Two options:

1. Move to a unified server setup, where session-state is shared between all servers. This would be `OIDCCacheType` settings of `memcache` or possibly `redis`.
1. Use `OIDCCookie` to rename the session-cookie used by the top-level installation in order to prevent it being used by the subdomain installations.

----
**Secondary cause**: The top level server was using `client-cookie`. In some cases, the subdomain's session-cookie was being accepted and the site was working. However, the parent domain sets an extremely large cookie, it was crowding out normal app-cookies for the sub-domain installs, causing failures.

----
**Secondary fix**: [Don't use OIDCSessionType client-cookie](https://github.com/pingidentity/mod_auth_openidc/wiki/Cookies)

**Comment by ftzdomino** [comment]
I had this issue too, but it was because I was sending an expires header on static content.  The redirect to google was caching, and when mod_auth_openidc attempted to send the authorized user back to their original URL the browser was repeatedly redirected back to google instead of refreshing the content.  The solution was to disable mod_expires for a mod_auth_openidc protected host.
