### ISSUE TITLE
session state return

### ISSUE THREAD

**Issue by boris8479** [pingidentity/mod_auth_openidc#125]
Hans,

I like your implementation of OpenID Connect relay party. After closer comparison of your implementation with other Openid Connect session implementation I see a slight difference.
The OpenID connect session specification states is section 3, to return the session in the "Authentication Response" as defined in "Section 3.1.2.5 of OpenID Connect Core 1.0". The same section states "An Authentication Response is an OAuth 2.0 Authorization Response message returned from the OP's Authorization Endpoint in response to the Authorization Request message sent by the RP". And the example of the "Authentication Response" provides example of the authorization code return.

This description led many implementers to believe that the session_state is returned together with the authorization code, not as a result of the token call as implemented by your RP.

I personally like your solution better, because provides better protection for the session_state. However, the spec is spec and the way it is now, I can see how it can be interpreted differently and to have most of the implementers doing it the other way.

Are you aware of this difference? For what reason, the PingIdentity implementation works in a different way? Did you consult your solution with the OpenID Connect community?

Regards,
Boris Georgiev

**Comment by zandbelt** [comment]
As far as I know mod_auth_openidc takes the `session_state` parameter from the authorization response together with the code. I've just verified this against Azure AD. Why do you believe differently?

BTW: perhaps a session state returned from the token endpoint will override one returned from the authorization endpoint but that is more undefined behaviour than anything else.

**Comment by boris8479** [comment]
I can see my mistake. You use the same table params to store the returns from both authorization response and token call. You do this probably to be able to handle hybrid flows.
