### ISSUE TITLE
oidc_util_decode_json_and_check_error on 1.8.8 openidc centos7

### ISSUE THREAD

**Issue by srimandarbha** [pingidentity/mod_auth_openidc#126]
Hello,

I am seeing issue with openidc module when i tried to install the latest version of openidc with httpd 2.4.6. I am seeing below errors with minimal httpd settings done. 

[root@test-instance ~]# cat /etc/httpd/conf.d/oidc.conf
oidc.conf file contents below
<Location />
   AuthType openid-connect
   Require valid-user
</Location>

#Ping OpenID Connect Configuration URL
#OIDCProviderMetadataURL https://fssfed.stage.example.com/fss/.well-known/openid-configuration
OIDCProviderMetadataURL https://example.api.example.com/examplecorp/ssoclient/v1

OIDCClientID ExampleCorp_jaam_ITRGAVAPOC127

OIDCClientSecret 2aa16c98cb880bb7001ba6ec03ce98bdf7b11e3c279a905706fa804ba8121b04

OIDCRedirectURI http://5.8.86.131/redirect_uri

OIDCScope "profile openid"

OIDCCryptoPassphrase chefapi@3003
ProxyPass /  http://5.8.86.131:8080/ nocanon
ProxyPassReverse / http://5.8.86.131:8080/
ProxyRequests     Off
AllowEncodedSlashes on
#
<Proxy http://5.8.86.131:8080/*>
</Proxy>
OIDCAuthNHeader X-Forwarded-User
OIDCRemoteUserClaim sub

OIDCClaimPrefix xx_

error logs shows

**[Thu Mar 31 14:27:20.855386 2016] [auth_openidc:error] [pid 23606] [client 3.235.198.30:54132] oidc_util_decode_json_and_check_error: JSON parsing returned an error: '[' or '{' expected near '<', referer: http://5.8.86.131/
[Thu Mar 31 14:27:20.855435 2016] [auth_openidc:error] [pid 23606] [client 3.235.198.30:54132] oidc_metadata_provider_retrieve: JSON parsing of retrieved Discovery document failed, referer: http://5.8.86.131/
[Thu Mar 31 14:27:20.855442 2016] [auth_openidc:error] [pid 23606] [client 3.235.198.30:54132] oidc_provider_static_config: could not retrieve metadata from url: https://stage.api.example.com/examplecorp/ssoclient/v1, referer: http://5.8.86.131/**

[root@test-instance ~]# rpm -qa | egrep 'httpd|openidc'
httpd-tools-2.4.6-40.el7.centos.x86_64
mod_auth_openidc-1.8.8-1.el7.centos.x86_64
httpd-2.4.6-40.el7.centos.x86_64
[root@test-instance ~]#

below is the list of loaded modules
[Thu Mar 31 14:46:50.604132 2016] [so:warn] [pid 23652] AH01574: module auth_openidc_module is already loaded, skipping
Loaded Modules:
 core_module (static)
 so_module (static)
 http_module (static)
 access_compat_module (shared)
 actions_module (shared)
 alias_module (shared)
 allowmethods_module (shared)
 auth_basic_module (shared)
 auth_digest_module (shared)
 authn_anon_module (shared)
 authn_core_module (shared)
 authn_dbd_module (shared)
 authn_dbm_module (shared)
 authn_file_module (shared)
 authn_socache_module (shared)
 authz_core_module (shared)
 authz_dbd_module (shared)
 authz_dbm_module (shared)
 authz_groupfile_module (shared)
 authz_host_module (shared)
 authz_owner_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 cache_module (shared)
 cache_disk_module (shared)
 data_module (shared)
 dbd_module (shared)
 deflate_module (shared)
 dir_module (shared)
 dumpio_module (shared)
 echo_module (shared)
 env_module (shared)
 expires_module (shared)
 ext_filter_module (shared)
 filter_module (shared)
 headers_module (shared)
 include_module (shared)
 info_module (shared)
 log_config_module (shared)
 logio_module (shared)
 mime_magic_module (shared)
 mime_module (shared)
 negotiation_module (shared)
 remoteip_module (shared)
 reqtimeout_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 slotmem_plain_module (shared)
 slotmem_shm_module (shared)
 socache_dbm_module (shared)
 socache_memcache_module (shared)
 socache_shmcb_module (shared)
 status_module (shared)
 substitute_module (shared)
 suexec_module (shared)
 unique_id_module (shared)
 unixd_module (shared)
 userdir_module (shared)
 version_module (shared)
 vhost_alias_module (shared)
 dav_module (shared)
 dav_fs_module (shared)
 dav_lock_module (shared)
 lua_module (shared)
 mpm_prefork_module (shared)
 proxy_module (shared)
 lbmethod_bybusyness_module (shared)
 lbmethod_byrequests_module (shared)
 lbmethod_bytraffic_module (shared)
 lbmethod_heartbeat_module (shared)
 proxy_ajp_module (shared)
 proxy_balancer_module (shared)
 proxy_connect_module (shared)
 proxy_express_module (shared)
 proxy_fcgi_module (shared)
 proxy_fdpass_module (shared)
 proxy_ftp_module (shared)
 proxy_http_module (shared)
 proxy_scgi_module (shared)
 proxy_wstunnel_module (shared)
 systemd_module (shared)
 cgi_module (shared)
 auth_openidc_module (shared)

Please help

Thanks,

**Comment by zandbelt** [comment]
It appears that you're pointing `OIDCProviderMetadataURL` to something else than the providers's Discovery endpoint that contains valid JSON metadata that describes the OP capabilities. Using the right URL should make this work.

**Comment by srimandarbha** [comment]
Thanks for the reply! I corrected the OIDCProviderMetadataURL, now i see another error

Error:

OpenID Connect Provider error: server_error
Description:

Unexpected+Runtime+Authn+Adapter+Integration+Problem.

Please help

Thanks

**Comment by zandbelt** [comment]
that's an error returned by the provider, you should check with the administrator of that server and see e.g. in the provider logs what the actual problem is

**Comment by srimandarbha** [comment]
Thank you Zandbelt for the help and quick support!

**Comment by priyanka92feb** [comment]
Hi Sri,

I am receiving the same error: "Unexpected+Runtime+Authn+Adapter+Integration+Problem", while invoking the endpoint to get the auth code.

Could you please confirm if the issue had to do with the authorization server & not with the way i am invoking the end-point or the client side settings?

**Comment by srimandarbha** [comment]
Hi Priyanka,

By Zandbelt previous comment, It should be a issue with Administrator end. Sometimes i have observed such an error with ntp unsynchonized. I hope your issue is resolved by now.
