### ISSUE TITLE
apr_jwe_decrypt_content_aesgcm() fails to null terminate string

### ISSUE THREAD

**Issue by jdennis** [pingidentity/mod_auth_openidc#128]
The test test_jwt_decrypt_gcm() in test.c would sometimes fail. The
failure was caused by extra garbage appearing in the decrypted string
after the expected string. This is due to the failure of
apr_jwe_decrypt_content_aesgcm() to null terminate the string as is
similarity done in apr_jwe_decrypt_content_aescbc().

There is a patch and pull request to fix this: https://github.com/pingidentity/mod_auth_openidc/pull/127

**Comment by zandbelt** [comment]
thanks for reporting and fixing; I will review and merge asap
