### ISSUE TITLE
Is Implicit Flow supported?

### ISSUE THREAD

**Issue by surfnet-niels** [pingidentity/mod_auth_openidc#130]
I am trying to set up an RP for use with an OP that only supports Implicit Flow

My config is as following:
```
        OIDCClientID "someclientid"
        OIDCResponseType "id_token"
        OIDCScope "openid persistent student"
        OIDCRedirectURI https://demoshop.inacademia.org/validate/do.php
        OIDCCryptoPassphrase somesecret
```
According to https://github.com/pingidentity/mod_auth_openidc/blob/master/auth_openidc.conf#L149
I should not need a client secret, however,  oidc_check_config throws an error: 
`[Mon Apr 04 13:15:32.839645 2016] [auth_openidc:error] [pid 15220] oidc_check_config_error: mandatory parameter 'OIDCClientSecret' is not set`

Looking at the sources at https://github.com/pingidentity/mod_auth_openidc/blob/master/src/config.c#L1506
it is not clear if it should be working, or if it is to be done.

Am I missing something?

**Comment by zandbelt** [comment]
The Implicit flow is supported but you may be experiencing a configuration glitch wrt. a single statically configured provider; for now you should be able to configure a dummy secret; I'll look in to it shortly
