### ISSUE TITLE
Create docker image

### ISSUE THREAD

**Issue by solsson** [pingidentity/mod_auth_openidc#131]
I made `solsson/httpd:openidc` over at https://hub.docker.com/r/solsson/httpd/ but it's quite possible that the build is sub-optimal.

See https://github.com/solsson/docker-httpd/tree/master/openidc

I'd prefer a Dockerfile that this community collaborates on.

**Comment by zandbelt** [comment]
Thanks for the heads up. There are existing binary images on the release page of this project for various OSes and some of the Linux distro's include mod_auth_openidc in their package feeds. It should be possible to use those in your Docker images as well. FWIW: I use docker myself to build and test the OS binaries from here: https://github.com/zandbelt/mod-auth-openidc-dist. Can you indicate what people would use this "docker build from source" image for?

**Comment by solsson** [comment]
I tried to summarize my reason to start from https://hub.docker.com/_/httpd/ in the readme: complete control over httpd.conf; the official https://github.com/docker-library/httpd/blob/master/2.4/httpd-foreground as entrypoint.

I see no reason to build mod_auth_openidc from source there, other than debian `jessie` not being among the distributed binaries.

Let's do nothing for a while and see what other people think. Your docker images are great for using a distro's httpd.

**Comment by zandbelt** [comment]
the stock debian binaries are Jessie binaries

**Comment by rektide** [comment]
The complexity of the solutions both presented here- hundreds of lines of code- makes me all the more certain that there really ought to be an official container for this. This is... not fun to DIY.

**Comment by rektide** [comment]
Notable gotcha of using the release .deb's when trying to build an image is that the official Docker image is Jessie, but it just has a minimal httpd release plunked down into /usr/local/apache2. To install the mod_auth_openidc release deb, I have to go install apache-api-20120211 which installs an apache2-bin. That's fine, but it definitely feels unideal now having an image with two httpds on it. One of those things that would be great to see an official Docker image handle more gracefully.

**Comment by rahogata** [comment]
I have created an alpine docker image which includes openidc plugin as a hobby project, I would like to share that here of that [here](https://hub.docker.com/r/rahogata/mod_auth_openidc_docker),  there is no much documentation I am newbie to that will update it soon. Please review and give suggestions.

**Comment by dpraul** [comment]
I recently built an updated version of the debian image to work with the latest version of `httpd`, which I'll also share here. Only improvement it could use is possibly building its own version of `libcjose`, but I haven't added that yet:

<details><summary>mod_auth_openidc on httpd:2.4.41</summary>
<p>

```Dockerfile
FROM httpd:2.4.41 as apache
# httpd defines HTTPD_PREFIX as apache2 directory
RUN DEPS_RUNTIME=" \
        libcurl4 ca-certificates \
        libcjose0 \
        libjansson4 \
        libhiredis0.14 \
        libpcre3 \
        " \
    # install runtime dependencies
    && apt-get update \
    && apt-get install -y --no-install-recommends $DEPS_RUNTIME \
    && rm -rf /var/lib/apt/lists/*

FROM apache as build
ARG OPENIDC_VERSION=v2.4.0
ARG OPENIDC_TARBALL_SHA1=e2eb381e142520f8ba20fafcb802c0077f5738de
ARG OPENIDC_TARBALL_URL=https://api.github.com/repos/zmartzone/mod_auth_openidc/tarball/$OPENIDC_VERSION

WORKDIR /build
RUN DEPS_BUILD=" \
        autoconf \
        automake \
        curl \
        gcc \
        gdb \
        lcov \
        libcjose-dev \
        libcurl4-openssl-dev \
        libhiredis-dev \
        libjansson-dev \
        libpcre3-dev \
        libssl-dev \
        libxml2-dev \
        libtool \
        make \
        pkg-config \
        valgrind \
        " \
    # install build dependencies
    && apt-get update \
    && apt-get install -y --no-install-recommends $DEPS_BUILD \
    && rm -rf /var/lib/apt/lists/* \
    # download and verify mod_auth_openidc
    && curl -L $OPENIDC_TARBALL_URL -o mod_auth_openidc.tar.gz \
    && echo "$OPENIDC_TARBALL_SHA1 mod_auth_openidc.tar.gz" | sha1sum -c - \
    && tar xfz mod_auth_openidc.tar.gz --strip=1 \
    # install mod_auth_openidc using apxs from httpd-bundled version
    && ./autogen.sh \
    && ./configure --with-apxs2=${HTTPD_PREFIX}/bin/apxs \
    && make \
    && make install

FROM apache as runtime
COPY --from=build ${HTTPD_PREFIX}/modules/mod_auth_openidc.so ${HTTPD_PREFIX}/modules/mod_auth_openidc.so
```

</p></details>

**Comment by zandbelt** [comment]
why wouldn't you use the Buster packages that one can download from the Releases page of this project?

**Comment by solsson** [comment]
I use [the Buster packages](https://github.com/solsson/openidc-keycloak-test/blob/master/httpd-openidc/Dockerfile) (note that the build also contains some unrelated conf changes we use). The question is how to handle the dependency to `apache2-api-20120211`? With buster that installs as `apache-bin`. Could we somehow skip that dependency when using the official docker image?

**Comment by zandbelt** [comment]
there's no dependency on `apache2-api-20120211` (that's just what your Docker image explicitly installs), just `apache-bin` and of course one cannot skip the latter

**Comment by dpraul** [comment]
> why wouldn't you use the Buster packages that one can download from the Releases page of this project?

Two reasons: I originally made the image before you released any Buster packages, and it was easier to circumvent the dependency on `apache2-bin` by directly compiling it against the version built into `httpd`. Plus with multi-stage builds it is easy to not leave behind any build dependencies/artifacts.
