### ISSUE TITLE
Access to refresh token

### ISSUE THREAD

**Issue by billpratt** [pingidentity/mod_auth_openidc#132]
I have a SPA app that needs to refresh a user's access token. I cant use the method this mod requires to refresh the token because I will need access to the new access token. Can the mod be updated to either A) Return the new access token or B) provide access to the refresh token in the headers similar to OIDC_access_token?

**Comment by zandbelt** [comment]
You should be able to use:

    Header set OIDC_access_token "%{OIDC_access_token}e" env=OIDC_access_token

to make the access token available to the SPA and it will be the current access token, so will be the new token after it is refreshed using A); see #76 

B) is not the preferred route as it requires access to the client secret in the SPA which is not good security practice as it cannot be protected

**Comment by billpratt** [comment]
Thanks. I'll give that a try. For B) I would not expose the refresh token to the SPA but instead use it on the server to refresh the token. Essentially the SPA would call back to the server to say "refresh my access token". I'll give A) a try first

**Comment by billpratt** [comment]
The solution you provided works. Thank you!

**Comment by zandbelt** [comment]
FYI: there's a new feature coming up called "session hook" that allows for a more generic and cleaner approach to this issue i.e. getting hold of the access token and optionally refreshing it: https://github.com/pingidentity/mod_auth_openidc/wiki/Session-Info-Hook
