### ISSUE TITLE
OIDCUnAuthAction not accepted in apache Location tag

### ISSUE THREAD

**Issue by sreuland** [pingidentity/mod_auth_openidc#134]
I'm using mod_auth_openidc 1.8.8 on apache 2.4.18 on Win64. I'm getting an apache startup error:

Invalid command 'OIDCUnAuthAction', perhaps misspelled or defined by a module not included in the server configuration****

i have this in apache conf:

```
<Location /api/>
    AuthType opened-connect
    Require valid-user
    OIDCUnAuthAction 401
</Location>
```
Is OIDCUnAuthAction supported in 1.8.8? This works fine on 1.8.7 release.

**Comment by zandbelt** [comment]
I just reprodcued this and it seems that I've uploaded some older version instead of 1.8.8; I've corrected it now on the release page: https://github.com/pingidentity/mod_auth_openidc/releases/tag/v1.8.8
