### ISSUE TITLE
segfault trying to setup resource server

### ISSUE THREAD

**Issue by brianwcook** [pingidentity/mod_auth_openidc#138]
I am trying to setup a resource server.  Right now it is a simple setup based on the readme.  I am purposefully not sending a token expecting to get a 401 error, but instead I am getting a segfault and no data returned.  It may be a configuration issue but I'm not sure what to look at.

`[Sun May 01 00:35:06.275872 2016] [authz_core:debug] [pid 31332] mod_authz_core.c(809): [client 8.27.177.130:45730] AH01626: authorization result of Require valid-user : denied (no authenticated user yet)
[Sun May 01 00:35:06.275921 2016] [authz_core:debug] [pid 31332] mod_authz_core.c(809): [client 8.27.177.130:45730] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[Sun May 01 00:35:06.275935 2016] [auth_openidc:debug] [pid 31332] src/mod_auth_openidc.c(2585): [client 8.27.177.130:45730] oidc_check_user_id: incoming request: "/app?(null)", ap_is_initial_req(r)=1
[Sun May 01 00:35:06.276055 2016] [auth_openidc:debug] [pid 31332] src/util.c(772): [client 8.27.177.130:45730] oidc_util_get_cookie: returning "mod_auth_openidc_session" = <null>
[Sun May 01 00:35:06.276068 2016] [auth_openidc:debug] [pid 31332] src/session.c(83): [client 8.27.177.130:45730] oidc_session_load: <null>
[Sun May 01 00:35:07.083125 2016] [core:notice] [pid 31296] AH00052: child pid 31332 exit signal Segmentation fault (11)`

`# Resource Server Settings
    OIDCOAuthClientID    clientname
    OIDCOAuthClientSecret    9832017d-64f3-4360-a3b8-04915c5de052
    OIDCOAuthIntrospectionEndpoint    <introspection url>
    OIDCOAuthIntrospectionEndpointMethod    POST
    OIDCOAuthSSLValidateServer    Off
    OIDCOAuthRemoteUserClaim    audience
    OIDCOAuthIntrospectionTokenParamName    token

  <Location "/app">
    AuthName "app Authentication"
    Authtype openid-connect
    Require valid-user
    Require claim iss:https://<idp url>
    LogLevel debug
  </Location>

`

**Comment by brianwcook** [comment]
nevermind, this was caused by the resource server specifying "openid-connect" instead of oauth20 as the authtype.

**Comment by zandbelt** [comment]
thanks for reporting; that deserves better handling which I added in the commit above
