### ISSUE TITLE
Disable caching

### ISSUE THREAD

**Issue by ondrejvelisek** [pingidentity/mod_auth_openidc#139]
Hello,

Great piece of software. It is very helpful. 

I use it as OAuth2 resource server. But I would like to turn off caching because I need to revoke access to resource instantly after revoking token on authorization server. 

When I tried to set OIDCCacheShmMax to 0 I get sometimes (do not know when) Apache errors. Is there a proper (Or at least another) way how to disable caching?

Thank you

Ondrej

**Comment by zandbelt** [comment]
You should make the Authorization Server indicate that the token should not be cached. i.e. in  `expires_in` value of the token introspection result.

**Comment by ondrejvelisek** [comment]
I'm not sure we understand each other. If token is cached on the resource server (in openidc module) it does not even contact authorization server, right?

If module askes for the first time I send expiration time. But if somebody decides to revoke token on authorization server earlier than expiration time (e.g. user decide he do not want to give access to the client anymore) module had no opportunity to find out.

**Comment by zandbelt** [comment]
Bottom line is: if the Authorization Server wants to be able to allow token revocation, it should make the Resource Server not cache the token by sending the appropriate `expires_in` value.

Theoretically there could be a configuration option that overrides the cache hint from the authorization server, but practically it doesn't make sense to try and support token revocation without the Authorization Server supporting it so I'd say you should configure the Authorization Server appropriately.

**Comment by ondrejvelisek** [comment]
Ehm. Where did you find it? It is not in spec, is it?

**Comment by zandbelt** [comment]
As https://github.com/pingidentity/mod_auth_openidc/wiki/OAuth-2.0-Resource-Server suggests it depends on the Authorization Server that you use. If it implements RFC 7662 the relevant claim would be called `exp`. mod_auth_openidc supports a range of variants.

**Comment by ondrejvelisek** [comment]
I think I got it. Expires_in value can be different for client and resource server. And these values can be less than real expiration time of token. And in case I do not want to cache it server has to put 0 value in expiration_in for resource server. Unfortunately my authorization server (OAuth-Apis) seems it can not distinguish these two values. I will figured out it somehow. Anyway the value should be called different (e.g. cache_time) if it is something different than expiration time. :/ 

Thank you. You can close it.

Ondrej

**Comment by zandbelt** [comment]
if you think about long enough you'll see that there is no difference
