### ISSUE TITLE
different IDP for resource server paths

### ISSUE THREAD

**Issue by brianwcook** [pingidentity/mod_auth_openidc#140]
Is it possible to have a resource server require use different introspection servers based on the path that  is being accessed?  I tried to move some of the resource server configuration directives to a <location> directive and it said they were not allowed there. I can set my Require claim iss: different in <location>, but I don't see how to tell it how to actually check the token against the different servers.

**Comment by zandbelt** [comment]
that is not possible at the moment; I'll look into the complexity/consequences in the coming week(s); in the mean time a possible workaround may be to use different virtual hosts

**Comment by zandbelt** [comment]
I'm sorry: it would take quite a few changes in the config sections and that's too much for me at this point in time. I'll consider pulling patches though...
