### ISSUE TITLE
Issues with Firefox/Google Account

### ISSUE THREAD

**Issue by crlshn** [pingidentity/mod_auth_openidc#142]
Firefox 46 Ubuntu 16.04 but also confirmed on firefox for windows

when the user have 2 GMAIL accounts open or declared in the firefox browser... .triger the Oauth show the other account.. even if you close the "Tab"

and the apache2 configuration require:
```
" `<Location` /protected>
                        AuthType openid-connect
                        Require claim hd:some_domain.com
           ....
"
```
firefox url: 
https://accounts.google.com/AccountChooser?continue=https://accounts.google.com/o/oauth2/v2/auth?scope%3Dopenid%2Bemail%2Bprofile%26response_type%3Dcode%26state%3DiHs0CX-it2mjV597t9dk2VOh3fE%26redirect_uri%3Dhttps://some_webserver/protected/redirect_uri%26nonce%3DnkCnmDBe_some_data_0knq3FkSc_gB74%26client_id%3D157071164604-bk_some_key_leusercontent.com%26from_login%3D1%26as%3Dbb8b7a13ede06fc&btmpl=authsub&scc=1&oauth=1

![screenshot](https://cloud.githubusercontent.com/assets/2448271/15306803/f59469a6-1b8a-11e6-851e-c6fd82f57137.png)

The firefox will only show the select account.....if you click you are redirected to select account

I clone the Git on the "Apr 12"

**Comment by crlshn** [comment]
of course if the "user" close the "@gmail.com" session... the auth pass with the @some_domain.com with no other issues.

**Comment by zandbelt** [comment]
as the README.md at https://github.com/pingidentity/mod_auth_openidc#openid-connect-sso-with-google-sign-in says: to skip the account chooser screen you must add `hd=<your-domain>` to the authentication request

**Comment by crlshn** [comment]
this is the part of the apache.conf : 

```
<IfModule mod_auth_openidc.c> 
                OIDCProviderMetadataURL https://accounts.google.com/.well-known/openid-configuration
                OIDCClientID xzxzccxz
                OIDCClientSecret sadasdasd

                OIDCRedirectURI https://support.panoramalife.com/glpi/redirect_uri
                OIDCCryptoPassphrase <password>
                OIDCScope "openid email profile"
                <Location /glpi>
                        AuthType openid-connect
                        Require claim hd:panoramalife.com
                        Options FollowSymLinks
                        DirectoryIndex index.php
                </Location>
</IfModule>
```

as far I know I am following exactly te README.md....

method to reproduce the issue:

on firefox:
step 1. open your gmail with the account @panoramalife.com 
step 2. open your gmail with the account @gmail.com

step 3. open the website https://support.panoramalife.com/glpi/ select your account @panoramalife.com and see that nothing is happening... 

BTW 
.htaccess had 

```
ErrorDocument 401 "/logout.php"
ErrorDocument 500 "/logout.php"
```

**Comment by zandbelt** [comment]
use `OIDCAuthRequestParams hd=panoramalife.com`

**Comment by crlshn** [comment]
thanks a lot, tested and working
