### ISSUE TITLE
Use of mod_auth_openidc with SPA application

### ISSUE THREAD

**Issue by r0main** [pingidentity/mod_auth_openidc#143]
HI,

We are trying to integrate "mod_auth_openidc" with our AngularJS application, but we struggle a bit. The problem is when the client is disconnected from the RP and the client issues an XHR request. This request receive a 302, redirecting to the OP (the form login page of the OP for us). But it's the XHR request wo receive the 302, not the browser... So nothing happen from the user point of view...

We came across with some solutions but we could not find the clean solution we wanted. Our best solution for now is to refresh the browser when our XHR call receives the login form page, then the browser will receive the 302 and will be redirected to the login page. But we would like to find a better solution.

In your opinion what is the best solution in this case ? Can mod_auth_openidc be used for this use case ?

Thanks for the help.

**Comment by zandbelt** [comment]
There is an optimization scenario where the XHR response would be a 401 instead of a redirect to a login form, by instrumenting the XHR paths with `OIDCUnAuthAction 401`, or auto-magically by making your Angular JS application send a `X-Requested-With` header on its requests.

You then still have to instruct the browser to redirect to the OP, there's no way around that and that is the purpose of OpenID Connect. Making it hit a protected page is indeed a good way of doing this; alternatively you could initiate the redirect in your application directly by constructing a so-called "3rd-party init SSO" URL as documented in the README.md (near the end of the section on multiple OPs).

I'll leave this ticket open for a while for other people to add suggestions. There are a number of closed issues that are related to this type of discussion.

**Comment by r0main** [comment]
Thank you for your help. 

When you say in the documentation (here : https://github.com/pingidentity/mod_auth_openidc/wiki/Cookies) : "protect Javascript paths with OIDCUnAuthAction 401". Do you mean "protect path that are called by XHR/AJAX with OIDCUnAuthAction 401" ?

I like the solution of having a 401 as it is the clean way of saying a client is not authenticated against a REST resource. I'll try that and let you know.

If I understand it well. In an SPA application, only the index.html should be protected with "OIDCUnAuthAction auth" (maybe other static files as JS, fonts, and CSS ?) and all other path that will be called via XHR should be protected with "OIDCUnAuthAction 401". And it is the job of the application to handle these 401, by making the browser hit a protected resource (like the index.html for example).

I imagine that to be sure the index.html is not cached by the browser, we should add some "no cache" headers in the response of that file ?

What is the advantage to create the "3rd-party init SSO" URL ? Less redirection for the user ?

**Comment by zandbelt** [comment]
> When you say in the documentation (here : https://github.com/pingidentity/mod_auth_openidc/wiki/Cookies) : "protect Javascript paths with OIDCUnAuthAction 401". Do you mean "protect path that are called by XHR/AJAX with OIDCUnAuthAction 401" ?

yes

> If I understand it well. In an SPA application, only the index.html should be protected with "OIDCUnAuthAction auth" (maybe other static files as JS, fonts, and CSS ?) and all other path that will be called via XHR should be protected with "OIDCUnAuthAction 401". And it is the job of the application to handle these 401, by making the browser hit a protected resource (like the index.html for example).

yes, or if the client sets the `X-Requested-With` automatically or you can make it do so, it should work with no special configuration of paths

> I imagine that to be sure the index.html is not cached by the browser, we should add some "no cache" headers in the response of that file ?

most probably, yes

> What is the advantage to create the "3rd-party init SSO" URL ? Less redirection for the user ?

indeed you'd save one round-trip; I actually wouldn't prefer this solution but depending on your requirements it may be a good fit

**Comment by r0main** [comment]
Thank you for your help and reactivity. Thanks to you we manage to get a lot more stable application.

Only the index.html receives 302, all the rest receives 401. We don't have problems with cookie any more.

One last thing. When we call the "redirect_uri" and the session has expire in auth_openidc, we are redirecting to the OP. But when the OP session has not expired we are automatically reconnected and redirected to the RP. When you call the redirect_uri for a logout this behavior is a bit strange for the user. Do you have a clean solution for this ? My guess is to have OP & RP sessions with the same timeout but it is not perfect and easy, and we don't really control with precision the OP session in our case.

**Comment by zandbelt** [comment]
the logout option by default kills the session that mod_auth_openidc has create, perhaps not useful in an SSO system indeed for the reason you mention; but, synchronizing sessions between an OP and several RPs is a hard problem, not specific to mod_auth_openidc or OpenID Connect

my (personal) advice would be not to offer a logout option but let the user know that he needs to close the browser to logoff

yet mod_auth_openidc implements the Session Management implementer's draft that could be used if only the OP and the other RPs play their part as well, see: https://github.com/pingidentity/mod_auth_openidc/wiki/Session-Management
