### ISSUE TITLE
mod_auth_openidc and keycloak - session management

### ISSUE THREAD

**Issue by jannikhuels** [pingidentity/mod_auth_openidc#144]
Hi,

I am using mod_auth_openidc together with keycloak. I was wondering if there is any way to manage the session without using the iframes, e.g. that caching is disabled within mod_auth_openidc? Or is there any workaround that ensures that within every request mod_auth_openidc validates the authentication againts keycloak?

Thanks in advance!

**Comment by zandbelt** [comment]
You may be confusing OpenID Connect's "federated" session management (with the iframes) with the module's local session management.

This question seems to be about local session management but I'm not sure what you want to achieve: the OpenID Connect flow delivers an `id_token` to the module that authenticates the user. That token is one-time usage, i.e. it is not stored anywhere and the browser wouldn't be able to present it again in the next request. What mechanism do you propose to manage the session?

**Comment by jannikhuels** [comment]
I see this behaviour in my current setting:

1. Access a app that is secured by mod_auth_openidc
2. Redirect to keycloak login page and authenticate the user
3. Destroy session in keycloak
4. Reload the app protected by mod_auth_openidc => User is still logged in.

When I reduce the `OIDCSessionInactivityTimeout` to e.g. 5 seconds the remote logout will be performed (after a 5 seconds delay). So I suggested that mod_auth_openidc is caching its `session_token` and thus I had to use "federated" session management with iframes to manage these remote logouts. Or do I just misconfigured mod_auth_openidc?

**Comment by zandbelt** [comment]
You want to achieve a federated logout but I believe Keycloak does not support OpenID Connect Session Management. It is not a final spec yet. The current behaviour means that the session on Keycloack is killed but not the session on Apache because it is not told to do so.

**Comment by jannikhuels** [comment]
Okay. Thank you.
So can you propose any workaround to get this down for now? I am thinking about doing a authentication against keycloak for every request in mod_auth_openidc? Is there such a setting? Even if that has not a good performance.
As I see keycloak offers the `LoginStatusIFrameEndpoint`. I tried to use this for the `OIDCProviderCheckSessionIFrame` but that seems not to work...

**Comment by zandbelt** [comment]
No, you would never get back the real content: after authenticating, the module redirects back to the URL that was originally accessed but no session would exist and you'd be redirected again in a loop. Delivering tokens to those URLs directly leads to insecure deployments and doesn't comply with the OpenID Connect specification.

What you could do is trigger logout from the RP, i.e. the module; since Keycloack seems to support an `end_session_endpoint`, after killing the session locally the module would redirect to the OP for logout. See: https://github.com/pingidentity/mod_auth_openidc/wiki#9-how-do-i-logout-users.

That's not true global logout (as other RP sessions may still exist) but may be what you're looking for. Let me know.

**Comment by jannikhuels** [comment]
Okay, the logout via the RP works fine. But the total setup I want to reach is slightly more difficult.

Besides the RP I have a RestAPI that connects directly to keycloak via OpenID Connect. Single-Sign-on between the RP and the RestAPI works fine. Likewise I have no problem when logout is done via the RP, the Session then is also destroyed in keycloak due to provided the `end_session_endpoint`. 

But if I login through the RP, call the RestAPIs Application and then logout, again the RP does not mention the logout (since the RestAPI only calls the 'end_session_endpoint' in keycloak). I thought about calling the `?logout=` url of the RP from the RestAPI, but I need to have a redundant set of many RPs  behind a Loadbalancer and so I have to take care that I always call the correct RP to logout. 

So as I see I have to make sure how the `OIDCProviderCheckSessionIFrame` may work with keycloak. Do you think it is a possible workaround to call the logout on all RPs from the RestAPI in case the session cookie written by mod_auth_openidc is available? I unfortunately have no idea on how to get this single-sign-out working in my setup.

**Comment by zandbelt** [comment]
a redundant set of many RPs should use a shared caching mechanism between them so removing a session would remove it for all of them, see: https://github.com/pingidentity/mod_auth_openidc/wiki/Caching

what you're looking for is Single Logout, which is an "asymptotic" goal in general in distributed systems; `mod_auth_openidc` plays it part though; your best chance is to have both Keycloak and the RestAPI support OIDC's Session Management

**Comment by tzelve** [comment]
Maybe too late but i have somethink to suggest here. 
You can set OIDCSessionMaxDuration 0 so your session will have the duration of your access token, and when will expire module will try to refresh access token.

**Comment by zandbelt** [comment]
Using `OIDCSessionMaxDuration 0` would set the maximum lifetime of the session to the value in the `id_token`, not the `access token`.  The `access_token` and and refreshing that is unrelated.

**Comment by zandbelt** [comment]
For the record: Keycloak supports standards-compliant OpenID Connect Session Management now.
