### ISSUE TITLE
Repeat Authentication Request

### ISSUE THREAD

**Issue by jannikhuels** [pingidentity/mod_auth_openidc#147]
Hi,

I recently read the OpenID Connect Session Management 1.0 specification. There it is said that it may be possible to repeat the authentication process using `prompt=none` parameter. I am aware of the network traffic, but it seems that we need that repeat in one special case to implement single sign out.

I was wondering if mod_auth_openidc supports the `prompt=none` parameter and therefore repeating re-authentication?

Thanks in advance.

**Comment by zandbelt** [comment]
mod_auth_openidc supports the session management implementer's draft specification and thus it will perform re-authentication with `prompt=none` whenever a session state change is signaled from the OP as described in section 4.1 of the spec: http://openid.net/specs/openid-connect-session-1_0.html#RPiframe; if the user was logged out from the OP that will generate an error response and kill the module's session as well

Does that answer your question?

**Comment by jannikhuels** [comment]
Ok, thank you. 

May it be possible to provide static content in the `openidc-op` iframe like `<client id> changed` such that it re-validates the session everytime such content is provided? 
The problem is that I intend to try to use a OP that seems not to implement the OpenID Connect session management correctly. I therefore try to implement a work-around to be able to get Single-Sign Out working. 
And what `<redirect uri>` has to be provided within the iframes?

**Comment by zandbelt** [comment]
that may be possible but seems very expensive and subject to DoS

the redirect URI is the one configured in `OIDCRedirectURI`

**Comment by jannikhuels** [comment]
Ok. Thank you!

**Comment by zandbelt** [comment]
did you mean to reopen?

**Comment by jannikhuels** [comment]
Sorry, it seems that I hit reopen accidentally.

Just one more short question: I plan to extend the module so that it uses no cache and re-authenticates the user for every request. I think that is the only chance to introduce Single-Logout in our setup since Session-Management is not supported by the OP. 
Am I right that this does not violate the OpenID Connect spec? 

Invalidating the Cache (setting `OIDCSessionInactivityTimeout 5`) leads to the problem that Post requests are changed to Get (regarding to the 302 HTTP Spec) which destroys AJAX requests. We tried to set the `OIDCUnAuthAction pass` for the specific AJAX requests, but isn't it a security issue?

**Comment by zandbelt** [comment]
it doesn't violate the spec but I'd still question this approach; it would only work in a scalable way if the browser requests only 1 resource at a time

you're correct that unauthenticated POST request "lose" context when being redirected for authentication; typically you'd use `OIDCUnAuthAction 401`, and have the client detect that situation ("catch" the 401) and redirect the top-level browser window for authentication; `pass` doesn't protect indeed
