### ISSUE TITLE
Unable to get module to install on centos6 with cpanel

### ISSUE THREAD

**Issue by bmbermn** [pingidentity/mod_auth_openidc#150]
I cannot seem to find a way to install this as a custom module under easy apache and building it directly into apache did not seem to work either, do you have any ideas or directions that might help?

**Comment by zandbelt** [comment]
What is the error you're experiencing?

Here's an install sequence that works on centos6: https://github.com/zandbelt/mod-auth-openidc-dist/blob/master/centos/6/run/Dockerfile
with this release binary: https://github.com/pingidentity/mod_auth_openidc/releases/download/v1.8.10/mod_auth_openidc-1.8.10-1.el6.x86_64.rpm

**Comment by bmbermn** [comment]
I get an error about http is needed when I try to configure the module. 

I tried to follow the instructions found at https://documentation.cpanel.net/display/EA/Custom+Modules
and was still unable to get this module activated

**Comment by zandbelt** [comment]
that's a question for cpanel then
