### ISSUE TITLE
Type error in authz_status oidc_authz_checker

### ISSUE THREAD

**Issue by gwollman** [pingidentity/mod_auth_openidc#151]
If I knew what the correct fix was, I'd send in a PR instead, but since I don't quite understand what's intended here...

At line 2680 in src/mod_auth_openidc.c:
```c
        if ((rc == HTTP_UNAUTHORIZED) && ap_auth_type(r)
```
rc is of type authz_status, and HTTP_UNAUTHORIZED is not in the domain of this type, so clang will consider the test to be always false, and optimize out the entire "unreachable" if statement.  I'm not sure what the intended comparison is -- should it be AUTHZ_DENIED?

**Comment by zandbelt** [comment]
you're right this seems to be a copy/paste error from the Apache 2.2 code in `oidc_auth_checker`
