### ISSUE TITLE
Return user's email

### ISSUE THREAD

**Issue by ngoduykhanh** [pingidentity/mod_auth_openidc#152]
Hi,

. I've setup the authentication successfully with the configs:

```
OIDCProviderMetadataURL https://accounts.google.com/.well-known/openid-configuration
OIDCClientID <hide>.apps.googleusercontent.com
OIDCClientSecret <hide>

OIDCRedirectURI https://mydomain.com/app/redirect
OIDCCryptoPassphrase <password>
OIDCScope "openid email profile"
OIDCOAuthIntrospectionEndpointAuth client_secret_basic
OIDCOAuthRemoteUserClaim user_id

Alias /app "/usr/share/app/public"

<Directory "/usr/share/app/public">
    AuthType openid-connect
    Require valid-user
    
    ......
```

After passing the authentication step, from application, I can get the logged in username is 1063422166487xxxxxxx@accounts.google.com. How can I return the user's email address instead of their google id?

**Comment by zandbelt** [comment]
Use `OIDCRemoteUserClaim email` as documented in https://github.com/pingidentity/mod_auth_openidc/blob/master/auth_openidc.conf#L549
