### ISSUE TITLE
Proposal: Use Cookie-Chunking for client-cookie

### ISSUE THREAD

**Issue by glatzert** [pingidentity/mod_auth_openidc#153]
The documentation for `OIDCSessionType` states
> *** WARNING: WITH client-cookie YOU MAY RUN EASILY OVER THE SIZE LIMIT FOR COOKIES, USE WITH CARE ***

this might totally be true, but we think, there might be an easy solution, which is commonly used in implementations of WS-Fed an SAML: chunked cookies.

Essentially the cookie content is split into multiple chunks of 4k as necessary and the cookies are named auth_cookie_0, auth_cookie_1, auth_cookie_2, ... you could also place a cookie, telling how many chunks to expect.
This allows cookie sizes up to ~50k per domain (which is uncommon, but i've seen a lot of 4k+2k in SSO) and allows the server hoster to go without server state in HA scenarios.

If you are open for pull-requests, we'd also happily spend the time to implement a client-chunked-cookie SessionType ourselfs and push it back into your module.

**Comment by zandbelt** [comment]
That sounds good indeed. I'd be happy to merge a PR.

**Comment by glatzert** [comment]
So I tried to implement it, but I had not time to get an environment up for building it.
Perhaps someone here has the time to validate my code before I PR it?
https://github.com/glatzert/mod_auth_openidc/commit/4ab7ca50fc839495476a6c48373445ca178c410d
