### ISSUE TITLE
The OpenID Connect Provider returned an error: Error in handling response type

### ISSUE THREAD

**Issue by mailugk** [pingidentity/mod_auth_openidc#154]
We have ping federate 7.1.3 environment that we are trying to upgrade on Ping 8.1 version. after upgrade when we tested some of the OIDC enabled apps they are failing with below error ( SAML apps working fine after upgrade)-
**"The OpenID Connect Provider returned an error: Error in handling response type"**
however we can see successful attempt in ping Audit log no failure.We aren’t seeing anything in the server.log that indicates a problem either, so we are stuck at this point .

**Comment by zandbelt** [comment]
Can you paste the error.log on the Apache side?
