### ISSUE TITLE
Does mod_auth_openidc support STS(Security Token Service)?

### ISSUE THREAD

**Issue by GPrathap** [pingidentity/mod_auth_openidc#156]
Since mod_auth_openidc is an authentication/authorization module for the Apache 2.x HTTP server that authenticates users against an OpenID Connect Provider. If OpenID Connect Provider supports STS(Security Token Service) does mod_auth_openidc is supported for that.

**Comment by zandbelt** [comment]
I'd say no, but I'm also curious as to which STS specification you are referring to and what use case you would like to solve with it.

**Comment by GPrathap** [comment]
Foa an example, https://docs.wso2.com/display/IS510/How+To%3A+Secure+the+Security+Token+Service

**Comment by zandbelt** [comment]
That's a WS-Trust STS from the SOAP/XML era that hasn't got anything todo with OpenID Connect and mod_auth_openidc will never support that but I also don't see what the module would do with it since it doesn't call APIs itself other than the stock userinfo endpoint with the regular access token.
