### ISSUE TITLE
cannot load module Apache 2.4.23

### ISSUE THREAD

**Issue by jakiiki** [pingidentity/mod_auth_openidc#157]
I am encountering this error when I try to the load the module in Apache 

./apachectl start
httpd: Syntax error on line 151 of /opt/apache/conf/httpd.conf: Cannot load modules/mod_auth_openidc.so into server: /opt/apache/modules/mod_auth_openidc.so: **undefined symbol: oidc_create_dir_config

Any ideas? 

N.B. This is my first time trying to compile and load an Apache module

Thanks

**Comment by zandbelt** [comment]
Why not use one of the existing binary distributions from https://github.com/pingidentity/mod_auth_openidc/releases/?

Did you follow https://github.com/pingidentity/mod_auth_openidc/blob/master/INSTALL?

**Comment by zandbelt** [comment]
any news on this?

**Comment by jakiiki** [comment]
Still run into the same issue. I also tried using the already compiled module and but run into another undefined symbol error: undefined symbol: ap_requires. I will try to downgrade from apache 2.4 to 2.2 and try again.

**Comment by zandbelt** [comment]
Yes, this is an Apache version /module version issue; you need to load a module compiled for the  Apache version at hand. See #101 and #58.

**Comment by jakiiki** [comment]
Got it fixed by installed Apache 2.2.23; I have another question for you but will ask it in a separate thread.
