### ISSUE TITLE
dynamically grant access to user's folder

### ISSUE THREAD

**Issue by uotw** [pingidentity/mod_auth_openidc#158]
Hello. I've got a PHP-based website on a LAMP server using auth0 authentication where users upload a set of files to a dynamically-generated folder. I'd like each of these folders to only be accessible by the auth0 user who uploaded them (and to those they grant access). The folder authorization access is logged in a database. I've read the mod_auth_openidc auth0 docs, but I'd like some clarification. It looks like one can add a folder rule to the apache config file (requiring a apache restart?)... How would I be able to dynamically add this kind of access?

Thanks

**Comment by zandbelt** [comment]
That should be possible by writing .htaccess files in the dynamically generated directory, at the cost of some performance. See: https://httpd.apache.org/docs/current/howto/htaccess.html Let me know how that works out.

**Comment by uotw** [comment]
Looks like the folder directive [cannot go in](http://httpd.apache.org/docs/2.2/mod/core.html#location) .htaccess, only the files.  Any other thoughts on how I can leverage mod_auth_openidc to dynamically protect a user's files?

**Comment by zandbelt** [comment]
The folder directive is implicit: the .htaccess file is authoritative for the folder that you put it in. I just verified that this works so this turns into an Apache configuration issue that you have to solve elsewhere.
