### ISSUE TITLE
OpenID Connect Provider error

### ISSUE THREAD

**Issue by kochsen** [pingidentity/mod_auth_openidc#159]
I'm trying to use an Apache 2.4.23 as an RP for Google as the OP. Below are my Apache configurations:

OIDCProviderMetadataURL https://accounts.google.com/.well-known/openid-configuration
OIDCClientID 766186240044-ltr2s0dffm6tig94apslnsse1p87ps79.apps.googleusercontent.com
OIDCClientSecret <google client secret>
OIDCRedirectURI https://server.dev.test:8443/oauth2callback
OIDCCryptoPassphrase password
OIDCProviderIssuer accounts.google.com
OIDCProviderAuthorizationEndpoint https://accounts.google.com/o/oauth2/auth
OIDCProviderJwksUri https://www.googleapis.com/oauth2/v2/certs
OIDCProviderTokenEndpoint https://accounts.google.com/o/oauth2/token
OIDCProviderTokenEndpointAuth client_secret_post
OIDCProviderUserInfoEndpoint https://www.googleapis.com/plus/v1/people/me/openIdConnect
OIDCSessionInactivityTimeout 3600
OIDCProviderJwksUri https://www.googleapis.com/oauth2/v2/certs

\<Location />
   AuthType openid-connect
   Require valid-user
\</Location>

Once I access the Apache instance I get the following error in the browser:

**Error:  OpenID Connect Provider error: Error in handling response type.**

I see the following errors in the Apache error.log:

[auth_openidc:error] [pid 2072:tid 140442616174336] [client 172.31.65.6:49426] oidc_util_json_string_print: oidc_util_check_json_error: response contained an "error" entry with value: ""invalid_request"", referer: https://accounts.google.com/ServiceLogin?passive=1209600&continue=https://accounts.google.com/o/oauth2/auth?scope%3Dopenid%26response_type%3Dcode%26state%3Dl7uBAcUTn01WBfL3nAAjoDc_44o%26redirect_uri%3Dhttps://server.dev.test:8443/oauth2callback%26nonce%3DNH3MR2ieziaea5WRkhFqHBS0f9ZyPZt23GIoFoe96bI%26client_id%3D766186240044-ltr2s0dffm6tig94apslnsse1p87ps79.apps.googleusercontent.com%26from_login%3D1%26as%3D5bff1910603ca1ca&oauth=1&sarp=1&scc=1

[auth_openidc:error] [pid 2072:tid 140442616174336] [client 172.31.65.6:49426] oidc_util_json_string_print: oidc_util_check_json_error: response contained an "error_description" entry with value: ""Parameter not allowed for this message type: state"", referer: https://accounts.google.com/ServiceLogin?passive=1209600&continue=https://accounts.google.com/o/oauth2/auth?scope%3Dopenid%26response_type%3Dcode%26state%3Dl7uBAcUTn01WBfL3nAAjoDc_44o%26redirect_uri%3Dhttps://server.dev.test:8443/oauth2callback%26nonce%3DNH3MR2ieziaea5WRkhFqHBS0f9ZyPZt23GIoFoe96bI%26client_id%3D766186240044-ltr2s0dffm6tig94apslnsse1p87ps79.apps.googleusercontent.com%26from_login%3D1%26as%3D5bff1910603ca1ca&oauth=1&sarp=1&scc=1

[auth_openidc:error] [pid 2072:tid 140442616174336] [client 172.31.65.6:49426] oidc_proto_resolve_code_and_validate_response: failed to resolve the code, referer: https://accounts.google.com/ServiceLogin?passive=1209600&continue=https://accounts.google.com/o/oauth2/auth?scope%3Dopenid%26response_type%3Dcode%26state%3Dl7uBAcUTn01WBfL3nAAjoDc_44o%26redirect_uri%3Dhttps://server.dev.test:8443/oauth2callback%26nonce%3DNH3MR2ieziaea5WRkhFqHBS0f9ZyPZt23GIoFoe96bI%26client_id%3D766186240044-ltr2s0dffm6tig94apslnsse1p87ps79.apps.googleusercontent.com%26from_login%3D1%26as%3D5bff1910603ca1ca&oauth=1&sarp=1&scc=1

**Comment by zandbelt** [comment]
You should get rid of:

````
OIDCProviderIssuer 
OIDCProviderAuthorizationEndpoint 
OIDCProviderJwksUri (2x)
OIDCProviderTokenEndpoint 
OIDCProviderTokenEndpointAuth 
OIDCProviderUserInfoEndpoint
````
as all of those are dynamically set from `OIDCProviderMetadataURL`

that will make mod_auth_openidc use the latest endpoints that Google provides, not the legacy ones that you've configured statically in your setup; those endpoints will accept the unknown `state` parameter that is not accepted on the legacy endpoints (in contrary to what the spec dictates, hence the upgrade)

**Comment by kochsen** [comment]
Thank you, that worked. I didn't realize the matadata URL set all of those dynamically.
