### ISSUE TITLE
SSL certficate in load balancer

### ISSUE THREAD

**Issue by jakiiki** [pingidentity/mod_auth_openidc#161]
My use case for this module is as follows. We have a load balancer in front of the Apache webserver.
The SSL certificate is stored on the load balance and not on the server running Apache. All request to the load balancer come in as https requests, and passed on to the Apache webserver as http requests. Is there a way to let the module aware that SSL is being handled by upfront by the load balancer?

Thanks

**Comment by zandbelt** [comment]
See: https://github.com/pingidentity/mod_auth_openidc/wiki#8-how-do-i-run-mod_auth_openidc-behind-a-reverse-proxy
