### ISSUE TITLE
Requesting a Refresh Token 

### ISSUE THREAD

**Issue by lg1712** [pingidentity/mod_auth_openidc#162]
Hello,
I'd like to request a refresh token using the OIDC module for apache.

### Issue:
When accessing the service protected by OIDC, the access_token never change.

### Configuration
Latest version of mod_auth_openidc 
Identity provider: Keycloak
Token time to live: 1min 
My OIDC apache vhost configuration is:
OIDCProviderMetadataURL localhost:8080/auth/realms/realm1/.well-known/openid-configuration
OIDCClientID client
OIDCClientSecret 123456789
OIDCRedirectURI localhost:8081/test/secure
OIDCCryptoPassphrase <password>
OIDCOAuthTokenIntrospectionInterval 10

Do you know if this use could work using the OIDC module and if the OIDCOAuthTokenIntrospectionInterval parameter is the suitable one to use?
Link to available parameter: https://github.com/pingidentity/mod_auth_openidc/blob/master/auth_openidc.conf

Thank you

**Comment by zandbelt** [comment]
There's a wiki entry on "access tokens and tefresh tokens" that should explain it.

**Comment by zandbelt** [comment]
https://github.com/pingidentity/mod_auth_openidc/wiki/Access-Tokens-and-Refresh-Tokens

**Comment by lg1712** [comment]
Refreshing the access token using this link <redirect_uri>?refresh=<return_to>&access_token=<access_token>in an application works but if not refreshed and having setting up an Access Token Lifespan of 1min, the OIDC module still authorize accessing the app after the access token expires and without refreshing it.

**Comment by zandbelt** [comment]
What do you mean by access token lifespan and how would you set it? The introspection interval is not a token lifespan but merely an update interval.

**Comment by lg1712** [comment]
In my Keycloak IDP settings, I set the access token to expire after 1 minute. 
When I access the API after 1 minute, now it seems Keycloak issue a new access token as expected

**Comment by zandbelt** [comment]
See https://github.com/pingidentity/mod_auth_openidc/wiki/OAuth-2.0-Resource-Server for the expiry/caching handling of access tokens. By default the `expires_in` claim returned by the authorization server is defining the cache duration.

**Comment by zandbelt** [comment]
Did that help? Do you still have an issue?

**Comment by zandbelt** [comment]
bump

**Comment by gcassata74** [comment]
Hi 
How can I pass the session cookie to the <redirect_uri>?refresh=<return_to>&access_token=<access_token> in order to retrieve the refresh_token from cache?
Ho can I get that session cookie using a curl command?
Thank you
BR

**Comment by zandbelt** [comment]
well once you have the session cookie you can provide it in a Cookie header

but getting the cookie using a curl command would defeat the purpose of having a (secure) session cookie: if such a call would exist it would have to be secured against open access and attackers which pushes the problem "one turtle down"; the required credential for interfacing with mod_auth_openidc **is** the session cookie
