### ISSUE TITLE
./configure --with-apxs2=/opt/apache2/bin/apxs2

### ISSUE THREAD

**Issue by Anid4u2c** [pingidentity/mod_auth_openidc#163]
On Ubuntu:  When I try to configure, I keep getting the same error:

> configure: WARNING: unrecognized options: --with-apxs2

/opt/apache2/bin/apxs2 doesn't exist.

I even installed php and Apache fresh:  http://php.net/manual/en/install.unix.apache2.php

So, I tried:

> ./configure --with-apxs2=/usr/local/apache2/bin/apxs

Same error :(

/usr/local/apache2/bin/apxs DOES exist and is executable... I'll review the INSTALL file some more, but hopefully can get pointed in the right direction.

Assistance please!

Thanks!

**Comment by zandbelt** [comment]
It is probably better to use a binary package from the releases page.

**Comment by zandbelt** [comment]
Were you able to use a binary package?

**Comment by zandbelt** [comment]
it looks like you've installed Apache in a non-standard path

**Comment by Anid4u2c** [comment]
I noticed I didn't reply... I've moved onto other projects.  Will check back on this at a later date.  Thanks for your replies!
