### ISSUE TITLE
InactivityTimeout incorrect GET/POST

### ISSUE THREAD

**Issue by gnm67** [pingidentity/mod_auth_openidc#165]
I have an issue, when a form is being edited and the user takes over 5 minutes to enter all their data when they submit (POST) the form the SSO does a check as the inactivityTimeout has passed. but instead of sending a POST it is then sending a GET instead, which of cause then deletes all the entered data.

Is there an option so it does the POST correctly?

127.0.0.1 - xxx.xxx.xxx.xxx [24/Aug/2016:11:26:37 +0100] "GET /coils/view.php?coil=42 HTTP/1.1" 200 5743
127.0.0.1 - xxx.xxx.xxx.xxx [24/Aug/2016:11:26:41 +0100] "GET /coils/edit.php?coil=42 HTTP/1.1" 200 7851
127.0.0.1 - - [24/Aug/2016:11:31:47 +0100] "**POST** /coils/save.php?action=20 HTTP/1.1" 302 500
127.0.0.1 - xxx.xxx.xxx.xxx [24/Aug/2016:11:31:48 +0100] "GET /redirect_uri?code=***************&state=************** HTTP/1.1" 302 251
127.0.0.1 - xxx.xxx.xxx.xxx [24/Aug/2016:11:31:51 +0100] "**GET** /coils/save.php?action=20 HTTP/1.1" 200 3773
127.0.0.1 - xxx.xxx.xxx.xxx [24/Aug/2016:11:31:52 +0100] "GET /coils/view.php?coil=45 HTTP/1.1" 200 5299

**Comment by zandbelt** [comment]
That's something that is hard to avoid as the roundtrip to the Provider loses the POST data. My first recommendation would be to increase `OIDCSessionInactivityTimeout` as documented in https://github.com/pingidentity/mod_auth_openidc/blob/master/auth_openidc.conf#L393

I have added rudimentary code to store the POST data in HTML local storage before redirecting away but this may result in security issues on shared workstations so I've never really completed it.

**Comment by gnm67** [comment]
Thanks, I thought that might be the case.

**Comment by zandbelt** [comment]
I'll take another look soon

**Comment by zandbelt** [comment]
I have addressed this in the 2.0.x branch: https://github.com/pingidentity/mod_auth_openidc/commit/cd8c8e3aca6c3af7685a546a20a3776359941f7e
You should explicitly enable it with the `OIDCPreservePost` directive (perhaps only on certain paths) since (as noted before) it may result in exposing private data to other users on shared terminals. Let me know if that works for you.
