### ISSUE TITLE
Returns 401 without calling oidc_check_user_id for incoming request

### ISSUE THREAD

**Issue by goyamamoto** [pingidentity/mod_auth_openidc#166]
I have an issue where mod_auth_openidc loads successfully but ap_hook_check_authn is not successful.  It results to return 401 without incoming request on oidc_check_user_id.

I can reproduce the issue on CentOS release 7.2.1511 with mod_auth_mellon installed.
Perhaps there will be some conflict on hooking check_authn.

I think it will be more friendly if mod_auth_openidc aborts when ap_hook_check_authn is not successful.

**Comment by zandbelt** [comment]
The module shouldn't handle the request unless AuthType openid-connect or oauth20 is set on the Location/Directory. If those aren't set, the method would return Decline and the next module on the same hook would be called. Is that different from what you're observing? Could it be that the mod_auth_mellon is returning 401 instead?

**Comment by goyamamoto** [comment]
I don't think it is likely.

The server returns 401 on a location with AuthType openid-connect without reaching at the debug message for incoming request.
https://github.com/pingidentity/mod_auth_openidc/blob/master/src/mod_auth_openidc.c#L2623

The same location works fine for OIDC after unloading mod_auth_mellon.

**Comment by zandbelt** [comment]
mod_auth_mellon is the culprit; similar reports exist: https://bugzilla.redhat.com/show_bug.cgi?id=1333161

You may either try and load mod_mellon *after* mod_auth_openidc or use a fixed version of mod_mellon > 0.12.0 from somewhere that has this patch:
https://github.com/UNINETT/mod_auth_mellon/commit/a99c081b1e7cab3f55cdf3951b0f2c35a3f397f0

**Comment by goyamamoto** [comment]
Confirmed.  Thank you for information.

For our workaround, I think we can consider changing present 10-auth_openidc.conf to 09-... or something in your package.
