### ISSUE TITLE
Feature Request: Lazy/passive sessions a la Shibboleth

### ISSUE THREAD

**Issue by terrencegf** [pingidentity/mod_auth_openidc#167]
mod_shib (part of the Shibboleth Service Provider software) can be configured to allow for [passive protection](https://wiki.shibboleth.net/confluence/display/SHIB2/NativeSPProtectContent) of content, sometimes referred to as "lazy sessions". For example, this allows a service such as [DokuWiki](https://github.com/ivan-novakov/dokuwiki-shibboleth-auth) to show basic content when a user is not authenticated, and detailed content when a user is authenticated.

I would like to request a similar feature for mod_auth_openidc. I haven't looked at the source code for mod_shib, so I have no idea how difficult it would be to implement such a feature.

**Comment by zandbelt** [comment]
That feature is already supported with the `OIDCUnAuthAction pass` directive, see: https://github.com/pingidentity/mod_auth_openidc/blob/master/auth_openidc.conf#L640 Let me know if that doesn't work for you.

**Comment by terrencegf** [comment]
Yes! This works perfectly! Thank you for the quick response.

**Comment by terrencegf** [comment]
A follow-up question on this issue. Is the `OIDCUnAuthAction` directive server-wide? Is it possible to configure this in a `<Location>` block, e.g.  one `<Location>` has `OIDCUnAuthAction auth` but another `<Location>` has `OIDCUnAuthAction pass`?

**Comment by zandbelt** [comment]
It can be used on both levels

**Comment by zandbelt** [comment]
btw, watch out that you're not running in to https://github.com/pingidentity/mod_auth_openidc/issues/170 (that would be when trying to override something else than "auth" with "auth")

**Comment by terrencegf** [comment]
Thank you! That post was also helpful.

**Comment by zandbelt** [comment]
For those using `OIDCUnAuthAction pass`: be aware that using this in a secure manner requires at least version 2.1.5 https://github.com/pingidentity/mod_auth_openidc/releases/tag/v2.1.5
