### ISSUE TITLE
oidc_proto_parse_idtoken fails with Implicit Flow

### ISSUE THREAD

**Issue by asc1** [pingidentity/mod_auth_openidc#168]
When configured to use Implicit Flow, we get the following error (with 2.0.0rc1):

`[Fri Sep 02 10:22:00.455873 2016] [auth_openidc:error] [pid 11179] [client 10.150.36.172:39016] oidc_proto_parse_idtoken: oidc_util_create_symmetric_key failed: [\b\x17\xb6\x01a\x7f:0: ]:`

It appears this is caused by the lack of a client secret, that results in the `oidc_util_create_symmetric_key` returning NULL in [oidc_proto_parse_idtoken](https://github.com/pingidentity/mod_auth_openidc/blob/v2.0.x/src/proto.c#L722)

**Comment by zandbelt** [comment]
That looks like a bug indeed; I'm assuming this is not a show-stopper for you since you can use a dummy secret?

**Comment by asc1** [comment]
This was in our dev environment, so not a show stopper, still running 1.8 in production.

**Comment by zandbelt** [comment]
I updated the release page with new binaries, I would appreciate confirmation about the fix, and if possible further tests ;-)
