### ISSUE TITLE
Using "OIDCUnAuthAction pass" on a root location can not be overriden?

### ISSUE THREAD

**Issue by carldini** [pingidentity/mod_auth_openidc#170]
Hi there,

I'm trying to setup a site where most of the content is publically available and certain areas are protected.
If the user is logged in, I want to acknowledge that on the public pages. (have access to the claims headers)

From the documentation, it looks like OIDCUnAuthAction is what I should be working with
If I try to do something like:

    <Location "/">
        AuthType openid-connect
        Require valid-user
        OIDCUnAuthAction pass
    </Location>

    <Location "/secure/">
        OIDCUnAuthAction auth
    </Location>

When I access the secure path, I'm not redirected to the Identity Provider.

This is with release 1.8.10.1
Is this expected behaviour? (and is there a workaround to get the behaviour that I'm looking for?)

Many thanks,
Carl

[demo.zip](https://github.com/pingidentity/mod_auth_openidc/files/454813/demo.zip)

**Comment by zandbelt** [comment]
You've actually stumbled on an issue that has been around forever: I need to fix all of the server configuration merging routines to work properly... In the mean time it would be impossible to override the default (which is `auth`) in a sub-directory (not just for this directive but for most of them...); overriding it with something else would work; perhaps you can reorganize the directory layout for the time being? I'll fix things later today/tomorrow.

**Comment by carldini** [comment]
Thanks for the prompt update. It's good to know that I'm not going crazy
If you are planning a fix that quickly, I'm happy to wait.
... The alternative is rather 'involved'

**Comment by zandbelt** [comment]
I've fixed this in the v2.0.x branch: https://github.com/pingidentity/mod_auth_openidc/commit/30a28c53533151411d20476a546b48c65bbf1453

**Comment by carldini** [comment]
Thanks Hans,
I've compiled that up and your fix has resolved my issue. :)

**Comment by zandbelt** [comment]
Just to close the loop: this was quite a basic issue with all configuration directives - so not just `OIDCUnAuthAction` - when so-called configuration merging was applied. This led to the situation that it was impossible to reset a value in a "derived" configuration (e.g. a sub-directory inheriting from a parent-directory) to its default value (and only its default value).

I took the opportunity to also refactor the code around accessing the directory-related configuration directives, hence the commit is relatively large.

Note that this issue still persists for top-level directives in vhost configurations, so merging of top-level directives in derived vhosts needs to be fixed at some point in the not too distant future as well. This is less urgent as it is a far less common use case (c.q. resetting a top-level directive in an inherited vhost configuration back to its default).

@carldini thanks for reporting.

**Comment by zandbelt** [comment]
so this is fixed in 2.0.0 which is now released

**Comment by zandbelt** [comment]
For those using `OIDCUnAuthAction pass`: be aware that using this in a secure manner requires at least version 2.1.5 https://github.com/pingidentity/mod_auth_openidc/releases/tag/v2.1.5
