### ISSUE TITLE
No package 'jansson' found

### ISSUE THREAD

**Issue by baniani** [pingidentity/mod_auth_openidc#171]
I am running this command:
sudo ./configure --prefix=/etc/httpd --enable-auth_openidc=shared --with-apxs2=/etc/httpd/bin/apxs
configure: WARNING: unrecognized options: --enable-auth_openidc
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for CURL... yes
checking for OPENSSL... yes
checking for APR... yes
checking for JANSSON... no
configure: error: Package requirements (jansson) were not met:

**No package 'jansson' found**

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables JANSSON_CFLAGS
and JANSSON_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

But I did installed jansson-2.8:
./configure
make
sudo make install

What am I missing here? Where does jansson go after installation and how can I link it when I am trying to install mod_auth_openidc ?

**Comment by zandbelt** [comment]
Jansson installs by default in /usr/local which is not where your pkg-config looks for it (apparently). You can change the installation path of Jansson or add the path to the PKG_CONFIG_PATH environment variable.

It is probably even better to use the binary packages from the releases page: https://github.com/pingidentity/mod_auth_openidc/releases/

**Comment by dgtlmoon** [comment]
@zandbelt not true in debian..

Debian 10 releases in september this year (2019)..

```cat /var/lib/dpkg/info/libjansson4\:amd64.list 
/.
/usr
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/lib/x86_64-linux-gnu/libjansson.so.4.11.1
/usr/share
/usr/share/doc
/usr/share/doc/libjansson4
/usr/share/doc/libjansson4/README.rst
/usr/share/doc/libjansson4/changelog.Debian.gz
/usr/share/doc/libjansson4/changelog.gz
/usr/share/doc/libjansson4/copyright
/usr/share/doc/libjansson4/examples
/usr/share/doc/libjansson4/examples/json_process.c.gz
/usr/lib/x86_64-linux-gnu/libjansson.so.4
```

**Comment by jingydz** [comment]
Package jansson was not found in the pkg-config search path.
Perhaps you should add the directory containing `jansson.pc'
to the PKG_CONFIG_PATH environment variable
No package 'jansson' found
$ pip install jansson
ERROR: Could not find a version that satisfies the requirement jansson (from versions: none)
ERROR: No matching distribution found for jansson

**Comment by vmorris** [comment]
I'd love to use the pre-packaged binaries, but I'm not on x86 here.

In RHEL 8, `dnf install jansson` 

```
# ls /usr/lib64/*jansson*
/usr/lib64/libjansson.so.4  /usr/lib64/libjansson.so.4.14.0
```

`# export PKG_CONFIG_PATH=/usr/lib64`


```
checking for jansson... no
configure: error: Package requirements (jansson) were not met:

Package 'jansson', required by 'virtual:world', not found
```

**Comment by zandbelt** [comment]
you'll need to install the "development" package that includes header files for Jansson in addition to the binaries/libraries package
