### ISSUE TITLE
How to do Token Refresh transparently for the applications

### ISSUE THREAD

**Issue by pamiel** [pingidentity/mod_auth_openidc#173]
Hello,
I’m using the mod_auth_openidc to protect the access to a (set of) Web UI server(s), managing the authentication of end-users through the OIDC Authorization Code flow.
I understand that the validity period of Access Tokens should be short for security reasons and, or order to avoid re-presenting a login page to end users every 5 minutes (!), I understand the notion of token refresh.

However, what is not clear to me is the way you propose to manage this token refresh use case: 
- The usage of the url that requests the refresh of the Access Token (as described in https://github.com/pingidentity/mod_auth_openidc/wiki/Access-Tokens-and-Refresh-Tokens) is clear…
- … but it is said that “When the application wants to refresh the access_token, it may call the module on the following hook”, which means that this is the application responsibility to verify the potential expiration of the Access Token, and in case of such expiration, to call this hook, giving the “old” Access Token, and most probably giving the just navigated url as the <return_to> url of the “refresh” query parameter (so that the same resource it could be called again).

My concerns are the following:

- Such a piece of code that checks the token expiration and then call the hook shall be implemented in front-end of all resources and shall be deployed in every application that is deployed beyond the Apache, which might become quite complex when you have many applications, implemented in many technologies.

- How to implement the “call the hook” point: I don’t really see how we could call this hook else than using a HTTP redirect response to the original request. Any alternate proposal? If using a redirect, the consequence is that we are sending back the Access Token to the Web Browser, which is not what we want, as our goal is to hide it to the external world (that’s the reason why we used the OIDC Authorization Code flow and not the Implicit flow).

It make sense to me that, when protecting the access to a Web UI, the mod_auth_openidc itself would directly detect the Access Token expiration when a request is made from the Web Browser. The mod_auth_openidc would then be fully autonomous in asking the token refresh transparently for the applications and for the Web Browser.
Does this proposal make sense?
Is there any security reason to not implemented it like that ?

Thanks for your feedbacks!

**Comment by zandbelt** [comment]
"Calling the hook" is indeed done by triggering a redirect as documented. The access token that is exposed is the old one that has expired by then so there's no security issue with that. It is merely required as a means of protection against CSRF/DoS.

The module actually does not use the access token, except after the initial call to the userinfo endpoint. Perhaps you're conflating it with the id_token. Since it doesn't use it, it cannot detect expiry/invalidation, that's up to the application that does use the access token.

I would also find out why your OP returns an access token that is valid for only 5 minutes. That may not be suited for your use case.

**Comment by pamiel** [comment]
Thanks for the very quick answer!

No, I’m not conflicting with the Id token: to clarify our use case, after authentication, we want the Access Token to be sent up to the Web applications on each HTTP call to a resource, so that applications could apply access control based on the roles contained in the Access Token. We don’t want the Access Token to be sent back up to the Web Browser.
OIDC Authentication Code flow + the mod_auth_openidc are perfectly doing the job in this context:
- During authentication phase, Access Token is not returned to the Web Browser. It is cached in the session managed by the Relying Party (mod_auth_openidc)
- After authentication, when accessing the Web resources, calls go through mod_auth_openidc acting “as a reverse proxy”, and mod_auth_openidc adds on-the-fly the Access Token to every request proxied to the applications.

As mentioned in my first post, the first issue we see in relying on the applications to run a specific processing related to the Access Token expiration is that we are mandated to implement this business logic in all entry points of all applications (so as kinds of interceptors?) for all the technologies used in the various applications.
The second concern is related to the confidentiality of the information contained in the Access Token. If applications are using the HTTP Redirect to trigger the refresh, then the Access Token is made available to the Web Browser during this process. For sure, as you mentioned, the token is already expired and cannot be used again, but it has provided sensitive information on the end user (in particular its roles) into an un-trusted area (the Web Browser), which is not recommended by the OIDC Core specification (section 16.4).

Finally, we’ve set a short validity period on Access Tokens for anti-theft reasons, as mentioned for example here, but also as recommeded into the OIDC Core specification, section 16.9. 5 min is indeed the default value that is set when using Keycloak. We would like to keep such value short…

So, at the end, a transparent and “on-the-fly” handling of the Access Token refresh use case in the mod_auth_openidc would be really usefull as we would have a single and centralized point to manage this concern (implemented and deployed once, efficient for all), without sending sensitive information to an untrusted area (aka the Web Browsers).

Do you think this could make sense?

**Comment by zandbelt** [comment]
The reasoning make sense but as I mentioned: the module can (and does) refresh the access token but it cannot tell whether an access token has expired so it has to rely on something else (i.e. the application that uses it) to do so.

**Comment by markdbuck** [comment]
In case anyone runs across this discussion as I did there is now functionality relevant to refreshing the access token before expiry. See `OIDCRefreshAccessTokenBeforeExpiry` configuration item which is discussed in some detail at the following link:
https://github.com/zmartzone/mod_auth_openidc/wiki/Single-Page-Applications#refresh-access-token-ahead-of-expiry
