### ISSUE TITLE
Single logout with Keycloak

### ISSUE THREAD

**Issue by vatima2016** [pingidentity/mod_auth_openidc#175]
I'm evaluating SSO and single logout between Java and PHP web applications protected by Keycloak Java adapter and mod_auth_openidc 1.8.10.1 respectively.

If I log out from the PHP application, Java adapter discovers this and the next request redirects to login page. But if I log out from the Java application, the PHP one does not recognize that the SSO session is over and refreshing the page does not redirect to the login screen.

I followed instructions described here: https://github.com/pingidentity/mod_auth_openidc/wiki/Session-Management and read this issue https://github.com/pingidentity/mod_auth_openidc/issues/144

Keycloak provides undocumented session management endpoint (see http://lists.jboss.org/pipermail/keycloak-user/2016-May/006416.html for discussion).
So I tried to set OIDCProviderCheckSessionIFrame to https://auth-srv001.example.com/realms/my-DEV/protocol/openid-connect/login-status-iframe.html?client_id=my-mod-oidc&origin=https://srv001.example.com

Resulting source code for the iframe URL if called in a web browser looks good, but I don't know whether it is compliant with the standard OIDC session management:
``

`<script>`
` function getCookie(cname)`
`    {`
        `var name = cname + "=";`
        `var ca = document.cookie.split(";");`
        `for(var i=0; i<ca.length; i++)`
        `{`
            `var c = ca[i].trim();`
            `if (c.indexOf(name)==0) return c.substring(name.length,c.length);`
        `}`
        `return null;`
    `}`
    `function receiveMessage(event)`
    `{`
        `if (event.origin !== "https://srv001.example.com") {`
         `   console.log(event.origin + " does not match built origin");`
          `  return;`
        `}`
        `var data = JSON.parse(event.data);`
        `data.loggedIn = false;`
        `var cookie = getCookie("KEYCLOAK_SESSION");`
        `if (cookie) {`
            `data.loggedIn = true;`
            `data.session = cookie;`
        `}`
        `event.source.postMessage(JSON.stringify(data), event.origin);`
    `}`
    `window.addEventListener("message", receiveMessage, false);`
`</script>`

But both iframes on my test page still return 404. 

Does anybody succeeded to configure single logout with Keycloak as OP?

**Comment by zandbelt** [comment]
From the thread on the e-mail list it appears that Keycloak has an iframe-based mechanism to support logout from Javascript applications but it is not an implementation of OpenID Connect's Session Management. Looking at the spec: http://openid.net/specs/openid-connect-session-1_0.html#OPiframe it says that the OP should return "changed" or "unchanged" and the code you posted shows that Keycloak returns a stringified JSON session data object. That is not something that mod_auth_openidc's iframe can deal with.

**Comment by vatima2016** [comment]
Thank you for the prompt response! 
I'll discuss this issue with the Keycloak team.

**Comment by zandbelt** [comment]
If you could report your findings back here that would be great.

**Comment by vatima2016** [comment]
The issue has been acknowledged by the Keycloak team:
https://issues.jboss.org/browse/KEYCLOAK-3625

**Comment by vatima2016** [comment]
The issue has been fixed by the Keycloak team in the version 2.3.0.Final:
https://issues.jboss.org/browse/KEYCLOAK-3625
