### ISSUE TITLE
Directory listing 

### ISSUE THREAD

**Issue by radaway** [pingidentity/mod_auth_openidc#176]
Unable to listing directories on server

<VirtualHost releases.mydomain.com.br:80>

	ServerName releases.mydomain.com.br
	ServerAdmin infra@mydomain.com.br
        DocumentRoot /var/www/releases

	#autenticação do google
	OIDCProviderMetadataUrl https://accounts.google.com/.well-known/openid-configuration
	OIDCSSLValidateServer Off
	OIDCClientID 9227241xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
	OIDCClientSecret Q8xxxxxxxxxxxxxxxxxxxxxn
	OIDCCryptoPassphrase releases
	OIDCAuthRequestParams hd=mydomain.com.br
	OIDCRemoteUserClaim email
	OIDCScope "openid email"
	OIDCSessionInactivityTimeout 7200
	OIDCRedirectURI http://releases.mydomain.com.br/oidcoauth2
	OIDCCookieDomain releases.mydomain.com.br

	#parametros e-cidade
        TimeOut 12000
        AddDefaultCharset ISO-8859-1
        LimitRequestLine 16382
        LimitRequestFieldSize 16382
	SetEnv no-gzip 1

	#handler php-fpm
	<FilesMatch ".+\.ph(p[3457]?|t|tml)$">
        	SetHandler php5.3-fcgi
	</FilesMatch>

	#diretorio de releases
	<Directory /var/www/releases>
    		Options Indexes FollowSymLinks MultiViews
    		AllowOverride All
    		Order Deny,Allow
                Deny from all
                AuthType openid-connect 
                Require claim hd:mydomain.com.br
                Satisfy Any
                Allow from 172.22.0.0/16		
	</Directory>

	#diretorio para acesso sem autenticação
	<Directory /var/www/releases/externo/>
                Options Indexes FollowSymLinks Multiviews
                AllowOverride All
                Order deny,allow
		AuthType None
		Require all granted
                Allow from all 
        </Directory>

	ErrorLog ${APACHE_LOG_DIR}/error-releases.mydomain.com.br.log
	CustomLog ${APACHE_LOG_DIR}/access-releases.mydomain.com.br.log combined
</VirtualHost>

with Require valid-user directories is listed but no validate my domain

**Comment by zandbelt** [comment]
Directory listing should work and is fine in my tests, regardless of the `Require` primitives configured.

What version of mod_auth_openidc do you use and which platform & Apache version are you on?

**Comment by radaway** [comment]
strange because only changing the line "Require claim hd: mydomain.com.br" by "Require valid-user". It works normally, but does not validate my domain and in turn allows login type @gmail accounts

configuration of my server

root@evilseed:/var/www/releases# dpkg --list libapache2-mod-auth-openidc
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                            Version                      Architecture                 Description
+++-===============================================-============================-============================-===================================================================================================
ii  libapache2-mod-auth-openidc                     2.0.0-1ubuntu1~trusty+1      amd64                        OpenID Connect authentication module for Apache
root@evilseed:/var/www/releases# apache2 -v
Server version: Apache/2.4.7 (Ubuntu)
Server built:   Jul 15 2016 15:34:04
root@evilseed:/var/www/releases# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty

**Comment by zandbelt** [comment]
that's because of the `Satisfy Any`

**Comment by mserramanxa** [comment]
Hi, and sorry for reopen the conversation after more than two years, but I have the same problem as @radaway 

When we save `.htaccess` with `Require valid-user`, directory listing works as expected, but if we try with...
```
Require claim hd:mydomain.tld 
# or
Require claim email~^[a-zA-Z0-9_.+-]+@(?:(?:[a-zA-Z0-9-]+\.)?[a-zA-Z]+\.)?(mydomain)\.tld$
```
The directory listing not works and we see this errors on apache log...
```
[Mon Feb 04 11:50:52.896384 2019] [authz_core:error] [pid 28812] [client x.x.x.x:52044] AH01631: user nnnnnnnnnnnnnnnnnnnn@accounts.google.com: authorization failure for "/path/to/url/folder/subfolder1/index.html":
[Mon Feb 04 11:50:52.896426 2019] [authz_core:error] [pid 28812] [client x.x.x.x:52044] AH01631: user nnnnnnnnnnnnnnnnnnnn@accounts.google.com: authorization failure for "/path/to/url/folder/subfolder1/index.cgi":
[Mon Feb 04 11:50:52.896446 2019] [authz_core:error] [pid 28812] [client x.x.x.x:52044] AH01631: user nnnnnnnnnnnnnnnnnnnn@accounts.google.com: authorization failure for "/path/to/url/folder/subfolder1/index.pl":
[Mon Feb 04 11:50:52.896466 2019] [authz_core:error] [pid 28812] [client x.x.x.x:52044] AH01631: user nnnnnnnnnnnnnnnnnnnn@accounts.google.com: authorization failure for "/path/to/url/folder/subfolder1/index.php":
[Mon Feb 04 11:50:52.896486 2019] [authz_core:error] [pid 28812] [client x.x.x.x:52044] AH01631: user nnnnnnnnnnnnnnnnnnnn@accounts.google.com: authorization failure for "/path/to/url/folder/subfolder1/index.xhtml":
[Mon Feb 04 11:50:52.896505 2019] [authz_core:error] [pid 28812] [client x.x.x.x:52044] AH01631: user nnnnnnnnnnnnnnnnnnnn@accounts.google.com: authorization failure for "/path/to/url/folder/subfolder1/index.htm":
[Mon Feb 04 11:50:52.896527 2019] [authz_core:error] [pid 28812] [client x.x.x.x:52044] AH01631: user nnnnnnnnnnnnnnnnnnnn@accounts.google.com: authorization failure for "/path/to/url/folder/subfolder1/index.shtml":
[Mon Feb 04 11:50:52.896620 2019] [authz_core:error] [pid 28812] [client x.x.x.x:52044] AH01631: user nnnnnnnnnnnnnnnnnnnn@accounts.google.com: authorization failure for "/path/to/url/folder/subfolder2/index.html":
[Mon Feb 04 11:50:52.896650 2019] [authz_core:error] [pid 28812] [client x.x.x.x:52044] AH01631: user nnnnnnnnnnnnnnnnnnnn@accounts.google.com: authorization failure for "/path/to/url/folder/subfolder2/index.cgi":
[Mon Feb 04 11:50:52.896668 2019] [authz_core:error] [pid 28812] [client x.x.x.x:52044] AH01631: user nnnnnnnnnnnnnnnnnnnn@accounts.google.com: authorization failure for "/path/to/url/folder/subfolder2/index.pl":
[Mon Feb 04 11:50:52.896716 2019] [authz_core:error] [pid 28812] [client x.x.x.x:52044] AH01631: user nnnnnnnnnnnnnnnnnnnn@accounts.google.com: authorization failure for "/path/to/url/folder/subfolder2/index.php":
[Mon Feb 04 11:50:52.896734 2019] [authz_core:error] [pid 28812] [client x.x.x.x:52044] AH01631: user nnnnnnnnnnnnnnnnnnnn@accounts.google.com: authorization failure for "/path/to/url/folder/subfolder2/index.xhtml":
[Mon Feb 04 11:50:52.896797 2019] [authz_core:error] [pid 28812] [client x.x.x.x:52044] AH01631: user nnnnnnnnnnnnnnnnnnnn@accounts.google.com: authorization failure for "/path/to/url/folder/subfolder2/index.htm":
[Mon Feb 04 11:50:52.896828 2019] [authz_core:error] [pid 28812] [client x.x.x.x:52044] AH01631: user nnnnnnnnnnnnnnnnnnnn@accounts.google.com: authorization failure for "/path/to/url/folder/subfolder2/index.shtml":
```
This logs are when I try to list the directory **/path/to/url/folder/**

In this directory, there are two others folders:  **subfolder1** and **subfolder2**. Each folder contains some PDF files.

Seems apache ignore the directory listing and tries to find an index file.

The folders and subfolders have 755 permissions.

I'm using Apache/2.4.18 on Ubuntu 16.04.5 64bits.

mod_auth_openidc module version is 1.8.5-1

Any ideas?

**Comment by mserramanxa** [comment]
Hi, and sorry for reopen the conversation after more than two years, but I have the same problem as @radaway 

When we save `.htaccess` with `Require valid-user`, directory listing works as expected, but if we try with...
```
Require claim hd:mydomain.tld 
# or
Require claim email~^[a-zA-Z0-9_.+-]+@(?:(?:[a-zA-Z0-9-]+\.)?[a-zA-Z]+\.)?(mydomain)\.tld$
```
The directory listing not works and we see this errors on apache log...
```
[Mon Feb 04 11:50:52.896384 2019] [authz_core:error] [pid 28812] [client x.x.x.x:52044] AH01631: user nnnnnnnnnnnnnnnnnnnn@accounts.google.com: authorization failure for "/path/to/url/folder/subfolder1/index.html":
[Mon Feb 04 11:50:52.896426 2019] [authz_core:error] [pid 28812] [client x.x.x.x:52044] AH01631: user nnnnnnnnnnnnnnnnnnnn@accounts.google.com: authorization failure for "/path/to/url/folder/subfolder1/index.cgi":
[Mon Feb 04 11:50:52.896446 2019] [authz_core:error] [pid 28812] [client x.x.x.x:52044] AH01631: user nnnnnnnnnnnnnnnnnnnn@accounts.google.com: authorization failure for "/path/to/url/folder/subfolder1/index.pl":
[Mon Feb 04 11:50:52.896466 2019] [authz_core:error] [pid 28812] [client x.x.x.x:52044] AH01631: user nnnnnnnnnnnnnnnnnnnn@accounts.google.com: authorization failure for "/path/to/url/folder/subfolder1/index.php":
[Mon Feb 04 11:50:52.896486 2019] [authz_core:error] [pid 28812] [client x.x.x.x:52044] AH01631: user nnnnnnnnnnnnnnnnnnnn@accounts.google.com: authorization failure for "/path/to/url/folder/subfolder1/index.xhtml":
[Mon Feb 04 11:50:52.896505 2019] [authz_core:error] [pid 28812] [client x.x.x.x:52044] AH01631: user nnnnnnnnnnnnnnnnnnnn@accounts.google.com: authorization failure for "/path/to/url/folder/subfolder1/index.htm":
[Mon Feb 04 11:50:52.896527 2019] [authz_core:error] [pid 28812] [client x.x.x.x:52044] AH01631: user nnnnnnnnnnnnnnnnnnnn@accounts.google.com: authorization failure for "/path/to/url/folder/subfolder1/index.shtml":
[Mon Feb 04 11:50:52.896620 2019] [authz_core:error] [pid 28812] [client x.x.x.x:52044] AH01631: user nnnnnnnnnnnnnnnnnnnn@accounts.google.com: authorization failure for "/path/to/url/folder/subfolder2/index.html":
[Mon Feb 04 11:50:52.896650 2019] [authz_core:error] [pid 28812] [client x.x.x.x:52044] AH01631: user nnnnnnnnnnnnnnnnnnnn@accounts.google.com: authorization failure for "/path/to/url/folder/subfolder2/index.cgi":
[Mon Feb 04 11:50:52.896668 2019] [authz_core:error] [pid 28812] [client x.x.x.x:52044] AH01631: user nnnnnnnnnnnnnnnnnnnn@accounts.google.com: authorization failure for "/path/to/url/folder/subfolder2/index.pl":
[Mon Feb 04 11:50:52.896716 2019] [authz_core:error] [pid 28812] [client x.x.x.x:52044] AH01631: user nnnnnnnnnnnnnnnnnnnn@accounts.google.com: authorization failure for "/path/to/url/folder/subfolder2/index.php":
[Mon Feb 04 11:50:52.896734 2019] [authz_core:error] [pid 28812] [client x.x.x.x:52044] AH01631: user nnnnnnnnnnnnnnnnnnnn@accounts.google.com: authorization failure for "/path/to/url/folder/subfolder2/index.xhtml":
[Mon Feb 04 11:50:52.896797 2019] [authz_core:error] [pid 28812] [client x.x.x.x:52044] AH01631: user nnnnnnnnnnnnnnnnnnnn@accounts.google.com: authorization failure for "/path/to/url/folder/subfolder2/index.htm":
[Mon Feb 04 11:50:52.896828 2019] [authz_core:error] [pid 28812] [client x.x.x.x:52044] AH01631: user nnnnnnnnnnnnnnnnnnnn@accounts.google.com: authorization failure for "/path/to/url/folder/subfolder2/index.shtml":
```
This logs are when I try to list the directory **/path/to/url/folder/**

In the directory **/path/to/url/folder/**, there are two others folders:  subfolder1 and subfolder2. Each folder contains some PDF files.

Seems apache ignore the directory listing and tries to find an index file.

The folders and subfolders have 755 permissions.

I'm using Apache/2.4.18 on Ubuntu 16.04.5 64bits.

mod_auth_openidc module version is 1.8.5-1

Any ideas?

**Comment by mserramanxa** [comment]
Two more comments (if can help)

If I replace 

`Require claim hd:mydomain.tld`

for ...

`Require claim email:myloggedemailaddress@mygsuitedomain.tld`

still not works.

But if I change for...

`require user my_user_id@accounts.google.com`

works as expected
