### ISSUE TITLE
oidc_cache_file_set tries to write to files with slashes in their name and fails

### ISSUE THREAD

**Issue by djahandarie** [pingidentity/mod_auth_openidc#179]
I've been getting this error on every request for as long as I've been using oidc, although things seem to work fine despite it:

`[Wed Oct 12 18:22:04 2016] [error] [client OMITTED] oidc_cache_file_set: cache file "/tmp/mod-auth-connect-provider-https://accounts.google.com/.well-known/openid-configuration" could not be opened (No such file or directory), referer: OMITTED`

Since oidc is successfully writing various other files to `/tmp` under the `apache` user, I think the problem might be here that it has slashes in the file name it is using? (Which is just `mod-auth-connect-provider-`+OIDCProviderMetadataURL as far as I can tell.)

Since this is the standard OIDCProviderMetadataURL found in various docs, I'm not sure why there hasn't been any reports on this before, and I wonder if I'm incorrect analyzing the problem, but figured I'd file a bug report.

**Comment by star3am** [comment]
@djahandarie 

> Since this is the standard OIDCProviderMetadataURL found in various docs, I'm not sure why there 
> hasn't been any reports on this before, and I wonder if I'm incorrect analyzing the problem, but figured 
> I'd file a bug report.

Your bug report helped me a lot!! 

Thank You!

**Comment by zandbelt** [comment]
As it turns out the same issue also holds for caching JWKs served on `jwks_uri`; the definitive fix for that is in 2.3.0rc3: c41226419503aa475d51982bed8ffacf5d7e9ba1...493c778ff2d69e8b37c742a59f95e736ecc90f41
