### ISSUE TITLE
cjose / jansson dependency issue

### ISSUE THREAD

**Issue by ervin-lemark** [pingidentity/mod_auth_openidc#182]
Hello, friends.

Can you help me out with the following dependency issue:

```
error: Failed dependencies:
        pkgconfig(jansson) >= 2.3 is needed by cjose-0.4.1-1.el7.centos.x86_64

```

Jansson is installed:

```
sudo rpm -i jansson-2.4-6.el7.x86_64.rpm
        package jansson-2.4-6.el7.x86_64 is already installed

```

Another failed dependency:

```
        pkgconfig(libcrypto) >= 1.0.1 is needed by cjose-0.4.1-1.el7.centos.x86_64
```

        

OS is CentOS Linux release 7.2.1511 (Core)

Thanks a lot! I really appreciate your help.

Keep up the good work,
Ervin

**Comment by zandbelt** [comment]
Using Docker I can just do this to install cjose on CentOS 7.2.1511:
```
FROM centos:centos7.2.1511

RUN curl -s -L -o ~/cjose-0.4.1-1.el7.centos.x86_64.rpm https://github.com/pingidentity/mod_auth_openidc/releases/download/v2.0.0/cjose-0.4.1-1.el7.centos.x86_64.rpm
RUN yum localinstall -y ~/cjose-0.4.1-1.el7.centos.x86_64.rpm
```

Can you confirm that this doesn't work on your machine?

**Comment by ervin-lemark** [comment]
Dear Hans, thank you very much. It worked:

```
Installed:
  cjose.x86_64 0:0.4.1-1.el7.centos

Dependency Installed:
  jansson-devel.x86_64 0:2.4-6.el7              keyutils-libs-devel.x86_64 0:1.5.8-3.el7
  krb5-devel.x86_64 0:1.13.2-12.el7_2           libselinux-devel.x86_64 0:2.2.2-6.el7
  libsepol-devel.x86_64 0:2.1.9-3.el7           openssl-devel.x86_64 1:1.0.1e-51.el7_2.7

Dependency Updated:
  openssl.x86_64 1:1.0.1e-51.el7_2.7            openssl-libs.x86_64 1:1.0.1e-51.el7_2.7

```

Great job, congrats!

Sincerely,
Ervin

**Comment by ricardinhorio** [comment]
In my case, it gets me the error below.
How to fix that?


Plugins carregados: langpacks, product-id, search-disabled-repos, subscription-manager
Examinando cjose-0.5.1-1.el7.centos.x86_64.rpm: cjose-0.5.1-1.el7.centos.x86_64
Marcando cjose-0.5.1-1.el7.centos.x86_64.rpm para ser instalado
Resolvendo dependências
--> Executando verificação da transação
---> O pacote cjose.x86_64 0:0.5.1-1.el7.centos será instalado
--> Processando dependência: pkgconfig(jansson) >= 2.3 para o pacote: cjose-0.5.1-1.el7.centos.x86_64
--> Resolução de dependências finalizada
Error: Pacote: cjose-0.5.1-1.el7.centos.x86_64 (/cjose-0.5.1-1.el7.centos.x86_64)
           Requer: pkgconfig(jansson) >= 2.3
**********************************************************************
yum can be configured to try to resolve such errors by temporarily enabling
disabled repos and searching for missing dependencies.
To enable this functionality please set 'notify_only=0' in /etc/yum/pluginconf.d/search-disabled-repos.conf
**********************************************************************

Error: Pacote: cjose-0.5.1-1.el7.centos.x86_64 (/cjose-0.5.1-1.el7.centos.x86_64)
           Requer: pkgconfig(jansson) >= 2.3
 Você pode tentar usar o parâmetro --skip-broken para contornar o problema
 Você pode tentar executar: rpm -Va --nofiles --nodigest

**Comment by zandbelt** [comment]
what is the command that you're using to install the package, leading to the error?

**Comment by ricardinhorio** [comment]
The commands are:

[root@teste ricardosm]# rpm -i mod_auth_openidc-2.3.2-1.el7.centos.x86_64.rpm
erro: Dependências não satisfeitas:
        cjose é requerido por mod_auth_openidc-2.3.2-1.el7.centos.x86_64
        hiredis é requerido por mod_auth_openidc-2.3.2-1.el7.centos.x86_64
        libcjose.so.0()(64bit) é requerido por mod_auth_openidc-2.3.2-1.el7.centos.x86_64
        libhiredis.so.0.12()(64bit) é requerido por mod_auth_openidc-2.3.2-1.el7.centos.x86_64

----

[root@teste ricardosm]# yum install cjose*
Plugins carregados: langpacks, product-id, search-disabled-repos, subscription-manager
Examinando cjose-0.5.1-1.el7.centos.x86_64.rpm: cjose-0.5.1-1.el7.centos.x86_64
Marcando cjose-0.5.1-1.el7.centos.x86_64.rpm para ser instalado
Resolvendo dependências
--> Executando verificação da transação
---> O pacote cjose.x86_64 0:0.5.1-1.el7.centos será instalado
--> Processando dependência: pkgconfig(jansson) >= 2.3 para o pacote: cjose-0.5.1-1.el7.centos.x86_64
--> Resolução de dependências finalizada
Error: Pacote: cjose-0.5.1-1.el7.centos.x86_64 (/cjose-0.5.1-1.el7.centos.x86_64)
           Requer: pkgconfig(jansson) >= 2.3
**********************************************************************
yum can be configured to try to resolve such errors by temporarily enabling
disabled repos and searching for missing dependencies.
To enable this functionality please set 'notify_only=0' in /etc/yum/pluginconf.d/search-disabled-repos.conf
**********************************************************************

Error: Pacote: cjose-0.5.1-1.el7.centos.x86_64 (/cjose-0.5.1-1.el7.centos.x86_64)
           Requer: pkgconfig(jansson) >= 2.3
 Você pode tentar usar o parâmetro --skip-broken para contornar o problema
 Você pode tentar executar: rpm -Va --nofiles --nodigest

**Comment by ricardinhorio** [comment]
Ah, I am on RED HAT EL 7.2.

**Comment by zandbelt** [comment]
you need to use `yum localinstall` to avoid the dependency issue
