### ISSUE TITLE
libpcre dependency

### ISSUE THREAD

**Issue by ervin-lemark** [pingidentity/mod_auth_openidc#183]
Hello, Hans.

I've managed to solve hiredis dependency and now I am stuck with:

```
Error: Package: mod_auth_openidc-2.0.0-1.el6.x86_64 (/mod_auth_openidc-2.0.0-1.el6.x86_64)
           Requires: libpcre.so.0()(64bit)

```

I do have:

```
$ rpm -q pcre
pcre-8.32-15.el7_2.1.x86_64

```

Please, help me out with this one too. I hope this is the last obstacle before the finish line :)

**Comment by zandbelt** [comment]
`mod_auth_openidc` requires `hiredis` which comes from the EPEL repository, but `libpcre` should come along automatically from the stock repositories.

` pcre                x86_64 8.32-15.el7_2.1     updates                   420 k
`

This Docker sequence works for me:

```
FROM centos:centos7.2.1511

RUN curl -s -L -o ~/cjose-0.4.1-1.el7.centos.x86_64.rpm https://github.com/pingidentity/mod_auth_openidc/releases/download/v2.0.0/cjose-0.4.1-1.el7.centos.x86_64.rpm
RUN yum install -y jansson openssl
RUN yum localinstall -y ~/cjose-0.4.1-1.el7.centos.x86_64.rpm

RUN rpm --import http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
RUN rpm -ihv http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm

RUN curl -s -L -o ~/mod_auth_openidc-2.0.0-1.el7.centos.x86_64.rpm https://github.com/pingidentity/mod_auth_openidc/releases/download/v2.0.0/mod_auth_openidc-2.0.0-1.el7.centos.x86_64.rpm
RUN yum localinstall -y ~/mod_auth_openidc-2.0.0-1.el7.centos.x86_64.rpm

```

**Comment by ervin-lemark** [comment]
Thank you very much. Installed!

Look like the trick is in **yum localinstall.** 

Cool. You are great!

Thank you very much and greetings from rainy Ljubljana,
Ervin
