### ISSUE TITLE
Error in handling response type

### ISSUE THREAD

**Issue by dimitrovs** [pingidentity/mod_auth_openidc#186]
Auth0 setup with default config.

```
Error:

The OpenID Connect Provider returned an error: Error in handling response type.
```

Apache logs:

[Sat Oct 22 23:24:10.701675 2016] [ssl:debug] [pid 16:tid 139806454540032] ssl_engine_kernel.c(2096): [client 172.17.0.1:54567] AH02043: SSL virtual host for servername justbuild.ml found
[Sat Oct 22 23:24:10.738720 2016] [ssl:debug] [pid 16:tid 139806454540032] ssl_engine_kernel.c(2023): [client 172.17.0.1:54567] AH02041: Protocol: TLSv1.2, Cipher: ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
[Sat Oct 22 23:24:10.762149 2016] [ssl:debug] [pid 16:tid 139806454540032] ssl_engine_kernel.c(354): [client 172.17.0.1:54567] AH02034: Initial (No.1) HTTPS request received for child 0 (server justbuild.ml:443)
[Sat Oct 22 23:24:10.762359 2016] [authz_core:debug] [pid 16:tid 139806454540032] mod_authz_core.c(809): [client 172.17.0.1:54567] AH01626: authorization result of Require valid-user : denied (no authenticated user yet)
[Sat Oct 22 23:24:10.762400 2016] [authz_core:debug] [pid 16:tid 139806454540032] mod_authz_core.c(809): [client 172.17.0.1:54567] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[Sat Oct 22 23:24:10.762440 2016] [auth_openidc:debug] [pid 16:tid 139806454540032] src/mod_auth_openidc.c(2312): [client 172.17.0.1:54567] oidc_check_user_id: incoming request: "/?(null)", ap_is_initial_req(r)=1
[Sat Oct 22 23:24:10.762617 2016] [auth_openidc:debug] [pid 16:tid 139806454540032] src/util.c(752): [client 172.17.0.1:54567] oidc_util_get_cookie: returning "mod_auth_openidc_session" = <null>
[Sat Oct 22 23:24:10.762649 2016] [auth_openidc:debug] [pid 16:tid 139806454540032] src/session.c(83): [client 172.17.0.1:54567] oidc_session_load: <null>
[Sat Oct 22 23:24:10.762672 2016] [auth_openidc:debug] [pid 16:tid 139806454540032] src/util.c(791): [client 172.17.0.1:54567] oidc_util_request_matches_url: comparing "/"=="/redirect_uri"
[Sat Oct 22 23:24:10.762698 2016] [auth_openidc:debug] [pid 16:tid 139806454540032] src/util.c(361): [client 172.17.0.1:54567] oidc_get_current_url: current URL 'https://justbuild.ml/'
[Sat Oct 22 23:24:10.762716 2016] [auth_openidc:debug] [pid 16:tid 139806454540032] src/mod_auth_openidc.c(1433): [client 172.17.0.1:54567] oidc_authenticate_user: enter
[Sat Oct 22 23:24:10.762822 2016] [auth_openidc:debug] [pid 16:tid 139806454540032] src/mod_auth_openidc.c(143): [client 172.17.0.1:54567] oidc_get_browser_state_hash: enter
[Sat Oct 22 23:24:10.762988 2016] [auth_openidc:debug] [pid 16:tid 139806454540032] src/util.c(712): [client 172.17.0.1:54567] oidc_util_set_cookie: adding outgoing header: Set-Cookie: mod_auth_openidc_state_B7rmfiMB9ztUT0oozQTD6Y022cg=Lzina8Z4McuuUxzFeedf4K3cq6Y4UJSuHdCLFO-Wxp_U7hQU6fmEw0sdYv2hTxeHLfSU8YBUH1ILYTegW2QIM7ZmantdEjunvSgiNx36LjkVfAx6VwfwGKlkSm3t_EqmRgEkH4VNd_BEw4biCkDJ84QvazLxrRWPDg9NKA16W8OxF2lq_m2M8qSXmI_3bfJhf7xhu387Xl-xmbYVWQQkFfDglEtdziHxqYt5ALjX5U5JpXpWp_oydohbGZu5uvBSNsUSkZxYiRtq-pKqVjkJY3s20X2RD7YyAeFJHJTQeyw;Path=/; expires=Sat, 22 Oct 2016 23:29:10 GMT;Secure;HttpOnly
[Sat Oct 22 23:24:10.763098 2016] [auth_openidc:debug] [pid 16:tid 139806454540032] src/proto.c(111): [client 172.17.0.1:54567] oidc_proto_authorization_request: enter, issuer=https://justbuild.auth0.com, redirect_uri=https://justbuild.ml/redirect_uri, state=B7rmfiMB9ztUT0oozQTD6Y022cg, proto_state={"timestamp": 1477178650, "nonce": "aeMtN8dwkm1k0VoPNQEWHq7R9mjgyIfRznxsbeXlbyA", "issuer": "https://justbuild.auth0.com", "original_url": "https://justbuild.ml/", "original_method": "get", "response_type": "code"}
[Sat Oct 22 23:24:10.763345 2016] [auth_openidc:debug] [pid 16:tid 139806454540032] src/proto.c(197): [client 172.17.0.1:54567] oidc_proto_authorization_request: adding outgoing header: Location: https://justbuild.auth0.com/authorize?response_type=code&scope=openid%20name%20email&client_id=1mQDwTF9eWGm9iYkWG2omjtBnJVRxrH5&state=B7rmfiMB9ztUT0oozQTD6Y022cg&redirect_uri=https%3A%2F%2Fjustbuild.ml%2Fredirect_uri&nonce=aeMtN8dwkm1k0VoPNQEWHq7R9mjgyIfRznxsbeXlbyA
[Sat Oct 22 23:24:15.710521 2016] [ssl:debug] [pid 16:tid 139806176618240] ssl_engine_io.c(1016): [remote 172.17.0.1:54567] AH02001: Connection closed to child 0 with standard shutdown (server justbuild.ml:443)
[Sat Oct 22 23:24:19.088737 2016] [ssl:info] [pid 16:tid 139806446147328] [client 172.17.0.1:54568] AH01964: Connection to child 1 established (server justbuild.ml:443)
[Sat Oct 22 23:24:19.089335 2016] [ssl:debug] [pid 16:tid 139806446147328] ssl_engine_kernel.c(2096): [client 172.17.0.1:54568] AH02043: SSL virtual host for servername justbuild.ml found
[Sat Oct 22 23:24:19.123850 2016] [ssl:debug] [pid 16:tid 139806446147328] ssl_engine_kernel.c(2023): [client 172.17.0.1:54568] AH02041: Protocol: TLSv1.2, Cipher: ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
[Sat Oct 22 23:24:19.149019 2016] [ssl:debug] [pid 16:tid 139806446147328] ssl_engine_kernel.c(354): [client 172.17.0.1:54568] AH02034: Initial (No.1) HTTPS request received for child 1 (server justbuild.ml:443), referer: https://justbuild.auth0.com/login?client=1mQDwTF9eWGm9iYkWG2omjtBnJVRxrH5&protocol=oauth2&state=B7rmfiMB9ztUT0oozQTD6Y022cg&redirect_uri=https%3A%2F%2Fjustbuild.ml%2Fredirect_uri&response_type=code&scope=openid%20name%20email&nonce=aeMtN8dwkm1k0VoPNQEWHq7R9mjgyIfRznxsbeXlbyA
[Sat Oct 22 23:24:19.149268 2016] [authz_core:debug] [pid 16:tid 139806446147328] mod_authz_core.c(809): [client 172.17.0.1:54568] AH01626: authorization result of Require valid-user : denied (no authenticated user yet), referer: https://justbuild.auth0.com/login?client=1mQDwTF9eWGm9iYkWG2omjtBnJVRxrH5&protocol=oauth2&state=B7rmfiMB9ztUT0oozQTD6Y022cg&redirect_uri=https%3A%2F%2Fjustbuild.ml%2Fredirect_uri&response_type=code&scope=openid%20name%20email&nonce=aeMtN8dwkm1k0VoPNQEWHq7R9mjgyIfRznxsbeXlbyA
[Sat Oct 22 23:24:19.149299 2016] [authz_core:debug] [pid 16:tid 139806446147328] mod_authz_core.c(809): [client 172.17.0.1:54568] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet), referer: https://justbuild.auth0.com/login?client=1mQDwTF9eWGm9iYkWG2omjtBnJVRxrH5&protocol=oauth2&state=B7rmfiMB9ztUT0oozQTD6Y022cg&redirect_uri=https%3A%2F%2Fjustbuild.ml%2Fredirect_uri&response_type=code&scope=openid%20name%20email&nonce=aeMtN8dwkm1k0VoPNQEWHq7R9mjgyIfRznxsbeXlbyA
[Sat Oct 22 23:24:19.149322 2016] [auth_openidc:debug] [pid 16:tid 139806446147328] src/mod_auth_openidc.c(2312): [client 172.17.0.1:54568] oidc_check_user_id: incoming request: "/redirect_uri?code=V3HQEf5YjuA2XpV8&state=B7rmfiMB9ztUT0oozQTD6Y022cg", ap_is_initial_req(r)=1, referer: https://justbuild.auth0.com/login?client=1mQDwTF9eWGm9iYkWG2omjtBnJVRxrH5&protocol=oauth2&state=B7rmfiMB9ztUT0oozQTD6Y022cg&redirect_uri=https%3A%2F%2Fjustbuild.ml%2Fredirect_uri&response_type=code&scope=openid%20name%20email&nonce=aeMtN8dwkm1k0VoPNQEWHq7R9mjgyIfRznxsbeXlbyA
[Sat Oct 22 23:24:19.149442 2016] [auth_openidc:debug] [pid 16:tid 139806446147328] src/util.c(752): [client 172.17.0.1:54568] oidc_util_get_cookie: returning "mod_auth_openidc_session" = <null>, referer: https://justbuild.auth0.com/login?client=1mQDwTF9eWGm9iYkWG2omjtBnJVRxrH5&protocol=oauth2&state=B7rmfiMB9ztUT0oozQTD6Y022cg&redirect_uri=https%3A%2F%2Fjustbuild.ml%2Fredirect_uri&response_type=code&scope=openid%20name%20email&nonce=aeMtN8dwkm1k0VoPNQEWHq7R9mjgyIfRznxsbeXlbyA[Sat Oct 22 23:24:19.149462 2016] [auth_openidc:debug] [pid 16:tid 139806446147328] src/session.c(83): [client 172.17.0.1:54568] oidc_session_load: <null>, referer: https://justbuild.auth0.com/login?client=1mQDwTF9eWGm9iYkWG2omjtBnJVRxrH5&protocol=oauth2&state=B7rmfiMB9ztUT0oozQTD6Y022cg&redirect_uri=https%3A%2F%2Fjustbuild.ml%2Fredirect_uri&response_type=code&scope=openid%20name%20email&nonce=aeMtN8dwkm1k0VoPNQEWHq7R9mjgyIfRznxsbeXlbyA
[Sat Oct 22 23:24:19.149480 2016] [auth_openidc:debug] [pid 16:tid 139806446147328] src/util.c(791): [client 172.17.0.1:54568] oidc_util_request_matches_url: comparing "/redirect_uri"=="/redirect_uri", referer: https://justbuild.auth0.com/login?client=1mQDwTF9eWGm9iYkWG2omjtBnJVRxrH5&protocol=oauth2&state=B7rmfiMB9ztUT0oozQTD6Y022cg&redirect_uri=https%3A%2F%2Fjustbuild.ml%2Fredirect_uri&response_type=code&scope=openid%20name%20email&nonce=aeMtN8dwkm1k0VoPNQEWHq7R9mjgyIfRznxsbeXlbyA
[Sat Oct 22 23:24:19.149508 2016] [auth_openidc:debug] [pid 16:tid 139806446147328] src/mod_auth_openidc.c(1313): [client 172.17.0.1:54568] oidc_handle_redirect_authorization_response: enter, referer: https://justbuild.auth0.com/login?client=1mQDwTF9eWGm9iYkWG2omjtBnJVRxrH5&protocol=oauth2&state=B7rmfiMB9ztUT0oozQTD6Y022cg&redirect_uri=https%3A%2F%2Fjustbuild.ml%2Fredirect_uri&response_type=code&scope=openid%20name%20email&nonce=aeMtN8dwkm1k0VoPNQEWHq7R9mjgyIfRznxsbeXlbyA
[Sat Oct 22 23:24:19.149610 2016] [auth_openidc:debug] [pid 16:tid 139806446147328] src/util.c(1014): [client 172.17.0.1:54568] oidc_util_read_form_encoded_params: parsed: "code=V3HQEf5YjuA2XpV8&state=B7rmfiMB9ztUT0oozQTD6Y022cg" in to 2 elements, referer: https://justbuild.auth0.com/login?client=1mQDwTF9eWGm9iYkWG2omjtBnJVRxrH5&protocol=oauth2&state=B7rmfiMB9ztUT0oozQTD6Y022cg&redirect_uri=https%3A%2F%2Fjustbuild.ml%2Fredirect_uri&response_type=code&scope=openid%20name%20email&nonce=aeMtN8dwkm1k0VoPNQEWHq7R9mjgyIfRznxsbeXlbyA
[Sat Oct 22 23:24:19.149629 2016] [auth_openidc:debug] [pid 16:tid 139806446147328] src/mod_auth_openidc.c(1151): [client 172.17.0.1:54568] oidc_handle_authorization_response: enter, response_mode=query, referer: https://justbuild.auth0.com/login?client=1mQDwTF9eWGm9iYkWG2omjtBnJVRxrH5&protocol=oauth2&state=B7rmfiMB9ztUT0oozQTD6Y022cg&redirect_uri=https%3A%2F%2Fjustbuild.ml%2Fredirect_uri&response_type=code&scope=openid%20name%20email&nonce=aeMtN8dwkm1k0VoPNQEWHq7R9mjgyIfRznxsbeXlbyA
[Sat Oct 22 23:24:19.149643 2016] [auth_openidc:debug] [pid 16:tid 139806446147328] src/mod_auth_openidc.c(790): [client 172.17.0.1:54568] oidc_authorization_response_match_state: enter (state=B7rmfiMB9ztUT0oozQTD6Y022cg), referer: https://justbuild.auth0.com/login?client=1mQDwTF9eWGm9iYkWG2omjtBnJVRxrH5&protocol=oauth2&state=B7rmfiMB9ztUT0oozQTD6Y022cg&redirect_uri=https%3A%2F%2Fjustbuild.ml%2Fredirect_uri&response_type=code&scope=openid%20name%20email&nonce=aeMtN8dwkm1k0VoPNQEWHq7R9mjgyIfRznxsbeXlbyA
[Sat Oct 22 23:24:19.149657 2016] [auth_openidc:debug] [pid 16:tid 139806446147328] src/mod_auth_openidc.c(421): [client 172.17.0.1:54568] oidc_restore_proto_state: enter, referer: https://justbuild.auth0.com/login?client=1mQDwTF9eWGm9iYkWG2omjtBnJVRxrH5&protocol=oauth2&state=B7rmfiMB9ztUT0oozQTD6Y022cg&redirect_uri=https%3A%2F%2Fjustbuild.ml%2Fredirect_uri&response_type=code&scope=openid%20name%20email&nonce=aeMtN8dwkm1k0VoPNQEWHq7R9mjgyIfRznxsbeXlbyA
[Sat Oct 22 23:24:19.149681 2016] [auth_openidc:debug] [pid 16:tid 139806446147328] src/util.c(752): [client 172.17.0.1:54568] oidc_util_get_cookie: returning "mod_auth_openidc_state_B7rmfiMB9ztUT0oozQTD6Y022cg" = "Lzina8Z4McuuUxzFeedf4K3cq6Y4UJSuHdCLFO-Wxp_U7hQU6fmEw0sdYv2hTxeHLfSU8YBUH1ILYTegW2QIM7ZmantdEjunvSgiNx36LjkVfAx6VwfwGKlkSm3t_EqmRgEkH4VNd_BEw4biCkDJ84QvazLxrRWPDg9NKA16W8OxF2lq_m2M8qSXmI_3bfJhf7xhu387Xl-xmbYVWQQkFfDglEtdziHxqYt5ALjX5U5JpXpWp_oydohbGZu5uvBSNsUSkZxYiRtq-pKqVjkJY3s20X2RD7YyAeFJHJTQeyw", referer: https://justbuild.auth0.com/login?client=1mQDwTF9eWGm9iYkWG2omjtBnJVRxrH5&protocol=oauth2&state=B7rmfiMB9ztUT0oozQTD6Y022cg&redirect_uri=https%3A%2F%2Fjustbuild.ml%2Fredirect_uri&response_type=code&scope=openid%20name%20email&nonce=aeMtN8dwkm1k0VoPNQEWHq7R9mjgyIfRznxsbeXlbyA
[Sat Oct 22 23:24:19.149722 2016] [auth_openidc:debug] [pid 16:tid 139806446147328] src/util.c(712): [client 172.17.0.1:54568] oidc_util_set_cookie: adding outgoing header: Set-Cookie: mod_auth_openidc_state_B7rmfiMB9ztUT0oozQTD6Y022cg=;Path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT;Secure;HttpOnly, referer: https://justbuild.auth0.com/login?client=1mQDwTF9eWGm9iYkWG2omjtBnJVRxrH5&protocol=oauth2&state=B7rmfiMB9ztUT0oozQTD6Y022cg&redirect_uri=https%3A%2F%2Fjustbuild.ml%2Fredirect_uri&response_type=code&scope=openid%20name%20email&nonce=aeMtN8dwkm1k0VoPNQEWHq7R9mjgyIfRznxsbeXlbyA
[Sat Oct 22 23:24:19.149753 2016] [auth_openidc:debug] [pid 16:tid 139806446147328] src/mod_auth_openidc.c(440): [client 172.17.0.1:54568] oidc_restore_proto_state: restored JSON state cookie value: {"timestamp": 1477178650, "nonce": "aeMtN8dwkm1k0VoPNQEWHq7R9mjgyIfRznxsbeXlbyA", "issuer": "https://justbuild.auth0.com", "original_url": "https://justbuild.ml/", "original_method": "get", "response_type": "code"}, referer: https://justbuild.auth0.com/login?client=1mQDwTF9eWGm9iYkWG2omjtBnJVRxrH5&protocol=oauth2&state=B7rmfiMB9ztUT0oozQTD6Y022cg&redirect_uri=https%3A%2F%2Fjustbuild.ml%2Fredirect_uri&response_type=code&scope=openid%20name%20email&nonce=aeMtN8dwkm1k0VoPNQEWHq7R9mjgyIfRznxsbeXlbyA
[Sat Oct 22 23:24:19.149811 2016] [auth_openidc:debug] [pid 16:tid 139806446147328] src/mod_auth_openidc.c(143): [client 172.17.0.1:54568] oidc_get_browser_state_hash: enter, referer: https://justbuild.auth0.com/login?client=1mQDwTF9eWGm9iYkWG2omjtBnJVRxrH5&protocol=oauth2&state=B7rmfiMB9ztUT0oozQTD6Y022cg&redirect_uri=https%3A%2F%2Fjustbuild.ml%2Fredirect_uri&response_type=code&scope=openid%20name%20email&nonce=aeMtN8dwkm1k0VoPNQEWHq7R9mjgyIfRznxsbeXlbyA
[Sat Oct 22 23:24:19.149863 2016] [auth_openidc:debug] [pid 16:tid 139806446147328] src/mod_auth_openidc.c(473): [client 172.17.0.1:54568] oidc_restore_proto_state: restored state: {"original_url": "https://justbuild.ml/", "issuer": "https://justbuild.auth0.com", "nonce": "aeMtN8dwkm1k0VoPNQEWHq7R9mjgyIfRznxsbeXlbyA", "timestamp": 1477178650, "original_method": "get", "response_type": "code"}, referer: https://justbuild.auth0.com/login?client=1mQDwTF9eWGm9iYkWG2omjtBnJVRxrH5&protocol=oauth2&state=B7rmfiMB9ztUT0oozQTD6Y022cg&redirect_uri=https%3A%2F%2Fjustbuild.ml%2Fredirect_uri&response_type=code&scope=openid%20name%20email&nonce=aeMtN8dwkm1k0VoPNQEWHq7R9mjgyIfRznxsbeXlbyA
[Sat Oct 22 23:24:19.149893 2016] [auth_openidc:debug] [pid 16:tid 139806446147328] src/proto.c(1501): [client 172.17.0.1:54568] oidc_proto_handle_authorization_response_code: enter, referer: https://justbuild.auth0.com/login?client=1mQDwTF9eWGm9iYkWG2omjtBnJVRxrH5&protocol=oauth2&state=B7rmfiMB9ztUT0oozQTD6Y022cg&redirect_uri=https%3A%2F%2Fjustbuild.ml%2Fredirect_uri&response_type=code&scope=openid%20name%20email&nonce=aeMtN8dwkm1k0VoPNQEWHq7R9mjgyIfRznxsbeXlbyA
[Sat Oct 22 23:24:19.149913 2016] [auth_openidc:debug] [pid 16:tid 139806446147328] src/proto.c(867): [client 172.17.0.1:54568] oidc_proto_resolve_code: enter, referer: https://justbuild.auth0.com/login?client=1mQDwTF9eWGm9iYkWG2omjtBnJVRxrH5&protocol=oauth2&state=B7rmfiMB9ztUT0oozQTD6Y022cg&redirect_uri=https%3A%2F%2Fjustbuild.ml%2Fredirect_uri&response_type=code&scope=openid%20name%20email&nonce=aeMtN8dwkm1k0VoPNQEWHq7R9mjgyIfRznxsbeXlbyA
[Sat Oct 22 23:24:19.150049 2016] [auth_openidc:debug] [pid 16:tid 139806446147328] src/util.c(600): [client 172.17.0.1:54568] oidc_util_http_post_form: post data="grant_type=authorization_code&code=V3HQEf5YjuA2XpV8&redirect_uri=https%3A%2F%2Fjustbuild.ml%2Fredirect_uri&client_id=1mQDwTF9eWGm9iYkWG2omjtBnJVRxrH5&client_secret=8tXmh1J2KT6TuyDCBCXPAAoV3jzLVCcy5fu0HI8NZTr_YsSVCO111ei8c5X43_QK", referer: https://justbuild.auth0.com/login?client=1mQDwTF9eWGm9iYkWG2omjtBnJVRxrH5&protocol=oauth2&state=B7rmfiMB9ztUT0oozQTD6Y022cg&redirect_uri=https%3A%2F%2Fjustbuild.ml%2Fredirect_uri&response_type=code&scope=openid%20name%20email&nonce=aeMtN8dwkm1k0VoPNQEWHq7R9mjgyIfRznxsbeXlbyA
[Sat Oct 22 23:24:19.150092 2016] [auth_openidc:debug] [pid 16:tid 139806446147328] src/util.c(427): [client 172.17.0.1:54568] oidc_util_http_call: url=https://justbuild.auth0.com/oauth/token, data=grant_type=authorization_code&code=V3HQEf5YjuA2XpV8&redirect_uri=https%3A%2F%2Fjustbuild.ml%2Fredirect_uri&client_id=1mQDwTF9eWGm9iYkWG2omjtBnJVRxrH5&client_secret=8tXmh1J2KT6TuyDCBCXPAAoV3jzLVCcy5fu0HI8NZTr_YsSVCO111ei8c5X43_QK, content_type=application/x-www-form-urlencoded, basic_auth=(null), bearer_token=(null), ssl_validate_server=1, referer: https://justbuild.auth0.com/login?client=1mQDwTF9eWGm9iYkWG2omjtBnJVRxrH5&protocol=oauth2&state=B7rmfiMB9ztUT0oozQTD6Y022cg&redirect_uri=https%3A%2F%2Fjustbuild.ml%2Fredirect_uri&response_type=code&scope=openid%20name%20email&nonce=aeMtN8dwkm1k0VoPNQEWHq7R9mjgyIfRznxsbeXlbyA
[Sat Oct 22 23:24:19.568230 2016] [auth_openidc:debug] [pid 16:tid 139806446147328] src/util.c(551): [client 172.17.0.1:54568] oidc_util_http_call: response={"access_token":"W8t41XPx5mTBJOGM","id_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiZWx3ZWJtYXN0ZXJAZ21haWwuY29tIiwiZW1haWwiOiJlbHdlYm1hc3RlckBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9qdXN0YnVpbGQuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDU4MGJlMzFkMTA2ZDU3ODM0ZDY1Nzg2NiIsImF1ZCI6IjFtUUR3VEY5ZVdHbTlpWWtXRzJvbWp0Qm5KVlJ4ckg1IiwiZXhwIjoxNDc3MjE0NTU1LCJpYXQiOjE0NzcxNzg1NTUsIm5vbmNlIjoiYWVNdE44ZHdrbTFrMFZvUE5RRVdIcTdSOW1qZ3lJZlJ6bnhzYmVYbGJ5QSJ9.pvR15gjws4DzWMDIyP8mxQnktpdYNDpQGjoVbnmtiA8","token_type":"Bearer"}, referer: https://justbuild.auth0.com/login?client=1mQDwTF9eWGm9iYkWG2omjtBnJVRxrH5&protocol=oauth2&state=B7rmfiMB9ztUT0oozQTD6Y022cg&redirect_uri=https%3A%2F%2Fjustbuild.ml%2Fredirect_uri&response_type=code&scope=openid%20name%20email&nonce=aeMtN8dwkm1k0VoPNQEWHq7R9mjgyIfRznxsbeXlbyA
[Sat Oct 22 23:24:19.573130 2016] [auth_openidc:debug] [pid 16:tid 139806446147328] src/proto.c(1199): [client 172.17.0.1:54568] oidc_proto_validate_code_response: enter, referer: https://justbuild.auth0.com/login?client=1mQDwTF9eWGm9iYkWG2omjtBnJVRxrH5&protocol=oauth2&state=B7rmfiMB9ztUT0oozQTD6Y022cg&redirect_uri=https%3A%2F%2Fjustbuild.ml%2Fredirect_uri&response_type=code&scope=openid%20name%20email&nonce=aeMtN8dwkm1k0VoPNQEWHq7R9mjgyIfRznxsbeXlbyA
[Sat Oct 22 23:24:19.573209 2016] [auth_openidc:debug] [pid 16:tid 139806446147328] src/proto.c(713): [client 172.17.0.1:54568] oidc_proto_parse_idtoken: enter, referer: https://justbuild.auth0.com/login?client=1mQDwTF9eWGm9iYkWG2omjtBnJVRxrH5&protocol=oauth2&state=B7rmfiMB9ztUT0oozQTD6Y022cg&redirect_uri=https%3A%2F%2Fjustbuild.ml%2Fredirect_uri&response_type=code&scope=openid%20name%20email&nonce=aeMtN8dwkm1k0VoPNQEWHq7R9mjgyIfRznxsbeXlbyA
[Sat Oct 22 23:24:19.573347 2016] [auth_openidc:debug] [pid 16:tid 139806446147328] src/proto.c(728): [client 172.17.0.1:54568] oidc_proto_parse_idtoken: successfully parsed (and possibly decrypted) JWT with header: "{"typ":"JWT","alg":"HS256"}", referer: https://justbuild.auth0.com/login?client=1mQDwTF9eWGm9iYkWG2omjtBnJVRxrH5&protocol=oauth2&state=B7rmfiMB9ztUT0oozQTD6Y022cg&redirect_uri=https%3A%2F%2Fjustbuild.ml%2Fredirect_uri&response_type=code&scope=openid%20name%20email&nonce=aeMtN8dwkm1k0VoPNQEWHq7R9mjgyIfRznxsbeXlbyA
[Sat Oct 22 23:24:19.573377 2016] [auth_openidc:debug] [pid 16:tid 139806446147328] src/proto.c(677): [client 172.17.0.1:54568] oidc_proto_jwt_verify: "jwks_uri" is set, but the JWT has a symmetric signature so we won't pull/use keys from there, referer: https://justbuild.auth0.com/login?client=1mQDwTF9eWGm9iYkWG2omjtBnJVRxrH5&protocol=oauth2&state=B7rmfiMB9ztUT0oozQTD6Y022cg&redirect_uri=https%3A%2F%2Fjustbuild.ml%2Fredirect_uri&response_type=code&scope=openid%20name%20email&nonce=aeMtN8dwkm1k0VoPNQEWHq7R9mjgyIfRznxsbeXlbyA
[Sat Oct 22 23:24:19.573460 2016] [auth_openidc:error] [pid 16:tid 139806446147328] [client 172.17.0.1:54568] oidc_proto_jwt_verify: JWT signature verification failed: [src/jose/apr_jws.c:587: apr_jws_verify]: could not verify signature against any of the (1) provided keys\n, referer: https://justbuild.auth0.com/login?client=1mQDwTF9eWGm9iYkWG2omjtBnJVRxrH5&protocol=oauth2&state=B7rmfiMB9ztUT0oozQTD6Y022cg&redirect_uri=https%3A%2F%2Fjustbuild.ml%2Fredirect_uri&response_type=code&scope=openid%20name%20email&nonce=aeMtN8dwkm1k0VoPNQEWHq7R9mjgyIfRznxsbeXlbyA
[Sat Oct 22 23:24:19.573481 2016] [auth_openidc:error] [pid 16:tid 139806446147328] [client 172.17.0.1:54568] oidc_proto_parse_idtoken: id_token signature could not be validated, aborting, referer: https://justbuild.auth0.com/login?client=1mQDwTF9eWGm9iYkWG2omjtBnJVRxrH5&protocol=oauth2&state=B7rmfiMB9ztUT0oozQTD6Y022cg&redirect_uri=https%3A%2F%2Fjustbuild.ml%2Fredirect_uri&response_type=code&scope=openid%20name%20email&nonce=aeMtN8dwkm1k0VoPNQEWHq7R9mjgyIfRznxsbeXlbyA
[Sat Oct 22 23:24:24.499162 2016] [ssl:debug] [pid 16:tid 139806176618240] ssl_engine_io.c(1016): [remote 172.17.0.1:54568] AH02001: Connection closed to child 1 with standard shutdown (server justbuild.ml:443)

**Comment by dimitrovs** [comment]
I was able to work around this problem by changing the signing algorithm in Auth0 from HS256 (default) to RS256.
But now I get an exception that the server certificate is not valid. My Apache server has a certificate signed by Cloudflare (so not by a recognized CA) but why is mod_auth_openidc connecting to the Apache server over its internal IP? Why does it need to connect to Apache over HTTPS at all? I am confused by this authentication process.
It works with `OIDCSSLValidateServer Off` but I am not sure what this option implies. All I found online is that "It breaks security". What does this mean? Note that my endpoint (which Auth0 may be connecting to) DOES have a valid SSL certificate (as provided by CloudFlare), it's just the internal Apache cert that is not signed by a recognized CA and the CloudFlare reverse proxy should be the only system to ever connect to this internal IP.

**Comment by zandbelt** [comment]
Can you paste the error.log and your config here (with obfuscated security related values)?

**Comment by zandbelt** [comment]
FWIW: your first issue is covered in https://auth0.com/docs/quickstart/webapp/apache

**Comment by dimitrovs** [comment]
I cannot reproduce the OIDCSSLValidateServer Off issue anymore. It works without it as well now. I will be closing this issue, but just for information would you say that Apache + mod_auth_openidc in front of Nginx (which does header-based proxying) would perform better than just Nginx with lua-resty-openidc (i.e. authentication + header-based proxying)? I already got it working with Apache when I discovered the Nginx module so I am not sure if it's worth investing more effort into switching to Nginx.
My setup is like this: CloudFlare -> Apache (mod_auth_openidc) -> Nginx (convert user claim to hostname ) -> Local DNS (maps hostname to backend IP) -> Backend . The idea is to have one backend per user.
