### ISSUE TITLE
Error parsing fractional values in JWT exp

### ISSUE THREAD

**Issue by drdivano** [pingidentity/mod_auth_openidc#187]
An OP implementation I'm working with (pyoidc) uses seconds with decimal fractions for NumericDate fields. (Example: "exp": 1477312112.172277)

When encountering such values mod_auth_openidc fails with an error:

oidc_proto_validate_exp: JWT did not contain an "exp" number value

However the OAuth spec says, that for NumericDate fields "non-integer values can be represented"
See https://tools.ietf.org/html/rfc7519#section-4.1.4

**Comment by drdivano** [comment]
Just checked - yes, it works for me now.
Many thanks!

**Comment by zandbelt** [comment]
thanks for checking and reporting back!
