### ISSUE TITLE
Require claim "scopes~%{custom_env_var}e" not working.

### ISSUE THREAD

**Issue by ngnanavadivel** [pingidentity/mod_auth_openidc#188]
Dear All,

Could you please fix or guide me about the usage of matching dynamic variables like env. variables in the Require Claim section to do authorization.

The use case is  as follows:
REQUEST_URI -> /cxf/rest/MyService
Using SetEnvIf, SRV_REQUESTED environment variable is set to 'MyService'.

The OAuth token verification gives a response which is a json having
{
audience:'some-client',
scopes:['MyService', 'YourService']
}

Now to validate against the SCOPE and the URI fragment to be matching,

we are trying to use

Require claim "scopes~%{SRV_REQUESTED}e"
But that is not working at all.....

However a static value works fine...like Require claim scopes~MyService..

Help us out please..

**Comment by zandbelt** [comment]
Environment variables are available only after the authentication process has finished, and in fact the information from the authentication process is then available in environment variables. 

You could separate your paths like:
```
<Location /cxf/rest/MyService>
    Require claim "scopes~ MyService"
</Location>

<Location /cxf/rest/YourService >
    Require claim "scopes~ YourService"
</Location>
```
Possibly even through include config files generated by some script.
