### ISSUE TITLE
404 on consecutive calls

### ISSUE THREAD

**Issue by jennyfurtado2** [pingidentity/mod_auth_openidc#201]
I noticed that the first time I hit my url it will work fine, but if right after I try again it will give me a 404.
If I wait 9 minutes or so it will work again.
This seems to be associated with the mod_auth_openidc_session being cached.
Is there a way to prevent this behavior?

**Comment by zandbelt** [comment]
Can you provide a debug log of that and send your http.conf?

**Comment by jennyfurtado2** [comment]
Unfortunately I cant. 
You suspect that something in apache other than the auth oidc module is rejecting the request?
This is the bad request I observe in the browser
------------------------------------------------------
https://some.com/oidc/abc

GET /oidc/abc HTTP/1.1
Host: some.com
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Cookie: __utma=264805659.704981365.1480452213.1480455841.1480457718.3; __utmz=264805659.1480452213.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); _ga=GA1.3.704981365.1480452213; __utmb=264805659.3.10.1480457718; __utmt=1; _gat_UA-74627609-1=1; mod_auth_openidc_session=08d59cbe-9506-294c-a9bb-0a5ef3ce5bc3; JSESSIONIDSSO=52DB5F2300F70AD8981B913BD309C84B; __utmc=264805659
Connection: keep-alive
Upgrade-Insecure-Requests: 1

HTTP/1.1 404 Not Found
Date: Tue, 29 Nov 2016 22:19:40 GMT
Server: Apache/2.4.12 (Win32) OpenSSL/1.0.2 mod_flvx/0.4
Set-Cookie: mod_auth_openidc_session=08d59cbe-9506-294c-a9bb-0a5ef3ce5bc3;;Secure;Path=/;HttpOnly
Content-Length: 206
Connection: close
Content-Type: text/html; charset=iso-8859-1
--------------------------------------------------------

**Comment by zandbelt** [comment]
really hard to say anything about it based on just the client-side info; the server-side debug log would tell you what mod_auth_openidc is doing before the 404 is returned and would probably also show another module/function kicking in

**Comment by jennyfurtado2** [comment]
I found out that the issue is the cookie
mod_auth_openidc_session
is not cleared at the end of the authentication.
Is there an option to clear it after authentication is complete?

**Comment by zandbelt** [comment]
`mod_auth_openidc_session` is keeping track of the fact that the user has already authenticated; if that cooke would not be set after authentication, the user would be sent off to the Provider again to authenticate and you'd send the browser in an endless loop...
