### ISSUE TITLE
Gitlab OAuth2 ?

### ISSUE THREAD

**Issue by SirNolaan** [pingidentity/mod_auth_openidc#203]
Hello,

Is it possible to protect some directory and give users access from Gitlab?
https://docs.gitlab.com/ee/integration/oauth_provider.html
I do not know Is it possible to connect gitlab with mod_auth_openidc

**Comment by zandbelt** [comment]
There's some confusing language on that page, but it doesn't seem that Gitlab conforms to the OpenID Connect specification thus it cannot be used as an OpenID Connect provider signing in to mod_auth_openidc.

**Comment by lnxbil** [comment]
Only for reference:
I just added a section about setting it up with GitLab with their new OpenID Connect:
https://github.com/zmartzone/mod_auth_openidc/wiki#20-how-do-i-authenticate-against-a-gitlab-oauth2-server
