### ISSUE TITLE
New session created after 1 minute or more of inactivity

### ISSUE THREAD

**Issue by anagan** [pingidentity/mod_auth_openidc#204]
We have multiple chart widgets in our app, each making a XHR request to APIs to fetch data. These APIs are setup behind Apache and with Apache as reverse proxy. After authentication when page loads multiple XHR requests are sent from browser and initially everything works fine. After a [minute](https://github.com/pingidentity/mod_auth_openidc/blob/master/src/mod_auth_openidc.c#L1360-L1368) or more has elapsed and when navigated to another page which has another set of widgets making XHR calls, only 1st or 2nd requests go through. It was observed 1st or 2nd XHR response gets a new session cookie with a new UUID value and old is invalidated. Since all XHR calls are almost made at same time some fail because old cookie was sent with XHR which is no longer available. 

Since session cookie value(UUID) is used as a key for session data lookup, is it possible to preserve same session cookie value for the lifetime of the session?

**Comment by zandbelt** [comment]
Which version of the module are you on?

**Comment by anagan** [comment]
Its 2.1.2

**Comment by zandbelt** [comment]
Could you send a debug log file of this event happening?

Normally an XHR call should not result in a redirect that will never resolve. See also https://github.com/pingidentity/mod_auth_openidc/wiki/Cookies for hints around this.

**Comment by anagan** [comment]
Debug log attached. [Attachment](https://github.com/pingidentity/mod_auth_openidc/files/646883/New_Session.txt)

All XHR calls has X-Requested-With in the header resulting 401 after new session is created

**Comment by zandbelt** [comment]
can you try f2dd8f9

**Comment by anagan** [comment]
Thank you @zandbelt, it works like a charm, will run few more tests and confirm.

**Comment by zandbelt** [comment]
I've tuned it a bit in a followup commit 20787d5d48ff314fbb7bea21f92c1dc2e226891c

**Comment by askainet** [comment]
Thanks @zandbelt for the fix, last week I was trying to use your module in front of https://github.com/lmenezes/elasticsearch-kopf and experiencing the same issues as @anagan, I can also confirm that the uuid of the cookie remains unchanged now and it works like a charm.

**Comment by zandbelt** [comment]
@askainet thanks for chiming in; I'll release 2.1.3 shortly

**Comment by iamambrus** [comment]
Works perfectly, thanks @zandbelt!
