### ISSUE TITLE
Using secondary OIDCRedirectURI

### ISSUE THREAD

**Issue by user-528392347** [pingidentity/mod_auth_openidc#209]
We are using claims on user metadata to determine whether a user has access to a specific application or not via, and each application has a callback registered with Auth0 (website.com/app1/auth, website.com/app2/auth), etc.

Apache will default to always using the callback specified by OIDCRedirectURI, so that secondary callbacks defined in Auth0 are not accessible. This makes any non-default applications inaccessible.

```
OIDCRedirectURI website.com/app1/auth

<location /app1/>
    AuthType openid-connect
    Require claim valid_app1:true
</Location>

<location /app2/>
    AuthType openid-connect
    Require claim valid_app2:true
</Location>
```

Is it possible to configure so that /app1/ uses callback /app1/auth and /app2/ uses callback /app2/auth? If not, what is the standard approach for returning a user to the location they initially attempted to load, rather than a default callback location?

**Comment by zandbelt** [comment]
Just to close the loop on this one: the originally request URL is kept as part of the "state" that is created upon starting authentication towards an OP (and referred to by the `state` parameter). Upon callback from the OP to the OIDCRedirectURI, the OP will also send back the state parameter and `mod_auth_openidc` will restore the state which contains the original URL and will, after verification of the login, return to that URL. So there is no need for 2 redirect URIs for this use case.
