### ISSUE TITLE
Error state cookie not found / can't parse JWT

### ISSUE THREAD

**Issue by StairZ0** [pingidentity/mod_auth_openidc#213]
Hello,

I'm having a really troubling issue and can't find which component could be the cause.

Here's my setup :

Our Application involves an Apache 2.2 using mod_auth_openidc (1.8.10 on RHEL6.8) to authenticate users on the "/" Location with that in mind we also have multiple tomcats behind running our webapps. One is using AJP and the others have another Apache in front with a mod_jk connection.
Also our Apache is using a multi-vhost configuration with mod_auth_openidc for some vhosts and simplesamlphp for others.

We're using Auth0 as our Identity Provider for openidc vhosts.

Apache configuration : 

```
  OIDCProviderIssuer https://<Auth0_domain>
  OIDCProviderAuthorizationEndpoint https://<Auth0_domain>/authorize
  OIDCProviderTokenEndpoint https://<Auth0_domain>/oauth/token
  OIDCProviderTokenEndpointAuth client_secret_post
  OIDCProviderUserInfoEndpoint https://<Auth0_domain>/userinfo
  OIDCClientID <CLIENT_ID>
  OIDCClientSecret <SECRET>
  OIDCProviderJwksUri https://<Auth0_domain>/.well-known/jwks.json
  OIDCScope "openid realm uid email"
  OIDCRedirectURI https://<Application_Domain>/auth0/callback
  OIDCCryptoPassphrase <PASSPHRASE>
  OIDCCookiePath /

 <Location />
 AuthType openid-connect
 Require valid-user
 </Location>
```

The issue here is when i'm already connected to the application and i try to access the root domain like
"https://example.com" mod_auth_openidc generates a 500 error code with these logs : 

 ```
[Mon Jan 23 16:19:02 2017] [error] [client XX.XX.XX.XX] oidc_clean_expired_state_cookies: state has expired, referer: XXX
[Mon Jan 23 16:19:02 2017] [error] [client XX.XX.XX.XX] oidc_restore_proto_state: no "mod_auth_openidc_state_k25dbvr5cw-Q1q2Y5308WEFizyI" state cookie found, referer: XXX
[Mon Jan 23 16:19:02 2017] [error] [client XX.XX.XX.XX] oidc_unsolicited_proto_state: could not parse JWT from state: invalid unsolicited response: [src/jose/apr_jwt.c:180: apr_jwt_base64url_decode_object]: JSON parsing (json_loads) failed: unable to decode byte 0x93 (\x93n]n\xfa\xf9s\x0f\x90\xd6\xad\x98\xe7}<XAb\xcf")\n, referer: XXX
[Mon Jan 23 16:19:02 2017] [error] [client XX.XX.XX.XX] oidc_authorization_response_match_state: unable to restore state, referer: XXX
[Mon Jan 23 16:19:02 2017] [error] [client XX.XX.XX.XX] oidc_handle_authorization_response: invalid authorization response state and no default SSO URL is set, sending an error..., referer: XXX
```

But in the meantime if i just had a GET Parameter to this URL even unrelated to our application this error does not occur.
For example : "https://example.com/?a=b".

I really can't find the root cause of this behaviour, do you have any idea regarding this issue ?

PS : If someone has any idea i'll be extremely grateful because i'm really starting to lose my mind on this one :)

**Comment by zandbelt** [comment]
This error happens when you hit the `OIDCRedirectURI` with no parameters. It looks like there must be some configuration mixup that makes "https://example.com" the designated redirect URI.

**Comment by StairZ0** [comment]
Thank you for your answer, it seems everything is working now.
The root cause of the issue was a misconfiguration of caching, the redirectURI was cached.

**Comment by SantoshNII** [comment]
@StairZ0 We are also facing similar issue. How did you fix that issue? What was the misconfiguration? 

This information would be really great help for us.

**Comment by StairZ0** [comment]
@SantoshNII Hello, well the caching issue wasn't really related to this error but it solved our logout issues.
For this issue we found a workaround with the directive OIDCDefaultURL redirecting to an index page and not to the root Location. The error still happens but no Internal Server Error is visible now. I don't know how bad from a security point of view this is but right now we're using mod_auth_openidc only for development.
