### ISSUE TITLE
Got 'openssl/obj_mac.h' file not found error on Mac OS

### ISSUE THREAD

**Issue by ekarudianto** [pingidentity/mod_auth_openidc#217]
Been trying to install this library all runnning well untill I tried to run 'make', I got this error

> clang: warning: /usr/local/opt/cjose/include: 'linker' input unused
In file included from src/mod_auth_openidc.c:74:
In file included from src/mod_auth_openidc.h:60:
In file included from src/jose.h:64:
In file included from /usr/local/include/cjose/cjose.h:26:
/usr/local/include/cjose/jwk.h:20:10: fatal error: 'openssl/obj_mac.h' file not found
#include <openssl/obj_mac.h>
         ^
1 error generated.
apxs:Error: Command failed with rc=65536
.
make: *** [src/mod_auth_openidc.la] Error 1

Below is my environment setup

- Apache (2.4.25)
- cjose (latest)
- OpenSSL (OpenSSL 1.0.2j  26 Sep 2016)
- Curl
- Jansson (2.9)
- pcre3 (8.39)
- pkg-config (0.29.1_2)
- hiredis (0.13.3)

*note that all software is installed using Brew (don't know if it will be matter just put some informations together)

Below is my ./configure setup

> erudianto$ CJOSE_CFLAGS=/usr/local/opt/cjose/include CJOSE_LIBS=/usr/local/opt/cjose/lib ./configure --with-apxs2=/Users/erudianto/Downloads/apache-server/dist/bin/apxs --prefix /Users/erudianto/Downloads/mod_auth_openidc-2.1.3/dist

**Comment by zandbelt** [comment]
Looks like there is more than one OpenSSL version present on your system. You may want to edit the generated Makefile by hand to point to the right OpenSSL include path, typically by including that path before any other system paths.

**Comment by ekarudianto** [comment]
thanks for the reply @zandbelt , can you give me some pointers on what line should I changed ? really sorry but I'm new to this thing

**Comment by zandbelt** [comment]
You can also try changing your `configure` command to:

`OPENSSL_CFLAGS=<path> OPENSSL_LIBS=<path> CJOSE_CFLAGS=/usr/local/opt/cjose/include CJOSE_LIBS=/usr/local/opt/cjose/lib ./configure --with-apxs2=/Users/erudianto/Downloads/apache-server/dist/bin/apxs --prefix /Users/erudianto/Downloads/mod_auth_openidc-2.1.3/dist
`

**Comment by ekarudianto** [comment]
Hi @zandbelt 

I tried your way but unfortunately I still getting this error

> clang: warning: /usr/local/opt/openssl/include: 'linker' input unused
clang: warning: /usr/local/opt/cjose/include: 'linker' input unused
In file included from src/mod_auth_openidc.c:74:
In file included from src/mod_auth_openidc.h:60:
In file included from src/jose.h:64:
In file included from /usr/local/include/cjose/cjose.h:26:
/usr/local/include/cjose/jwk.h:20:10: fatal error: 'openssl/obj_mac.h' file not found
#include <openssl/obj_mac.h>
         ^
1 error generated.
apxs:Error: Command failed with rc=65536

below is my configuration

> OPENSSL_CFLAGS=/usr/local/opt/openssl/include 
> OPENSSL_LIBS=/usr/local/opt/openssl/lib 
> CJOSE_CFLAGS=/usr/local/opt/cjose/include 
> CJOSE_LIBS=/usr/local/opt/cjose/lib 
> ./configure 
> --with-apxs2=/Users/erudianto/Downloads/apache-server/dist/bin/apxs 
> --prefix /Users/erudianto/Downloads/mod_auth_openidc-2.1.3/dist

do you think I missed something ?

**Comment by zandbelt** [comment]
Can you verify that the file
`/usr/local/opt/openssl/include/openssl/obj_mac.h`
exists on your system?

**Comment by ekarudianto** [comment]
Hi @zandbelt 

Yes I think so

<img width="705" alt="screen shot 2017-01-25 at 11 08 13 pm" src="https://cloud.githubusercontent.com/assets/5218495/22295808/2d75a7d2-e353-11e6-90dc-f5157699218e.png">

**Comment by zandbelt** [comment]
Can you paste the generated Makefile?

**Comment by ekarudianto** [comment]
Hi @zandbelt 

# Source files. mod_auth_openidc.c must be the first file.
SRC=src/mod_auth_openidc.c \
	src/cache/file.c \
	src/cache/memcache.c \
	src/cache/shm.c \
	src/cache/lock.c \
	src/oauth.c \
	src/proto.c \
	src/config.c \
	src/util.c \
	src/authz.c \
	src/session.c \
	src/metadata.c \
	src/jose.c \
	src/parse.c

ifeq (1, 1)
SRC += \
	src/cache/redis.c	
REDIS_CFLAGS=-DUSE_LIBHIREDIS -D_FILE_OFFSET_BITS=64 -I/usr/local/Cellar/hiredis/0.13.3/include/hiredis
REDIS_LIBS=-L/usr/local/Cellar/hiredis/0.13.3/lib -lhiredis
endif

HDRS = \
	$(JWT_HDRS) \
	src/mod_auth_openidc.h \
	src/jose.h \
	src/parse.h \
	src/cache/cache.h

# Files to include when making a .tar.gz-file for distribution
DISTFILES=$(SRC) \
	$(HDRS) \
	test/test.c \
	test/test-cmd.c \
	test/stub.c \
	configure \
	configure.ac \
	Makefile.in \
	autogen.sh \
	INSTALL \
	README.md \
	AUTHORS \
	DISCLAIMER \
	auth_openidc.conf \
	LICENSE.txt \
	ChangeLog

all: src/mod_auth_openidc.la

CFLAGS=/usr/local/opt/openssl/include  -I/usr/local/Cellar/jansson/2.9/include /usr/local/opt/cjose/include -I/usr/local/include $(REDIS_CFLAGS)
LIBS=/usr/local/opt/openssl/lib -lcurl -L/usr/local/Cellar/jansson/2.9/lib -ljansson /usr/local/opt/cjose/lib -lpcre $(REDIS_LIBS)

src/mod_auth_openidc.la: $(SRC) $(HDRS)
	/Users/erudianto/Downloads/apache-server/dist/bin/apxs  -Wc,"-DNAMEVER=\"mod_auth_openidc-2.1.3\" $(CFLAGS)" -Wl,"$(LIBS)" -Wc,-Wall -Wc,-g -c $(SRC)

configure:	configure.ac
	./autogen.sh

mod_auth_openidc-2.1.3.tar.gz:	 $(DISTFILES)
	tar -c --transform="s#^#mod_auth_openidc-2.1.3/#" -vzf $@ $(DISTFILES)

test/test test/test-cmd: test/test.c test/stub.c src/mod_auth_openidc.la
	/Users/erudianto/Downloads/apache-server/dist/bin/apxs  $(CFLAGS) -Wl,"$(LIBS)" -Isrc -Wc,-Wall -Wc,-g -c -o $@ $@.c test/stub.c $(SRC:.c=.lo) -laprutil-1 -lldap -llber -lexpat -liconv -lsqlite3 -lldap -llber -lapr-1 -lpthread

test-compile: test/test test/test-cmd

test: test-compile
	test/test

.PHONY:	install
install: src/mod_auth_openidc.la
	/Users/erudianto/Downloads/apache-server/dist/bin/apxs  -i -n mod_auth_openidc src/mod_auth_openidc.la

.PHONY: distfile
distfile:	mod_auth_openidc-2.1.3.tar.gz

.PHONY:	clean
clean:
	rm -f src/mod_auth_openidc.la
	rm -f src/*.o src/cache/*.o test/*.o
	rm -f src/*.lo src/cache/*.lo test/*.lo
	rm -f src/*.slo src/cache/*.slo test/*.slo
	rm -rf src/.libs/ src/cache/.libs/ test/.libs
	rm -rf test/test test/test-cmd

.PHONY:	distclean
distclean:	clean
	rm -f Makefile config.log config.status mod_auth_openidc-2.1.3.tar.gz *~ \
	build-stamp config.guess config.sub
	rm -rf debian/mod-auth_openidc
	rm -f debian/files

.PHONY: fullclean
fullclean:	distclean
	rm -f configure aclocal.m4

**Comment by ekarudianto** [comment]
Turns out I need to modify the Makefile in order to make it work

> CFLAGS=-I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib -I/usr/local/opt/curl/include -I/usr/local/Cellar/jansson/2.7/include  -I/usr/local/opt/cjose/include -I/usr/local/Cellar/pcre/8.39/include  $(REDIS_CFLAGS)
LIBS=-lssl -lcrypto -lz  -L/usr/local/opt/curl/lib -lcurl -L/usr/local/Cellar/jansson/2.7/lib -ljansson  -L/usr/local/opt/cjose/lib -lcjose -L/usr/local/Cellar/pcre/8.39/lib -lpcre  $(REDIS_LIBS)

I get it from this [website](http://lifewithcode.blogspot.co.uk/2016/10/securing-apache-on-osx-using.html)

thanks for the help !
