### ISSUE TITLE
Need to set roles/group info of a authenticated user

### ISSUE THREAD

**Issue by abhishekraghav** [pingidentity/mod_auth_openidc#221]
I am using keycloak and trying to protect my apps running behind mod_auth_openidc. I would want to know, is there a possibilty i can set role/group info in the header so that my app can use it.

I am creating client mappers for roles/groups in keycloak and adding those mappers in idToken/userInfo endpoint as well and then in conf file i am specifying it like this: 
**OIDCRemoteUserClaim role**

So i am able to see user roles claim in the apache console, but when i say like 👍 
**OIDCRemoteUserClaim group**
_OpenID Connect Provider error: Remote user could not be set: contact the website administrator_

And in the console, 
OIDCRemoteUserClaim is set to "group", but the id_token JSON Payload and user claims did not contain a "group" string, referer.....
and i dont see user groups coming through.

Also my doubt is, if i add role/group mapper in IDtoken/userInfo, then when the user get authenticated on keycloak, after authentication is successful.
Will **mod_auth_openidc** add all claims which are part of IDtoken to the headers and my applications can consume those headers.

Thanks in advance.
Cheers
Abhishek

**Comment by zandbelt** [comment]
The `OIDCRemoteUserClaim` needs to refer to a claim that exists in either the `id_token` or the claims returned from the userinfo endpoint. So you'll need to make Keycloak return a group in the `group` claim or base `OIDCRemoteUserClaim` on some other claim that is actually passed in from the Provider.

mod_auth_openidc will add all claims that are part of the ID token and those that are returned from the userinfo endpoint as headers for the application and/or as environment variables, see: https://github.com/pingidentity/mod_auth_openidc/blob/master/auth_openidc.conf#L598

**Comment by abhishekraghav** [comment]
Thanks for your prompt reply.
When i introspected my userinfo endpoint, i found that "group" is not string type, its an array that returns.
I am also attaching the output of my userinfo endpoint.  
![image](https://cloud.githubusercontent.com/assets/19988460/22422606/5ea503c0-e713-11e6-86f9-a4c16d522313.png)

When i define the Role as a client mapper, i am setting the "claim json type" as "String" where as in case of group membership claim, there is no way to define json type as String. By default it is a array type. Might be  mod_auth_openidc works well if claim is String type and since group claim is an Array type it doesnot. Please see the returned response in the image attached. Am i missing any configuration. 
Thanks.

**Comment by zandbelt** [comment]
You can't map an array to `OIDCRemoteUserClaim`. You'll have to map the (single) group in Keycloak to a string claim if you want to use that info.
