### ISSUE TITLE
HTTP 404 errors when access to RP and OP frames

### ISSUE THREAD

**Issue by security4java** [pingidentity/mod_auth_openidc#223]
Hello,
I successfully integrated mod_auth_openidc with Keycloak:
I try to implement the Session Management using OP and RP frames as described here:
https://github.com/pingidentity/mod_auth_openidc/wiki/Session-Management
I put (first manually) the following in my html page:
<iframe title='empty' style='visibility: hidden;' width='0' height='0' tabindex='-1' id='openidc-op' src='https://<ip>/protected/redirect_uri?session=iframe_op'></iframe><iframe title='empty' style='visibility: hidden;' width='0' height='0' tabindex='-1' id='openidc-rp' src='https:// <ip>/protected/redirect_uri?session=iframe_rp\&amp;poll=5000'></iframe>

Unfortunately I get HTTP 404 errors when access to RP and OP frames.
I tried to call to the following URL using curl:
curl -k -v -H "Cookie: mod_auth_openidc_session=1f2c9173-fd1b-455f-b605-2b79dac30faf" https://<ip>/protected/redirect_uri?session=iframe_rp
I also get HTTP 404 errors.

Note that Keycloak supports the Session Management and it returns the login-status-iframe.html (the URL is populated via check_session_iframe)

curl -k -v -H "Cookie: mod_auth_openidc_session=1f2c9173-fd1b-455f-b605-2b79dac30faf" https://<ip>/auth/realms/realm/protocol/openid-connect/login-status-iframe.html

What wrong in my configuration and what should I do to configure the Session Management?

**Comment by zandbelt** [comment]
The 404 usually means that session management support was not detected/enabled at the OP. Can you provide the version of mod_auth_openidc that you use, the debug logs (`LogLevel debug`) and the Discovery metadata of the keycloak server?

**Comment by security4java** [comment]
I use mod_auth_openidc version "2.1.2", Keycloak version “2.4.0”

curl -k  https://localhost/auth/realms/realm/.well-known/openid-configuration
{"issuer":"https://localhost/auth/realms/realm","authorization_endpoint":"https://localhost/auth/realms/realm/protocol/openid-connect/auth","token_endpoint":"https://localhost/auth/realms/realm/protocol/openid-connect/token","token_introspection_endpoint":"https://localhost/auth/realms/realm/protocol/openid-connect/token/introspect","userinfo_endpoint":"https://localhost/auth/realms/realm/protocol/openid-connect/userinfo","end_session_endpoint":"https://localhost/auth/realms/realm/protocol/openid-connect/logout","jwks_uri":"https://localhost/auth/realms/realm/protocol/openid-connect/certs","check_session_iframe":"https://localhost/auth/realms/realm/protocol/openid-connect/login-status-iframe.html","grant_types_supported":["authorization_code","implicit","refresh_token","password","client_credentials"],"response_types_supported":["code","none","id_token","token","id_token token","code id_token","code token","code id_token token"],"subject_types_supported":["public","pairwise"],"id_token_signing_alg_values_supported":["RS256"],"userinfo_signing_alg_values_supported":["RS256"],"request_object_signing_alg_values_supported":["none","RS256"],"response_modes_supported":["query","fragment","form_post"],"registration_endpoint":"https://localhost/auth/realms/realm/clients-registrations/openid-connect","token_endpoint_auth_methods_supported":["private_key_jwt","client_secret_basic","client_secret_post"],"token_endpoint_auth_signing_alg_values_supported":["RS256"],"claims_supported":["sub","iss","auth_time","name","given_name","family_name","preferred_username","email"],"claim_types_supported":["normal"],"claims_parameter_supported":false,"scopes_supported":["openid","offline_access"],"request_parameter_supported":true,"request_uri_parameter_supported":true}
The log is attached.

[rpframedebug.zip](https://github.com/pingidentity/mod_auth_openidc/files/744693/rpframedebug.zip)

**Comment by zandbelt** [comment]
Looks like there is no session. You're not supposed to hit the iframe directly. This iframe should only be loaded from a resource that is protected with `AuthType openid-connect` so an authenticated session for the user exists and it is clear from which Provider to pull the iframe (namely the one that authenticated the user).

**Comment by security4java** [comment]
The attached log using the session from a browser.
I included frames in index.htm and it is protected by `AuthType openid-connect`
I can access to all protected URLs after OIDC authentication.
What I miss?



[rpframedebug_short.zip](https://github.com/pingidentity/mod_auth_openidc/files/744725/rpframedebug_short.zip)

**Comment by zandbelt** [comment]
That log doesn't show that the iframe is pulled at all.

It would also be helpful to provide the complete log, from startup, initial access of index.html, redirect & authenticate at Keycloak and receiving the response all the way to the now authenticated user accessing index.html with a valid session and subsequently pulling the iframes from that same session.

**Comment by security4java** [comment]
The log is attached
[rpframedebug4.zip](https://github.com/pingidentity/mod_auth_openidc/files/744775/rpframedebug4.zip)

**Comment by zandbelt** [comment]
The crux is in:

`[Wed Feb 01 14:12:54 2017] [debug] src/mod_auth_openidc.c(1556): [client 192.168.111.33] oidc_save_in_session: session management disabled: session_state ((null)) and/or check_session_iframe (https://localhost/auth/realms/realm/protocol/openid-connect/login-status-iframe.html) is not provided, referer: https://192.168.110.2/auth/realms/realm/protocol/openid-connect/auth?response_type=code&scope=openid&client_id=st_httpd_192.168.110.2&state=i1YQ39FbBLSCTRyIgEN-F9CdDH4&redirect_uri=https%3A%2F%2F192.168.110.2%2Fprotected%2Fredirect_uri&nonce=0VJ7AO-QBaxVaUBL9goen7muN4Oka1dP_1iPEQ43o-M
`

which says that session management is disabled because the Provider did not return a `session_state` parameter in the authentication response (which in its turn can be verified via the `referer` URL in the same log entry) as the spec dictates:
https://openid.net/specs/openid-connect-session-1_0.html#CreatingUpdatingSessions

So it looks like you may have to explicitly enable session management on the Provider side for your Client so that it starts returning `session_state` in the authentication responses.

**Comment by zandbelt** [comment]
Any luck there?

**Comment by security4java** [comment]
Sorry for the delay.
I have described the problem to Keycloak.
Probably it is Keycloak bugs - I will update when I will have an issue number.

**Comment by security4java** [comment]
The update from Keycloak: It was fixed as part of https://issues.jboss.org/browse/KEYCLOAK-4338.
