### ISSUE TITLE
http for OIDCOAuthIntrospectionEndpoint

### ISSUE THREAD

**Issue by malishahi** [pingidentity/mod_auth_openidc#224]
Hi

My keycloak installation does not support HTTPs. Could apache configuration be done to address this issue?
 
Currently, apache complains about that OIDCOAuthIntrospectionEndpoint

**Comment by zandbelt** [comment]
Sending bearer tokens over non-HTTPs channels is insecure and against the spec, hence not supported. You could modify the code to support this but I'd rather advise you to put your server on HTTPs.

**Comment by malishahi** [comment]
Thanks for the note.

Is the following apache configration valid in order to recieve an access_token and send it to KeyCloak for validation?

<VirtualHost *:80>
ServerName orion.waziup.io
OIDCOAuthSSLValidateServer Off
OIDCOAuthClientID orion-cli
OIDCOAuthClientSecret 060be8ce-1a65-49ce-8939-48d2dc29ea4c
OIDCOAuthIntrospectionEndpoint https://aam.waziup.io/auth/realms/waziup/protocol/openid-connect/token/introspect
OIDCOAuthIntrospectionEndpointAuth client_secret_basic
OIDCOAuthIntrospectionEndpointMethod POST
OIDCOAuthRemoteUserClaim audience
OIDCOAuthIntrospectionTokenParamName access_token
#OIDCOAuthVerifyJwksUri https://aam.waziup.io/auth/realms/waziup/protocol/openid-connect/certs

<Location />
   Authtype oauth20
   Require valid-user
   LogLevel debug
</Location>

**Comment by zandbelt** [comment]
I'm not familiar with the token introspection protocol/message-format that Keycloak expects but by what I gather from https://github.com/keycloak/authorization_services_guide/blob/master/topics/service/protection/token-introspection.adoc it needs `OIDCOAuthIntrospectionTokenParamName token` and `OIDCOAuthIntrospectionEndpointParams token_type_hint=requesting_party_token`.

**Comment by malishahi** [comment]
Thanks a lot for the note Hans.

I have not yet configured https, but I was trying to see what are the reponses from curl commands.
Is this problem due to not having ssl (https)?

(SSL received a record that exceeded the maximum permissible length.)
[Mon Feb 06 16:54:54.135741 2017] [auth_openidc:error] [pid 53] [client 10.32.0.78:48230] oidc_oauth_resolve_access_token: could not get a validation response from the Authorization server

---------curl command output

*   Trying 217.77.95.68...
* Connected to orion.waziup.io (217.77.95.68) port 80 (#0)
> POST /v1/data/ HTTP/1.1
> Host: orion.waziup.io
> User-Agent: curl/7.47.0
> Accept: */*
> Content-Type: application/x-www-form-urlencoded
> Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJDck9tNzhpWkVyWGdXeEs5MzVxNEdHRmp3ak1mdENQX01IenhBWHo5OUswIn0.eyJqdGkiOiI2YmE4MTUwNC0xNGNhLTQyYjAtYjljNC0xNzkwMDJlYTA4ODUiLCJleHAiOjE0ODY0MDA5OTMsIm5iZiI6MCwiaWF0IjoxNDg2NDAwMDkzLCJpc3MiOiJodHRwOi8vYWFtLndheml1cC5pby9hdXRoL3JlYWxtcy93YXppdXAiLCJhdWQiOiJvcmlvbi1jbGkiLCJzdWIiOiJiNmMyMjg0OC00NzVmLTRkN2EtYTAzMC1jOTQxZjEwN2E5YzIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJvcmlvbi1jbGkiLCJhdXRoX3RpbWUiOjAsInNlc3Npb25fc3RhdGUiOiJmMTdkYTU2Mi02MmFlLTQ3MmQtYjgwZi0xZGU3NWQ1NzYxZjAiLCJhY3IiOiIxIiwiY2xpZW50X3Nlc3Npb24iOiIyMTk1MWE5Yi1kYjI0LTQ2NTItOGZlZS01ZWJkNTUyNWM4YjgiLCJhbGxvd2VkLW9yaWdpbnMiOltdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50Iiwidmlldy1wcm9maWxlIl19fSwibmFtZSI6IiIsInByZWZlcnJlZF91c2VybmFtZSI6Indheml1cCJ9.cI_g00WMRe2GQ9vxAu_bb7XlNX89y_9L5Q200E4O8Aj7bVROwmFtzATwnUIC7KD_LVp-AM-L-9Ow-WkKka1IPzCFTnEuenwttzTdGhko7i5e9TAQwGdyL8HruyLegheMwruCUB1Gv4KxWDAe6kC1NqItFIZoqSborP3mzOqcR8CkT50ebX7_eVYOjFz4Oo4XXvk-avYQlOoIY3RAZ2lgBgcyfPJYo3FUxt6qlJFYkFU6Dxx8Canso3OT_w2WyGUyeTUzR-D1uCd7EBycnkR9MmWvEaYATng0oDh1cNZqpJAt64kPzxBFN7eZkNz5W55XfZ9HTrdFGvDl6iiwhfJgFw
> Content-Length: 14
> 
* upload completely sent off: 14 out of 14 bytes
< HTTP/1.1 401 Unauthorized
< Server: nginx/1.11.1
< Date: Mon, 06 Feb 2017 16:54:54 GMT
< Content-Type: text/html; charset=iso-8859-1
< Content-Length: 381
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Methods: POST, GET, OPTIONS
< Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept, Authorization, Fiware-ServicePath, Fiware-Service
< WWW-Authenticate: Bearer error="invalid_token", error_description="Reference token could not be introspected"
< 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>401 Unauthorized</title>
</head><body>
<h1>Unauthorized</h1>
<p>This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.</p>
</body></html>
* Connection #0 to host orion.waziup.io left intact


Apache logs:


[Mon Feb 06 16:54:53.864487 2017] [auth_openidc:debug] [pid 53] src/util.c(677): [client 10.32.0.78:48230] oidc_util_http_get: get URL="https://aam.waziup.io/auth/realms/waziup/protocol/openid-connect/token/introspect?token_type_hint=requesting_party_token&token=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJDck9tNzhpWkVyWGdXeEs5MzVxNEdHRmp3ak1mdENQX01IenhBWHo5OUswIn0.eyJqdGkiOiI2YmE4MTUwNC0xNGNhLTQyYjAtYjljNC0xNzkwMDJlYTA4ODUiLCJleHAiOjE0ODY0MDA5OTMsIm5iZiI6MCwiaWF0IjoxNDg2NDAwMDkzLCJpc3MiOiJodHRwOi8vYWFtLndheml1cC5pby9hdXRoL3JlYWxtcy93YXppdXAiLCJhdWQiOiJvcmlvbi1jbGkiLCJzdWIiOiJiNmMyMjg0OC00NzVmLTRkN2EtYTAzMC1jOTQxZjEwN2E5YzIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJvcmlvbi1jbGkiLCJhdXRoX3RpbWUiOjAsInNlc3Npb25fc3RhdGUiOiJmMTdkYTU2Mi02MmFlLTQ3MmQtYjgwZi0xZGU3NWQ1NzYxZjAiLCJhY3IiOiIxIiwiY2xpZW50X3Nlc3Npb24iOiIyMTk1MWE5Yi1kYjI0LTQ2NTItOGZlZS01ZWJkNTUyNWM4YjgiLCJhbGxvd2VkLW9yaWdpbnMiOltdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50Iiwidmlldy1wcm9maWxlIl19fSwibmFtZSI6IiIsInByZWZlcnJlZF91c2VybmFtZSI6Indheml1cCJ9.cI_g00WMRe2GQ9vxAu_bb7XlNX89y_9L5Q200E4O8Aj7bVROwmFtzATwnUIC7KD_LVp-AM-L-9Ow-WkKka1IPzCFTnEuenwttzTdGhko7i5e9TAQwGdyL8HruyLegheMwruCUB1Gv4KxWDAe6kC1NqItFIZoqSborP3mzOqcR8CkT50ebX7_eVYOjFz4Oo4XXvk-avYQlOoIY3RAZ2lgBgcyfPJYo3FUxt6qlJFYkFU6Dxx8Canso3OT_w2WyGUyeTUzR-D1uCd7EBycnkR9MmWvEaYATng0oDh1cNZqpJAt64kPzxBFN7eZkNz5W55XfZ9HTrdFGvDl6iiwhfJgFw"
[Mon Feb 06 16:54:53.864567 2017] [auth_openidc:debug] [pid 53] src/util.c(514): [client 10.32.0.78:48230] oidc_util_http_call: url=https://aam.waziup.io/auth/realms/waziup/protocol/openid-connect/token/introspect?token_type_hint=requesting_party_token&token=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJDck9tNzhpWkVyWGdXeEs5MzVxNEdHRmp3ak1mdENQX01IenhBWHo5OUswIn0.eyJqdGkiOiI2YmE4MTUwNC0xNGNhLTQyYjAtYjljNC0xNzkwMDJlYTA4ODUiLCJleHAiOjE0ODY0MDA5OTMsIm5iZiI6MCwiaWF0IjoxNDg2NDAwMDkzLCJpc3MiOiJodHRwOi8vYWFtLndheml1cC5pby9hdXRoL3JlYWxtcy93YXppdXAiLCJhdWQiOiJvcmlvbi1jbGkiLCJzdWIiOiJiNmMyMjg0OC00NzVmLTRkN2EtYTAzMC1jOTQxZjEwN2E5YzIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJvcmlvbi1jbGkiLCJhdXRoX3RpbWUiOjAsInNlc3Npb25fc3RhdGUiOiJmMTdkYTU2Mi02MmFlLTQ3MmQtYjgwZi0xZGU3NWQ1NzYxZjAiLCJhY3IiOiIxIiwiY2xpZW50X3Nlc3Npb24iOiIyMTk1MWE5Yi1kYjI0LTQ2NTItOGZlZS01ZWJkNTUyNWM4YjgiLCJhbGxvd2VkLW9yaWdpbnMiOltdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50Iiwidmlldy1wcm9maWxlIl19fSwibmFtZSI6IiIsInByZWZlcnJlZF91c2VybmFtZSI6Indheml1cCJ9.cI_g00WMRe2GQ9vxAu_bb7XlNX89y_9L5Q200E4O8Aj7bVROwmFtzATwnUIC7KD_LVp-AM-L-9Ow-WkKka1IPzCFTnEuenwttzTdGhko7i5e9TAQwGdyL8HruyLegheMwruCUB1Gv4KxWDAe6kC1NqItFIZoqSborP3mzOqcR8CkT50ebX7_eVYOjFz4Oo4XXvk-avYQlOoIY3RAZ2lgBgcyfPJYo3FUxt6qlJFYkFU6Dxx8Canso3OT_w2WyGUyeTUzR-D1uCd7EBycnkR9MmWvEaYATng0oDh1cNZqpJAt64kPzxBFN7eZkNz5W55XfZ9HTrdFGvDl6iiwhfJgFw, data=(null), content_type=(null), basic_auth=orion-cli:060be8ce-1a65-49ce-8939-48d2dc29ea4c, bearer_token=(null), ssl_validate_server=0
[Mon Feb 06 16:54:54.135642 2017] [auth_openidc:error] [pid 53] [client 10.32.0.78:48230] oidc_util_http_call: curl_easy_perform() failed on: https://aam.waziup.io/auth/realms/waziup/protocol/openid-connect/token/introspect?token_type_hint=requesting_party_token&token=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJDck9tNzhpWkVyWGdXeEs5MzVxNEdHRmp3ak1mdENQX01IenhBWHo5OUswIn0.eyJqdGkiOiI2YmE4MTUwNC0xNGNhLTQyYjAtYjljNC0xNzkwMDJlYTA4ODUiLCJleHAiOjE0ODY0MDA5OTMsIm5iZiI6MCwiaWF0IjoxNDg2NDAwMDkzLCJpc3MiOiJodHRwOi8vYWFtLndheml1cC5pby9hdXRoL3JlYWxtcy93YXppdXAiLCJhdWQiOiJvcmlvbi1jbGkiLCJzdWIiOiJiNmMyMjg0OC00NzVmLTRkN2EtYTAzMC1jOTQxZjEwN2E5YzIiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJvcmlvbi1jbGkiLCJhdXRoX3RpbWUiOjAsInNlc3Npb25fc3RhdGUiOiJmMTdkYTU2Mi02MmFlLTQ3MmQtYjgwZi0xZGU3NWQ1NzYxZjAiLCJhY3IiOiIxIiwiY2xpZW50X3Nlc3Npb24iOiIyMTk1MWE5Yi1kYjI0LTQ2NTItOGZlZS01ZWJkNTUyNWM4YjgiLCJhbGxvd2VkLW9yaWdpbnMiOltdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50Iiwidmlldy1wcm9maWxlIl19fSwibmFtZSI6IiIsInByZWZlcnJlZF91c2VybmFtZSI6Indheml1cCJ9.cI_g00WMRe2GQ9vxAu_bb7XlNX89y_9L5Q200E4O8Aj7bVROwmFtzATwnUIC7KD_LVp-AM-L-9Ow-WkKka1IPzCFTnEuenwttzTdGhko7i5e9TAQwGdyL8HruyLegheMwruCUB1Gv4KxWDAe6kC1NqItFIZoqSborP3mzOqcR8CkT50ebX7_eVYOjFz4Oo4XXvk-avYQlOoIY3RAZ2lgBgcyfPJYo3FUxt6qlJFYkFU6Dxx8Canso3OT_w2WyGUyeTUzR-D1uCd7EBycnkR9MmWvEaYATng0oDh1cNZqpJAt64kPzxBFN7eZkNz5W55XfZ9HTrdFGvDl6iiwhfJgFw (SSL received a record that exceeded the maximum permissible length.)
[Mon Feb 06 16:54:54.135741 2017] [auth_openidc:error] [pid 53] [client 10.32.0.78:48230] oidc_oauth_resolve_access_token: could not get a validation response from the Authorization server

**Comment by zandbelt** [comment]
Seems that you're trying to make an SSL connection to a plain HTTP port (80).

**Comment by malishahi** [comment]
I made some progress securing KeyCloak endpoint. I am able to get RPT token using:

rpt_call=`curl -X GET -H "Authorization: Bearer ${access_token}"  "${entitlement_url}"`

but when I'd like to access the protected resource, none of the following curl works.

curl -k -u $username:$pass -H "Authorization: Bearer ${access_token}" --data 'token_type_hint=requesting_party_token&token=${rpt}' http://protected-url/v1/data
curl -k -u $username:$pass -H "Authorization: Basic ${client_secret_base64}" --data 'token_type_hint=requesting_party_token&token=${rpt}' http://protected-url/v1/data

Any hints?
-----------Apache proxy output---------

[Wed Mar 08 15:41:40.408108 2017] [authz_core:debug] [pid 6:tid 139666011412224] mod_authz_core.c(809): [client 10.0.0.10:57116] AH01626: authorization result of Require valid-user : denied (no authenticated user yet)
[Wed Mar 08 15:41:40.408129 2017] [authz_core:debug] [pid 6:tid 139666011412224] mod_authz_core.c(809): [client 10.0.0.10:57116] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[Wed Mar 08 15:41:40.408138 2017] [auth_openidc:debug] [pid 6:tid 139666011412224] src/mod_auth_openidc.c(3047): [client 10.0.0.10:57116] oidc_check_user_id: incoming request: "/v1/data?(null)", ap_is_initial_req(r)=1
[Wed Mar 08 15:41:40.408144 2017] [auth_openidc:debug] [pid 6:tid 139666011412224] src/oauth.c(114): [client 10.0.0.10:57116] oidc_oauth_get_bearer_token: accept_token_in=0
[Wed Mar 08 15:41:40.408147 2017] [auth_openidc:debug] [pid 6:tid 139666011412224] src/oauth.c(125): [client 10.0.0.10:57116] oidc_oauth_get_bearer_token: authorization header found
[Wed Mar 08 15:41:40.408149 2017] [auth_openidc:warn] [pid 6:tid 139666011412224] [client 10.0.0.10:57116] oidc_oauth_get_bearer_token: client used unsupported authentication scheme: /v1/data
[Wed Mar 08 15:41:40.408152 2017] [auth_openidc:debug] [pid 6:tid 139666011412224] src/oauth.c(177): [client 10.0.0.10:57116] oidc_oauth_get_bearer_token: no bearer token found in the allowed methods: []
10.0.0.10 - - [08/Mar/2017:15:41:40 +0000] "POST /v1/data HTTP/1.1" 401 381

**Comment by zandbelt** [comment]
You need to use a(nother) `Authorization: bearer <rpt>` header to pass the access token in a OAuth 2.0 compliant way.

**Comment by malishahi** [comment]
I did your suggestion,but I am getting similar errors:

[Wed Mar 08 16:38:14.300346 2017] [auth_openidc:debug] [pid 93:tid 139666214377216] src/util.c(534): [client 10.0.0.10:38984] oidc_util_http_call: url=https://aam.waziup:8443/auth/realms/waziup/protocol/openid-connect/token/introspect, data=token_type_hint=requesting_party_token&token=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJrQ1BNaEd1dHdhakIzbW93SkI2TkZHTWFNUW5jVDVDN3d2UFdQN3ozbkZzIn0.eyJqdGkiOiJhOGNjYmIxMC1hYTgzLTQ4ZDEtODM0NC1kNThhZjExY2EyMWMiLCJleHAiOjE0ODg5OTEzOTQsIm5iZiI6MCwiaWF0IjoxNDg4OTkxMDk0LCJpc3MiOiJodHRwOi8vYWFtLndheml1cC5nZXJvYml0LmNvbS9hdXRoL3JlYWxtcy93YXppdXAiLCJhdWQiOiJhcGktY2xpZW50Iiwic3ViIjoiZjgyYThlMjctMzZmZS00YWVjLThkMDItMDEzNWI4OWRmMThmIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiYXBpLWNsaWVudCIsImF1dGhfdGltZSI6MCwic2Vzc2lvbl9zdGF0ZSI6IjZiZDk5NDRhLWE3YzYtNDUyMS05MzY0LTA1ZDFmYWQzYzA2MCIsIm5hbWUiOiIiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJzZXJ2aWNlLWFjY291bnQtYXBpLWNsaWVudCIsImVtYWlsIjoic2VydmljZS1hY2NvdW50LWFwaS1jbGllbnRAcGxhY2Vob2xkZXIub3JnIiwiYWNyIjoiMSIsImNsaWVudF9zZXNzaW9uIjoiNzkwMDdkMWUtOTMxYS00ZTU2LTllMDAtMDJjMzM1NzUwMDRmIiwiYWxsb3dlZC1vcmlnaW5zIjpbXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYXBpLWNsaWVudCI6eyJyb2xlcyI6WyJ1bWFfcHJvdGVjdGlvbiJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsInZpZXctcHJvZmlsZSJdfX0sImF1dGhvcml6YXRpb24iOnsicGVybWlzc2lvbnMiOlt7InJlc291cmNlX3NldF9pZCI6ImI5YjI4NWMxLWFiYWMtNGY4YS1iYjI0LTlmNWE0MDA2MzNjYSIsInJlc291cmNlX3NldF9uYW1lIjoiRGVmYXVsdCBSZXNvdXJjZSJ9XX0sImNsaWVudEhvc3QiOiIxMC4wLjAuMTAiLCJjbGllbnRJZCI6ImFwaS1jbGllbnQiLCJjbGllbnRBZGRyZXNzIjoiMTAuMC4wLjEwIn0.E9Lzv23zKiJtFsRnoJ7H9sGqrBJA9O4Zw3EpJsMwgfNY9FtJgrIBrVQpTAj5ZM5UMREuOVDbMtLSXbo8EP4FdQ1tzuPNFrkxLSIoP0RDtHOezzY-xcxpXgb__pxxstwegeePeQrSajxawyUP3VC7MK_D1YGW7oOSoGUAN8hV14xlB8g7BHD23d9uCsM2Do85Fc0XCExwNVc43Y5LV_d9PlHn-2kdJl7xjcJaBXxduOOOQ1c-fRR2v-izfvAYrsz339PyBZvkywnB3F0_032T9jhKc4Hf9D4rhxrbDal4SYdbfW_sk0_wLSRBsiVFQlCFkHImm2TEji7f7NFjrwH4Tg, content_type=application/x-www-form-urlencoded, basic_auth=api-cli:1682dfd0-eb3b-4754-b150-22aa8d895fe0, bearer_token=(null), ssl_validate_server=0
[Wed Mar 08 16:38:14.330365 2017] [auth_openidc:debug] [pid 93:tid 139666214377216] src/util.c(670): [client 10.0.0.10:38984] oidc_util_http_call: HTTP response code=401
[Wed Mar 08 16:38:14.330400 2017] [auth_openidc:debug] [pid 93:tid 139666214377216] src/util.c(675): [client 10.0.0.10:38984] oidc_util_http_call: response={"error":"invalid_request","error_description":"Authentication failed."}
[Wed Mar 08 16:38:14.330443 2017] [auth_openidc:error] [pid 93:tid 139666214377216] [client 10.0.0.10:38984] oidc_util_json_string_print: oidc_util_check_json_error: response contained an "error" entry with value: ""invalid_request""
[Wed Mar 08 16:38:14.330450 2017] [auth_openidc:error] [pid 93:tid 139666214377216] [client 10.0.0.10:38984] oidc_util_json_string_print: oidc_util_check_json_error: response contained an "error_description" entry with value: ""Authentication failed.""
10.0.0.10 - - [08/Mar/2017:16:38:14 +0000] "GET /v1/data/ HTTP/1.1" 401 381

**Comment by Trojan295** [comment]
I encountered a similar problem with Keycloak. The introspect token endpoint support only Basic Auth on the client id and secret. You would need to pass this Basic Auth into the header and in the payload the RPT.

Here's a ticket for it:
https://issues.jboss.org/browse/KEYCLOAK-2293

**Comment by zandbelt** [comment]
Basic authentication to the introspection endpoint is configurable through setting:
`OIDCOAuthClientID <client_id>`
`OIDCOAuthClientSecret <client_secret>`
and
`OIDCOAuthIntrospectionEndpointAuth client_secret_basic`
