### ISSUE TITLE
oidc_util_http_call: curl_easy_perform() failed, in 200 response

### ISSUE THREAD

**Issue by ernsheong** [pingidentity/mod_auth_openidc#227]
Hi there, 

This is related to https://github.com/pingidentity/mod_auth_openidc/issues/218

I've also read and followed as close as possible:
https://github.com/pingidentity/mod_auth_openidc/wiki#17-restricted-web-server-environments

Error:
```
[Tue Feb 14 10:58:13.769248 2017] [auth_openidc:error] [pid 9710:tid 123145307131904] [client ::1:56364] oidc_util_http_call: curl_easy_perform() failed on: https://login.microsoftonline.com/REDACTED.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1_CDSignIn1FA (Content-Length: in 200 response), referer: https://localhost/
[Tue Feb 14 10:58:13.769491 2017] [auth_openidc:error] [pid 9710:tid 123145307131904] [client ::1:56364] oidc_provider_static_config: could not retrieve metadata from url: https://login.microsoftonline.com/REDACTED.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1_CDSignIn1FA, referer: https://localhost/
```

I am puzzled because it says 200 response, but it still fails. Can you help enlighten what is possibly wrong with my configuration?

**Comment by zandbelt** [comment]
Are you using an outgoing proxy in your environment? If so, have you set `OIDCOutgoingProxy`?

**Comment by ernsheong** [comment]
Thank you for your fast reply. Yes there is an outgoing proxy in my environment.

I have tried using:
export http_proxy PROXYPORT:PROXTHOST
export https_proxy PROXYPORT:PROXTHOST

Also tried in httpd.conf:
SetEnv http_proxy "http://PROXYHOST:PROXYPORT"
SetEnv https_proxy "http://PROXYHOST:PROXYPORT"

Also tried:
OIDCOutgoingProxy http://PROXYHOST:PROXYPORT
(not clear if it should be a string, drop the scheme, etc.)

**Comment by zandbelt** [comment]
As the docs say here:
https://github.com/pingidentity/mod_auth_openidc/blob/master/auth_openidc.conf#L651
it should be:
`OIDCOutgoingProxy PROXYHOST:PROXYPORT`

**Comment by ernsheong** [comment]
Unfortunately just not having a luck with all this. Working around by proxying to the PC that works. Thanks

**Comment by zandbelt** [comment]
Could it be that your proxy is an authenticating proxy?

**Comment by ernsheong** [comment]
It's not. I got it to work with a pre-compiled mod_auth_oidc from a colleague. I might have messed up something during the compilation phase 

No need for OIDCOutgoingProxy, just http_proxy and https_proxy.

**Comment by gauravkits** [comment]
How did you fix this?
