### ISSUE TITLE
Make OIDCOAuthRemoteUserClaim Optional

### ISSUE THREAD

**Issue by ryansmith940** [pingidentity/mod_auth_openidc#231]
The OP I am using (Gluu) does not return user information on the `validate_token_endpoint`.  It only returns this:
```json
{
   "valid": true,
   "expires_in": 299
}
```

So validation fails when the AuthType is oauth20 with the error: 
`WWW-Authenticate: Bearer error="invalid_token", error_description="Could not set remote user"`

The message in the log is:
```
[Wed Feb 15 16:55:06 2017] [warn] oidc_oauth_set_remote_user: response JSON object did not contain a "sub" string
[Wed Feb 15 16:55:06 2017] [error] oidc_oauth_check_userid: remote user could not be set, aborting with HTTP_UNAUTHORIZED
```

I'd like to be able to set OIDCOAuthRemoteUserClaim so that authentication does not fail when there isn't any user information in the validate_token_endpoint. It could either leave REMOTE_USER unset, or set it from the user_info or client_info endpoint.

**Comment by zandbelt** [comment]
That is tricky since *something* needs to be set in the remote user internals to indicate that authentication succeeded. Couldn't you just include a hard-configured/coded string value for the claim "sub" in the validation results?

**Comment by zandbelt** [comment]
bump
