### ISSUE TITLE
Make installation user friendly

### ISSUE THREAD

**Issue by vatima2016** [pingidentity/mod_auth_openidc#232]
There is a lot of dependencies, which make installation of the new versions at least for me impossible. This situation considerably reduces adoption probability for this excellent product.

I had a couple of unsuccessful attempts with different vagrant boxes (ubuntu and centos), where mod_auth_openidc requires  at the end an older version of some library (I can provide details later if required) although there is already installed a newer one.

It would be nice to get detailed instructions, for example for the "bento/centos-6.8" or any other vagrant box, ideally with all dependencies provided for download.

**Comment by zandbelt** [comment]
I would have to rely on help of others for all platforms out there. I guess you could write up what exactly the problem is and provide the solution?

**Comment by zandbelt** [comment]
version 2.2.0 uses package naming that is more in line with libcjose0 in the Debian/Ubuntu repositories
