### ISSUE TITLE
Can OIDCProviderIssuer accept multiple Issuers?

### ISSUE THREAD

**Issue by chaumanhui** [pingidentity/mod_auth_openidc#234]
Hi,

We're using mod_auth_openidc to integrate user logon to O365. However, our school has two subscription of O365, one for staff and one for students. We have web applications which assume both students and staff logon. 

The problem is that 

OIDCProviderIssuer can accept only one predefined Issuer.

Can I specify two Issuer in the OIDCProviderIssuer variable, so that logon from two O365 pool can be accepted. 

Thanks, 

cm

**Comment by zandbelt** [comment]
You'll need to adopt the "multi-provider" setup described here:
https://github.com/pingidentity/mod_auth_openidc/#openid-connect-sso-with-multiple-openid-connect-providers

Basically drop the `OIDCProvider*` primitives and use `OIDCMetadataDir` to point to a directory where you store `.provider` and `*.client` metadata/configuration files.

**Comment by chaumanhui** [comment]
Thanks a lot

cm
