### ISSUE TITLE
Forward access Token / ID Token as a JWT

### ISSUE THREAD

**Issue by lucsabathe** [pingidentity/mod_auth_openidc#235]
Dear all, 
In our current setting we have internal applications that are developped to use OIDC as authentication mechanism and we also have to authenticate first the user in our DMZ. In order to do it  we try to use mod_auth_openidc in order to forward OIDC token as a JWT token to our internal app instead of creating a new set of token internally.
So my question : Is it possible to forward access token/id token after proxy authentication with OIDC.
regards
Luc

**Comment by zandbelt** [comment]
Yes, that is possible using `OIDCPassIDTokenAs `, see: https://github.com/pingidentity/mod_auth_openidc/blob/master/auth_openidc.conf#L587

**Comment by zandbelt** [comment]
I trust this works for you.
