### ISSUE TITLE
bad request, size of request header field exceeds servers limit   

### ISSUE THREAD

**Issue by VAnagani** [pingidentity/mod_auth_openidc#236]
I get a bad request error when left the application for a very long time and refresh. 
Here's my situation.
•	The app is left running in a browser tab for a long time (overnight) and when I refresh the page in the morning I see this error "Bad request.bad request size of request header field exceeds server limit"
I see lot of 'mod_aut_openidc_state' cookies in the browser.
How to handle this issue?

Clearing cookies in the browser is a temporary solution but it would be annoying to users.
![openidcerror](https://cloud.githubusercontent.com/assets/8958293/23523834/5e889360-ff56-11e6-9d45-8dbacc7a7b6f.png)

**Comment by VAnagani** [comment]
![openidcerror](https://cloud.githubusercontent.com/assets/8958293/23523817/549d28de-ff56-11e6-85d1-dc8b019bdbcf.png)

**Comment by zandbelt** [comment]
Could it be the same cause as #204, #220, #114 or #214? In any case I'd be interested in the version of mod_auth_openidc and the platform that you run it on. If that's not the latest (2.1.6) release then I'd strongly advise to upgrade and try to reproduce first

**Comment by zandbelt** [comment]
Did an upgrade resolve the issue?

**Comment by VAnagani** [comment]
Yes, Thank you
