### ISSUE TITLE
Everything is null

### ISSUE THREAD

**Issue by malishahi** [pingidentity/mod_auth_openidc#237]
[Sat Mar 04 11:11:29.152724 2017] [authz_core:debug] [pid 84] mod_authz_core.c(809): [client 10.32.0.191:50876] AH01626: authorization result of Require valid-user : denied (no authenticated user yet)
[Sat Mar 04 11:11:29.152868 2017] [authz_core:debug] [pid 84] mod_authz_core.c(809): [client 10.32.0.191:50876] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[Sat Mar 04 11:11:29.152997 2017] [auth_openidc:debug] [pid 84] src/mod_auth_openidc.c(2981): [client 10.32.0.191:50876] oidc_check_user_id: incoming request: "/favicon.ico?(null)", ap_is_initial_req(r)=1
[Sat Mar 04 11:11:29.153031 2017] [auth_openidc:debug] [pid 84] src/util.c(853): [client 10.32.0.191:50876] oidc_util_get_cookie: returning "mod_auth_openidc_session" = <null>
[Sat Mar 04 11:11:29.153115 2017] [auth_openidc:debug] [pid 84] src/util.c(956): [client 10.32.0.191:50876] oidc_util_request_matches_url: comparing "/favicon.ico"=="/redirect_uri"
[Sat Mar 04 11:11:29.153147 2017] [auth_openidc:debug] [pid 84] src/util.c(447): [client 10.32.0.191:50876] oidc_get_current_url: current URL 'http://dashboard.waziup.io:80/favicon.ico'
[Sat Mar 04 11:11:29.153156 2017] [auth_openidc:debug] [pid 84] src/mod_auth_openidc.c(2007): [client 10.32.0.191:50876] oidc_authenticate_user: enter
[Sat Mar 04 11:11:29.153364 2017] [auth_openidc:debug] [pid 84] src/cache/shm.c(158): [client 10.32.0.191:50876] oidc_cache_shm_get: enter, section="provider", key="http%3A%2F%2Faam.waziup.io%2Fauth%2Frealms%2Fwaziup%2F.well-known%2Fopenid-configuration"
[Sat Mar 04 11:11:29.154515 2017] [auth_openidc:debug] [pid 84] src/util.c(514): [client 10.32.0.191:50876] oidc_util_http_call: url=http://aam.waziup.io/auth/realms/waziup/.well-known/openid-configuration, data=(null), content_type=(null), basic_auth=(null), bearer_token=(null), ssl_validate_server=1
[Sat Mar 04 11:11:49.175812 2017] [auth_openidc:error] [pid 84] [client 10.32.0.191:50876] oidc_util_http_call: curl_easy_perform() failed on: http://aam.waziup.io/auth/realms/waziup/.well-known/openid-configuration (Resolving timed out after 5515 milliseconds)
[Sat Mar 04 11:11:49.176010 2017] [auth_openidc:error] [pid 84] [client 10.32.0.191:50876] oidc_provider_static_config: could not retrieve metadata from url: http://aam.waziup.io/auth/realms/waziup/.well-known/openid-configuration
[Sat Mar 04 17:05:44.895067 2017] [authz_core:debug] [pid 85] mod_authz_core.c(809): [client 10.32.0.191:34590] AH01626: authorization result of Require valid-user : denied (no authenticated user yet)
[Sat Mar 04 17:05:44.895302 2017] [authz_core:debug] [pid 85] mod_authz_core.c(809): [client 10.32.0.191:34590] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[Sat Mar 04 17:05:44.895495 2017] [auth_openidc:debug] [pid 85] src/mod_auth_openidc.c(2981): [client 10.32.0.191:34590] oidc_check_user_id: incoming request: "/?(null)", ap_is_initial_req(r)=1
[Sat Mar 04 17:05:44.895573 2017] [auth_openidc:debug] [pid 85] src/util.c(853): [client 10.32.0.191:34590] oidc_util_get_cookie: returning "mod_auth_openidc_session" = <null>
[Sat Mar 04 17:05:44.895671 2017] [auth_openidc:debug] [pid 85] src/util.c(956): [client 10.32.0.191:34590] oidc_util_request_matches_url: comparing "/"=="/redirect_uri"
[Sat Mar 04 17:05:44.895721 2017] [auth_openidc:debug] [pid 85] src/util.c(447): [client 10.32.0.191:34590] oidc_get_current_url: current URL 'http://dashboard.waziup.io:80/'
[Sat Mar 04 17:05:44.895737 2017] [auth_openidc:debug] [pid 85] src/mod_auth_openidc.c(2007): [client 10.32.0.191:34590] oidc_authenticate_user: enter
[Sat Mar 04 17:05:44.896219 2017] [auth_openidc:debug] [pid 85] src/cache/shm.c(158): [client 10.32.0.191:34590] oidc_cache_shm_get: enter, section="provider", key="http%3A%2F%2Faam.waziup.io%2Fauth%2Frealms%2Fwaziup%2F.well-known%2Fopenid-configuration"
[Sat Mar 04 17:05:44.897176 2017] [auth_openidc:debug] [pid 85] src/util.c(514): [client 10.32.0.191:34590] oidc_util_http_call: url=http://aam.waziup.io/auth/realms/waziup/.well-known/openid-configuration, data=(null), content_type=(null), basic_auth=(null), bearer_token=(null), ssl_validate_server=1
[Sat Mar 04 17:05:45.155777 2017] [authz_core:debug] [pid 94] mod_authz_core.c(809): [client 10.32.0.191:34596] AH01626: authorization result of Require valid-user : denied (no authenticated user yet)
[Sat Mar 04 17:05:45.155906 2017] [authz_core:debug] [pid 94] mod_authz_core.c(809): [client 10.32.0.191:34596] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[Sat Mar 04 17:05:45.156017 2017] [auth_openidc:debug] [pid 94] src/mod_auth_openidc.c(2981): [client 10.32.0.191:34596] oidc_check_user_id: incoming request: "/?(null)", ap_is_initial_req(r)=1
[Sat Mar 04 17:05:45.156059 2017] [auth_openidc:debug] [pid 94] src/util.c(853): [client 10.32.0.191:34596] oidc_util_get_cookie: returning "mod_auth_openidc_session" = <null>
[Sat Mar 04 17:05:45.156145 2017] [auth_openidc:debug] [pid 94] src/util.c(956): [client 10.32.0.191:34596] oidc_util_request_matches_url: comparing "/"=="/redirect_uri"
[Sat Mar 04 17:05:45.156178 2017] [auth_openidc:debug] [pid 94] src/util.c(447): [client 10.32.0.191:34596] oidc_get_current_url: current URL 'http://dashboard.waziup.io:80/'
[Sat Mar 04 17:05:45.156187 2017] [auth_openidc:debug] [pid 94] src/mod_auth_openidc.c(2007): [client 10.32.0.191:34596] oidc_authenticate_user: enter
[Sat Mar 04 17:05:45.156394 2017] [auth_openidc:debug] [pid 94] src/cache/shm.c(158): [client 10.32.0.191:34596] oidc_cache_shm_get: enter, section="provider", key="http%3A%2F%2Faam.waziup.io%2Fauth%2Frealms%2Fwaziup%2F.well-known%2Fopenid-configuration"
[Sat Mar 04 17:05:45.156551 2017] [auth_openidc:debug] [pid 94] src/util.c(514): [client 10.32.0.191:34596] oidc_util_http_call: url=http://aam.waziup.io/auth/realms/waziup/.well-known/openid-configuration, data=(null), content_type=(null), basic_auth=(null), bearer_token=(null), ssl_validate_server=1
[Sat Mar 04 17:06:04.915430 2017] [auth_openidc:error] [pid 85] [client 10.32.0.191:34590] oidc_util_http_call: curl_easy_perform() failed on: http://aam.waziup.io/auth/realms/waziup/.well-known/openid-configuration (Resolving timed out after 5513 milliseconds)
[Sat Mar 04 17:06:04.915601 2017] [auth_openidc:error] [pid 85] [client 10.32.0.191:34590] oidc_provider_static_config: could not retrieve metadata from url: http://aam.waziup.io/auth/realms/waziup/.well-known/openid-configuration
[Sat Mar 04 17:06:05.172781 2017] [auth_openidc:error] [pid 94] [client 10.32.0.191:34596] oidc_util_http_call: curl_easy_perform() failed on: http://aam.waziup.io/auth/realms/waziup/.well-known/openid-configuration (Resolving timed out after 5515 milliseconds)
[Sat Mar 04 17:06:05.172942 2017] [auth_openidc:error] [pid 94] [client 10.32.0.191:34596] oidc_provider_static_config: could not retrieve metadata from url: http://aam.waziup.io/auth/realms/waziup/.well-known/openid-configuration
[Sat Mar 04 17:06:05.357724 2017] [authz_core:debug] [pid 95] mod_authz_core.c(809): [client 10.32.0.191:34748] AH01626: authorization result of Require valid-user : denied (no authenticated user yet), referer: http://dashboard.waziup.io/
[Sat Mar 04 17:06:05.357824 2017] [authz_core:debug] [pid 95] mod_authz_core.c(809): [client 10.32.0.191:34748] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet), referer: http://dashboard.waziup.io/
[Sat Mar 04 17:06:05.357845 2017] [auth_openidc:debug] [pid 95] src/mod_auth_openidc.c(2981): [client 10.32.0.191:34748] oidc_check_user_id: incoming request: "/favicon.ico?(null)", ap_is_initial_req(r)=1, referer: http://dashboard.waziup.io/
[Sat Mar 04 17:06:05.357863 2017] [auth_openidc:debug] [pid 95] src/util.c(853): [client 10.32.0.191:34748] oidc_util_get_cookie: returning "mod_auth_openidc_session" = <null>, referer: http://dashboard.waziup.io/
[Sat Mar 04 17:06:05.357911 2017] [auth_openidc:debug] [pid 95] src/util.c(956): [client 10.32.0.191:34748] oidc_util_request_matches_url: comparing "/favicon.ico"=="/redirect_uri", referer: http://dashboard.waziup.io/
[Sat Mar 04 17:06:05.357934 2017] [auth_openidc:debug] [pid 95] src/util.c(447): [client 10.32.0.191:34748] oidc_get_current_url: current URL 'http://dashboard.waziup.io:80/favicon.ico', referer: http://dashboard.waziup.io/
[Sat Mar 04 17:06:05.357952 2017] [auth_openidc:debug] [pid 95] src/mod_auth_openidc.c(2007): [client 10.32.0.191:34748] oidc_authenticate_user: enter, referer: http://dashboard.waziup.io/
[Sat Mar 04 17:06:05.358056 2017] [auth_openidc:debug] [pid 95] src/cache/shm.c(158): [client 10.32.0.191:34748] oidc_cache_shm_get: enter, section="provider", key="http%3A%2F%2Faam.waziup.io%2Fauth%2Frealms%2Fwaziup%2F.well-known%2Fopenid-configuration", referer: http://dashboard.waziup.io/
[Sat Mar 04 17:06:05.358311 2017] [auth_openidc:debug] [pid 95] src/util.c(514): [client 10.32.0.191:34748] oidc_util_http_call: url=http://aam.waziup.io/auth/realms/waziup/.well-known/openid-configuration, data=(null), content_type=(null), basic_auth=(null), bearer_token=(null), ssl_validate_server=1, referer: http://dashboard.waziup.io/

**Comment by zandbelt** [comment]
Yes, just like it is supposed to be. What is the problem?

**Comment by malishahi** [comment]
The problem was not due to module. It was due to connection problem with KeyCloak from Apache.
