### ISSUE TITLE
cjose RPM generation

### ISSUE THREAD

**Issue by hgomez-sonarsource** [pingidentity/mod_auth_openidc#239]
cjose RPM is required from 2.1.3+ and only binary is provided.

 [cjose](https://github.com/cisco/cjose/blob/60b6b6a7de23575388d1988c0066dd3939333da2/platform/centos/build.sh) package chain generate cjose (libs) and cjose-devel (includes) packages, but your package provides both. 

Is it safe to use cjose rpm generation and cjose package with mod_auth_openidc (at least for people who knows well rpm packaging) ?

Thanks

**Comment by zandbelt** [comment]
it is safe to use either variant; just make sure you have version 0.4.1; there's also some distro here: http://rpmfind.net/linux/rpm2html/search.php?query=pkgconfig(cjose) which would also work

**Comment by hgomez-sonarsource** [comment]
Thanks, I was looking for CentOS 7 / Fedora 25 and it was quite simple to adapt to those distros
