### ISSUE TITLE
Access UserInfo object in Single Page Application

### ISSUE THREAD

**Issue by Jharmuth** [pingidentity/mod_auth_openidc#240]
Hello,

currently I am working on a Microservice Architecture where multiple Single Page Applications and REST-APIs should be secured by Apache and mod_auth_openidc. The OP is Keycloak in my case.
None of the SPAs should be available before login The SPAs only get loaded after successfull login and redirect.
Now my current setup works good, but in my Single Page Apps I need to have the UserInfo of the currently logged in user to handle client-side authorization. The question is, how can I get the UserInfos (similar to OpenID UserInfo-Endpoint) from the mod_auth_openidc session in the proxy? I saw that with this I can get the access_token:

`Header set OIDC_access_token "%{OIDC_access_token}e" env=OIDC_access_token`

but I dont want to expose the access_token to the client. I want the clients to only have the UserInfo-Object. Is there a similar approach for getting the UserInfos only?
I saw that with the upcoming 2.2.0 release this is much easier, but it would be great to have a fallback solution for now.

Thank you very much!

**Comment by zandbelt** [comment]
The fallback today would be to either:
a) set individual claims in individual headers just like the access token example have
b) include the claims in the id_token itself and expose its claims through `OIDCPassIDTokenAs payload` in an environment variable `OIDC_id_token_payload` and subsequently set those in a response header again

**Comment by zandbelt** [comment]
FWIW: I would appreciate it if people could test the 2.2.0rc3 release from:
http://mod-auth-openidc.org/download/?C=M;O=D

it has a changed (name) dependency on libcjose0 and libjq now; for some docs see also the ChangeLog on the "feature" branch here:

https://github.com/pingidentity/mod_auth_openidc/blob/feature/ChangeLog

**Comment by Jharmuth** [comment]
Thanks for your help! If I set the OIDC_id_token_payload in a Header like this,

`Header set userinfo "%{OIDC_id_token_payload}e"`

I inevitably get all claims/attributes from the id_token in the Header as JSON. There is no way to get only a subset, am I right?

**Comment by zandbelt** [comment]
Having a subset is also a 2.2.x feature... You could take the approach of setting individual headers or just modify the OP side to issue less claims to this client.
