### ISSUE TITLE
Optionally configure Header Name for OAuth Resource Server

### ISSUE THREAD

**Issue by mdan1eli** [pingidentity/mod_auth_openidc#241]
When using header asbabvehicle for the token, would be great to be able to specify a custom name to not conflict with many cli tools which use own bearer or basic auth.n. schemes.  What we try to achieve is a perimeter authorization for external users with https based cli tools.  Ever considered?

**Comment by zandbelt** [comment]
I guess those https cli tools should either speak standard OAuth 2.0 or avoid abusing the header name standardized by OAuth 2.0 "Authorization: bearer" for their own purpose. I don't see why a client would present a standard OAuth 2.0 bearer token - which is the only token accepted by mod_auth_openidc - in a non-standard way.

Moreover you should be able to separate paths protected by other means from paths protected by mod_auth_openidc to avoid header collusion.

Having said all that, there's a way to pass it in a Cookie, which is non standard, see:
https://github.com/pingidentity/mod_auth_openidc/blob/master/auth_openidc.conf#L316
