### ISSUE TITLE
Request_URI environment variable behaving oddly

### ISSUE THREAD

**Issue by sysadmin1139** [pingidentity/mod_auth_openidc#242]
The compounding factor here is that we're using mod_php, which complicates the code-path.

The problem we're trying to solve is to find a way to allow certain PHP routes, not files, to bypass the auth restrictions on the directory. This module has been working for us for some time, but we need to make some changes. Here is a significant `<Directory>` entry:

```apache
<Directory "/opt/homeapp/web">
  AuthType openid-connect
  # File
  SetEnvIf Request_URI "^/(callbacks.php.*)$" allow
  # Route
  SetEnvIf Request_URI "^/oauth/(.*)$" allow
  # CatchAll
  SetEnvIf Request_URI "(.*)" test_uri=$1

  require claim hd:example.com
  require env allow
  require valid-user
</Directory>
```

We're setting some environment variables on a specific file, and allowing it to bypass the OIDC require. This works for files. It doesn't work for routes. The `test_uri` env-var is used to capture the state of Request_URI at the time of the SetEnvIf statement.

To trace this, I modified the LogFormat to add `%{Request_URI}e %{test_url}e` at the end of our log-lines, to see what they get logged as. This works, and I was able to see a difference.

    127.0.0.1 - - [17/Mar/2017:19:04:33 +0000] "GET /oauth/token HTTP/1.1" 400 68 "-" "curl/7.35.0" /oauth/token /index.php
    127.0.0.1 - - [17/Mar/2017:19:05:08 +0000] "GET /oauth/token HTTP/1.1" 302 631 "-" "curl/7.35.0" - /index.php

The first line here was done with the `AuthType` and `require` statements commented out. You can see that `Request_URI` is set to `oauth/token`, and test_uri is set to `/index.php`. When I uncomment, we get the OIDC redirect (302 status code); `Request_URI` is unset, which is why it shows up as `-`. `test_uri` is still set to `/index.php`.

Either way, we can't use the `SetEnvIf` trick for routes. It could be that Apache normally doesn't preserve Request_URI when it's issuing a 30x redirect, but this still seems like a bug.

**Comment by zandbelt** [comment]
I don't think I follow. Why not use separate `<LocationMatch>` directives and include the ones for the File and Route paths before the CatchAll?

**Comment by sysadmin1139** [comment]
In my experience, `LocationMatch` hasn't ever matched a route. Take this:

```apache
    <LocationMatch "^/(editor|oauth)/">
      SetEnv test_uri "oauthing"
    </LocationMatch>

    <Location "/oauth/">
      SetEnv test_uri "MatchRoute"
    </Location>

    <Location "/">
      SetEnv test_uri "MatchIndexing"
    </Location>


    <Directory "/opt/homeapp/web">
      # Require info as before
    </Directory>
```

What I get in the logging when attempting to hit '/callback.php', is "MatchIndexing". When I do a route, such as `/oauth/token` that value is unset by the time it gets to logging.

However, when I comment out the `AuthType` and `Require` lines in the `Directory` statement, hitting `/oauth/token` now returns "MatchIndexing". The `AuthType openid-connect` statement does seem to modify the environment enough that these matches no longer function.

**Comment by zandbelt** [comment]
`Directory` is interpreted before `Location`. What if you use `Location`/`LocationMatch` everywhere and get rid of `Directory` primitives?

**Comment by sysadmin1139** [comment]
So I tested this...

```apache
    <LocationMatch "^/(editor|oauth)">
      SetEnv test_uri "editing"
    </LocationMatch>

    <Location "/oauth/">
      SetEnv test_uri "MatchRoute"
    </Location>

    <Location "/">
      SetEnvIf Request_URI "index.php$" test_uri=MatchIndex
      SetEnvIf Request_URI "(.*)" test_uri=root_$1
      # AuthType openid-connect
      # require claim hd:example.com
      # require valid-user
    </Location>
```

Hitting this with `/oauth/token`, gives me test_uri of `MatchIndex`. This suggests that Request_URI is set to `index.php` at the stage of processing where the `Location` directives are handled.

Changing it to remove the comments:

```apache
    <LocationMatch "^/(editor|oauth)">
      SetEnv test_uri "editing"
    </LocationMatch>

    <Location "/oauth/">
      SetEnv test_uri "MatchRoute"
    </Location>

    <Location "/">
      SetEnvIf Request_URI "index.php$" test_uri=MatchIndex
      SetEnvIf Request_URI "(.*)" test_uri=root_$1
      AuthType openid-connect
      require claim hd:example.com
      require valid-user
    </Location>
```

**Comment by zandbelt** [comment]
I'm not sure what to conclude here. Remember that the *authentication phase*, which included the redirect that mod_auth_openidc does, is triggered *before* SetEnvIf does its work. The *authorization* phase -  i.e. executing the Required directives - happens in a later phase, after the claims have been set by mod_auth_openidc and the SetEnvIf commands have been executed.

If you want to exclude locations from authentication you can do that using ordered Location directives, it wouldn't work by setting environment variables as you can conclude from the above.

I'm just trying to wrap my head around what you want to achieve and provide some alternatives. I don't actually see a a bug up to now.

**Comment by zandbelt** [comment]
Seems I got my wires crossed on the ordering earlier, it should be reversed: most specific last. So I believe you should be able to sort this out with:

```
<Location /protected/allow>
        Require all granted
</Location>

<Location /protected>
       AuthType openid-connect
       Require valid-user
</Location>
````
etc.

**Comment by sysadmin1139** [comment]
After much back and forth, I was able to figure out a way to get the behavior I need. It isn't elegant, and `Location` set to anything other than root simply never worked for any route. Whatever data `Location` and `LocationMatch` check against, is already rewritten to `index.php` by the time they execute. However, an [Expression](https://httpd.apache.org/docs/current/expr.html) worked.

```apache
    <Location "/">
        <If "%{THE_REQUEST} =~ m#[GET|POST] /oauth#" >
          SetEnvIf Request_URI "(.*)" allow
        </If>
         SetEnvIf Request_URI "^/(callbacks.php.*)$" allow
         AuthType openid-connect
         require claim hd:example.com
         require env allow
         require valid-user
    </Location>
```

This takes advantage of an Apache Expression matching on `THE_REQUEST`, which is the full request, including verb and query-string if any. Unlike `REQUEST_URI` it doesn't seem to get rewritten by whatever is rewriting it for the SetEnvIfs.

**Comment by zandbelt** [comment]
I believe the rewriting to index.php originates from other Apache settings like `DirectoryIndex` that may be enabled or disabled on specific locations/routes.

This seems to be an Apache config issue and I would like people to try my earlier suggestion before reverting to the solution that you provide :-|

Nevertheless thanks for reporting and helping out. 👍
