### ISSUE TITLE
The state cookie set without HTTPonly and SECURE flags during the authentication

### ISSUE THREAD

**Issue by security4java** [pingidentity/mod_auth_openidc#244]
The state cookie set without HTTPonly and SECURE flags during the authentication please find the attached image.
Please note that upon the successful authentication the state cookie cleaned with HTTPonly and SECURE flags
![cookienotsecured](https://cloud.githubusercontent.com/assets/1451975/24081127/6b06c9b0-0cb5-11e7-89fd-1b67693cde7d.JPG)

**Comment by zandbelt** [comment]
You're looking at the **request** `Cookie` header that is sent from the browser instead of the `Set-Cookie` header that was used to set the state cookie earlier, just like the `Set-Cookie` **response** headers in your screenshot.

**Comment by security4java** [comment]
Yes, Correct!
