### ISSUE TITLE
The “Bad Request” error appears

### ISSUE THREAD

**Issue by security4java** [pingidentity/mod_auth_openidc#245]
After the successful authentication during normal work unfortunately the “Bad Request” error appears

```
Bad Request
Your browser sent a request that this server could not understand.
Size of a request header field exceeds server limit.
Cookie
/n

```

Unfortunately I have log only the error level (and not in the debug).
I do not understand why I see in the log “oidc_clean_expired_state_cookies: state has expired”
I supposed that state is used only for the authentication.

[ssl_error_log.zip](https://github.com/pingidentity/mod_auth_openidc/files/854181/ssl_error_log.zip)

**Comment by security4java** [comment]
We have in our deployment CGI application that deployed in Apache and Java application deployed in Tomcat.
Therefore we have separate configuration for root and for the application.
Do you see any problems with the configuration below (the full is attached):

```
<Directory />
    Deny from all
	Allow from localhost
    Order Deny,Allow
    AuthType openid-connect
    Require valid-user
	AllowOverride None
    Satisfy any
    Options None FollowSymLinks    
</Directory>
ProxyPass        /application1 http://localhost:8080/application1
ProxyPassReverse /application1 http://localhost:8080/application1

<Location /application1>
    Deny from all
    Order Deny,Allow
    AuthType openid-connect
    Require valid-user
    Satisfy any
    Options None FollowSymLinks
     RequestHeader set X-Remote-User  %{OIDC_CLAIM_preferred_username}e
</Location>

```
[conf.zip](https://github.com/pingidentity/mod_auth_openidc/files/857738/conf.zip)

**Comment by zandbelt** [comment]
I don't necessarily see a problem with that config but it may depend on the client. Most often one would see state cookies pile up if there's a large number of parallel unauthenticated requests coming from a Javascript client.

**Comment by zandbelt** [comment]
Any update on this?

**Comment by security4java** [comment]
We have reproduced the same problem in UI but we have different error in log.
```
[Wed Mar 29 13:19:20 2017] [debug] protocol.c(705): [client 192.168.111.22] (28)No space left on device: Failed to read request header line Cookie: KC_RESTART=eyJhbGciOiJIUzI1NiIsImtpZCIgOiAiZGJkNjRlOWI
tYzcwOC00ZGI5LThlOWYtZGZkNTU2ZTE2NzEyIn0…. 
```
Please find the attached log in the debug level.

We will happy for the clarification regarding the RP behavior:
How RP consider these configurations?
As the same applications?
Do we have same tokens for both configurations?

I mean if client access “application1” URLs will it affect the token on the root configuration?

```
<Directory />
    
    AuthType openid-connect
    
</Directory>

ProxyPass        /application1 http://localhost:8080/application1
ProxyPassReverse /application1 http://localhost:8080/application1
<Location /application1>
    
    AuthType openid-connect
    
</Location>
```
[ssl_error_log.zip](https://github.com/pingidentity/mod_auth_openidc/files/884893/ssl_error_log.zip)

**Comment by zandbelt** [comment]
The log shows that **after** the user logs out, a number of requests comes in to Javascript resources:
````
/application1/javax.faces.resource/richfaces-event.js.faces
/application1/javax.faces.resource/tufin/ui/js/blank.js.faces
/application1/js/modal.js
/application1/js/jquery.blockUI.js
/application1/js/jquery.jscrollpane.min.js
/application1/js/jcarousel.min.js
/application1/js/jtooltip.min.js
/application1/js/tufin.js?build=0
/application1/js/tufin.unsaved.js?build=0
/application1/javax.faces.resource/tree.js.faces?ln=org.richfaces
````
each of these requests generates a redirect to the Provider with a unique state cookie, hence the Cookie header limit is exceeded. Maybe those resources are loaded from the loggedout page, maybe there's another tab open that keeps polling those resources.

So either you should reorganize your Javascript code so it does not load those resources after logout, or you can use `OIDCUnAuthAction 401` on the `/application1/js` and `/application/javax*` paths, see https://github.com/pingidentity/mod_auth_openidc/wiki/Cookies#cookie-exceeds-size-limit to prevent those redirects to happen.

**Comment by security4java** [comment]
Thanks,
How RP consider our configurations?
As the same applications?
Do we have same tokens for both configurations?

I mean if client access “application1” URLs will it affect the token on the root configuration?

**Comment by zandbelt** [comment]
yes, there's only one session, created by a single login

**Comment by security4java** [comment]
We will happy for couple of clarifications related to https://github.com/pingidentity/mod_auth_openidc/wiki/Cookies#tldr
1)	If we use file storage (`OIDCCacheType file`) should we apply` X-Requested-With: XMLHttpRequest`?
2)	Can we apply `OIDCUnAuthAction 401` using `LocationMatch` like in the example below?

```
<LocationMatch "\.(js)$">
 OIDCUnAuthAction 401
</LocationMatch
```

**Comment by zandbelt** [comment]
1. the cache/storage type is independent of the interpretation of the`X-Requested-With: XMLHttpRequest` header
2. yes, but I believe the order of Location/LocationMatch directives matters

**Comment by security4java** [comment]
Thanks,
I guess `OIDCUnAuthAction 401` should be after `AuthType openid-connect`.
Correct?

**Comment by security4java** [comment]
Unfortunately, the problem is back again.
We have added to the configuration the following: 

```
<LocationMatch "\.(js|faces)$">
 OIDCUnAuthAction 401
</LocationMatch>

```
What we missed in our configuration?
The logs are attached.
[ssl_error_log.zip](https://github.com/pingidentity/mod_auth_openidc/files/992356/ssl_error_log.zip)
