### ISSUE TITLE
client-cookie logout not working

### ISSUE THREAD

**Issue by Jharmuth** [pingidentity/mod_auth_openidc#246]
Hello,

I am working on a Single Page Application and use mod_auth_openidc on my reverse proxy. Now the login is working fine. I use

`OIDCSessionType client-cookie`

to prevent a stateful proxy. The problem that I have is, that the logout mechanism is not working as expected with this setting. For logout I redirect to http://localhost/xxx/redirect_uri?logout=http%3A%2F%2Flocalhost. The redirect works and now I see the apache default page. Also the session in Keycloak (OP that I use) is removed for the user. But if I access the application again, the old session gets restored somehow (I dont need to login). What confuses me is, that the initial page-load of my app after logout does not contain a session-cookie, but mod_auth_openidc can restore the session nevertheless.
If I use

`OIDCSessionType server-cache`

logout works as expected (login is required to access app after logout).
Any idea what is the problem here and how I can solve it?

Thank you!

**Comment by zandbelt** [comment]
please attach a sever debug log and a browser trace of the `client-cookie` event

**Comment by Jharmuth** [comment]
This should be debug-log:

[error_logout.txt](https://github.com/pingidentity/mod_auth_openidc/files/854481/error_logout.txt)

**Comment by zandbelt** [comment]
it depends on your browser; for Firefox there's e.g. Live Headers, for IE there's Fiddler etc.

**Comment by zandbelt** [comment]
it appears that indeed when `OIDCSessionType client-cookie` is used and cookies are chunked because of the size, those cookies wouldn't correctly be cleared; that is fixed in the commit above on the "feature" branch, to be released in 2.2.0; as a workaround today you could try and minimize the number of claims that end up in the session so the cookie does not need to be chunked

**Comment by Jharmuth** [comment]
Thanks for your response! I will try to limit the claims or find a workaround until 2.2.0 is released
