### ISSUE TITLE
mod_auth_openidc.so: undefined symbol: CJOSE_HDR_KID

### ISSUE THREAD

**Issue by Bharaths1** [pingidentity/mod_auth_openidc#247]
Hi,

    I have compiled openidc from src "mod_auth_openidc-2.1.6.tar" and build was successful.
   when i try to start apache i am getting following error,
    tried in REHL 5.4 and 6.0 - 64 bit (both same error).
Apache2.2.21 64 bit.
openssl-1.0.2g
cjose-0.4.1
jansson-2.8
hiredis-0.13.3

Error:
httpd: Syntax error on line 90 of /local/oidc/apache2.2-oidc/conf/httpd.conf: Cannot load /local/oidc/apache2.2-oidc/modules/mod_auth_openidc.so into server: /local/oidc/apache2.2-oidc/modules/mod_auth_openidc.so: undefined symbol: CJOSE_HDR_KID

Please provide me suggestion.

**Comment by 4dz** [comment]
Hi,

What a coincidence!

I had this problem just today.  Took me ages to get everything to compile on RHEL5, and I had to edit the source code to remove support for memcache.

This is the code I added to the .conf files to get the module to load,

 ```
LoadFile /usr/local/lib/libjansson.so
LoadFile /usr/local/lib/libcjose.so
LoadModule auth_openidc_module modules/mod_auth_openidc.so
```

I also added symbolic links into /lib64

```
cd /lib64
sudo ln -s /usr/local/ssl/lib/libssl.so.1.0.0
sudo ln -s /usr/local/ssl/lib/libcrypto.so.1.0.0
```

**Comment by zandbelt** [comment]
It looks like the Apache runtime cannot find the cjose shared library. You'll need to make sure that it exists in the default library path that Apache searches, or you'll need to add it to that path, as documented here: http://serverfault.com/questions/424997/how-to-set-ld-library-path-on-vps-red-hat-linux-to-be-visible-by-apache

**Comment by zandbelt** [comment]
Did that help?

**Comment by Bharaths1** [comment]
Hi Adam Perry,

     Yes as per your guidaness i have added loadfiles then i can able to start apache server. Thanks much!.
Hi Zandbelt,

Adding libraries won't work in this case i tried that it was not starting apache. Thanks for suggestion.

**Comment by zandbelt** [comment]
That works indeed for those who prefer including hardcoded paths in LoadFile statements over a search path.
