### ISSUE TITLE
OpenID Connect Provider error: server_error No value found for required attribute claim sub

### ISSUE THREAD

**Issue by Bharaths1** [pingidentity/mod_auth_openidc#248]
Hi Team,
 
        I have built mod_auth_openid from src 2.6.1(latest) all work fine but when i hit the URL after authenticating my credentials successfully i am getting following error message please guide me.
Also tried with and without SSL both providing same message.
REHL 5.4 and 6.0 - 64 bit (both same message).
Apache2.2.21 64 bit.
openssl-1.0.2g
cjose-0.4.1
jansson-2.8
hiredis-0.13.3 
Error:

OpenID Connect Provider error: server_error
Description:

No+value+found+for+required+attribute/claim+'sub'+in+the+mapped+user+info+attributes:+{}

**Comment by zandbelt** [comment]
That looks like a message from your Provider saying that there's a problem with gathering the information to put in to the set of claims returned from the user info endpoint. You'll have to solve this on the Provider side.

**Comment by zandbelt** [comment]
Any luck looking at the Provider side?
