### ISSUE TITLE
OIDCStateCookiePrefix configurable

### ISSUE THREAD

**Issue by hgomez-sonarsource** [pingidentity/mod_auth_openidc#249]
I'm using mod_auth_openidc 2.1.6 on CentOS 7 to protect a bunch of VHost and all of them generate mod_auth_openidc_state_ 

Could it be possible to have OIDCStateCookiePrefix configurable so each VHost would use its own state cookie ?

**Comment by zandbelt** [comment]
The state cookies are unique anyway because they get postfixed with a random identifier. Moreover, the cooke Domain setting makes them specific for a domain/host. Why would you want to achieve with a configurable prefix?

**Comment by hgomez-sonarsource** [comment]
To be able to hunt issues I have today with 5 VHost protected by mod_auth_openidc.
But you mention, Domain setting makes them specific for a domain/host, and it could be my issue, since I used same OIDCCookieDomain configuration for many sites

**Comment by zandbelt** [comment]
I don't see now the name of the cookies could be an issue since they're unique anyway. But indeed debugging could be done based on the Domain setting.
