### ISSUE TITLE
Compatibility with Office365 / Azure AD

### ISSUE THREAD

**Issue by solsson** [pingidentity/mod_auth_openidc#250]
Has anyone tested authentication for users in an Office 356 organization? If not, I will have to start from scratch :) It is reportedly compliant with OpenID Connect.

**Comment by zandbelt** [comment]
See here https://github.com/pingidentity/mod_auth_openidc/wiki/Useful-Links 2nd section on Azure AD.

You should be able to use:
````
OIDCProviderMetadataURL https://sts.windows.net/<tenant-id>/.well-known/openid-configuration
````
