### ISSUE TITLE
add hook to explicitly refresh userinfo claims

### ISSUE THREAD

**Issue by istvano** [pingidentity/mod_auth_openidc#251]
Hi,

I think I found a bug in the module.

We are using keycloak but I am sure with an other identity provider it would be the same problem

Steps to reproduce

- user logs in
- access token is received containing user attributes ( first name, last name, locale ( custom user attribute))
- admin logs into identity server and changes the user attribute locale
- we call https://cf.e-change.co/redirect_uri?refresh=our_homepage&access_token=xxxx
- we receive a new access token with the updated user attribute locale

Expected behaviour:
- we should see the http headers reflecting the new attributes from the access token

Actual behaviour:
- attributes are shown from the old access token

unforuntatelly the http header we receive -locale => still shows the value from the old access token.

is this how it is supposed to be ? I though the module should update it's session when it receives a new access token.

Let me know if I am doign something wrong or it is a bug.

**Comment by zandbelt** [comment]
Refreshing an access token, well, refreshes an access token e.g. when it is expired so you can use the new access token from your application to make calls to protected resources. It doesn't update user attributes in a session. That would require calling the userinfo endpoint again. The latter is controlled with `OIDCUserInfoRefreshInterval `, see: https://github.com/pingidentity/mod_auth_openidc/blob/master/auth_openidc.conf#L717

So if you set the appropriate interval, that's all it needs; i.e. no need to refresh the access token explicitly as that will be done, if needed, by the module itself.

**Comment by istvano** [comment]
Hi,

thanks for the update. I see, i guess I am doing the wrong thing to achive my business case.

My problem is the following.

1, user logs in and receives attributes from the identity server
2, the user goes to his account page ( hosted by the identity server ) and changes his details
3, I want those user attributes visibile almost immediatelly to all the applications.

Since the module caches user attributes it takes time until the change becomes visible for the user in the applications. is there an endpoint call on mod_auth_openid that I can call to force the module to refresh user data from the idenity server ?

I can see that I can set the refresh period but the user data hardly ever changes e.g. it is unnecessary to reload user data periodically it would be nice to be able to trigger a refresh externally the same way I can trigger the module to retrieve a new access token.

What do you think ?

Thanks

Istvan

**Comment by zandbelt** [comment]
I do agree there can be value in having a dedicated hook to refresh the claims from the userinfo endpoint. The alternative is to logout and login the user again.

**Comment by istvano** [comment]
Hi, 

Thanks for getting back to me.

At the moment I will be setting the refresh period to something low enough to solve the problem. 

Do you need me to create a separate request to add the hook ?

Kind Regard

**Comment by zandbelt** [comment]
I'll keep this as an enhancement request; also consider my edit about logout/login.

**Comment by istvano** [comment]
Hi,

thanks for this. I think for me the logout is a no-go at the moment. if the user changes their locale I shall not force them to log-in again. so i guess I need to go with the user info api refresh period.

**Comment by zandbelt** [comment]
Not that normally it would not result in a forced login but merely a round-trip to the Provider which triggers SSO because of an existing session that was established in the first run.

**Comment by istvano** [comment]
I am slightly confused. I have the following in my apache config.
	RedirectTemp  /logout https://cf.e-change.co/redirect_uri?logout=outdashboard

and this one always triggers a logout as it shuold. how is calling the redirect_uri directly will create a different behaviour?

**Comment by zandbelt** [comment]
apparently your OP supports OpenID Connect's session management, in that case you'll be logged out and you'd have to switch that off to support this scenario

**Comment by zandbelt** [comment]
Not as as elegant but in your case you could kill the session cookie manually with `Set-Cookie: mod_auth_openidc_session=; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT; Secure; HttpOnly` and redirect to the current page which will force the roundtrip.

**Comment by istvano** [comment]
Hi,

I use keycloak on the OP end.  This sounds like a good plan to me. so if I drop the module session cookie it will force to do a roundtrip. I will check this out.

Thanks for your help on this one !

**Comment by istvano** [comment]
this works well. thanks for this tip.
