### ISSUE TITLE
Reading user identity information from header code on successful openid connect authentication

### ISSUE THREAD

**Issue by gangavh** [pingidentity/mod_auth_openidc#252]
Hi,
 I have done following configuration in Apache HTTPD:

OIDCProviderMetadataURL https://accounts.google.com/.well-known/openid-configuration
OIDCClientID 362933187483-tdskqlu5usd4p60k655985vi26nc88vf.apps.googleusercontent.com
OIDCClientSecret abc
OIDCRedirectURI http://abce.com/secure/index.html
OIDCCryptoPassphrase 2@!4#%&
OIDCScope "openid email"
<Location /secure/>
   AuthType openid-connect
   Require valid-user
</Location>

In scope I have included email. On successful authentication to Google OpenID Authentication, I need to read the email from the openid redirect URL headers which Authorization server is attaching such as code (same pasted below) . How to get the user profile information from the response headers?

/secure/index.html?state=aqA9Vj8GSXPVa9elDyYvwkpsX0U&code=4/oD-OKxM-2QfejxyisDo29DpsDSnb_BDmVD4HOcFCLS4&authuser=0&session_state=95b1b3f3f2b017c907787cf2877eabcc28fba7d9..8cf6&prompt=none

**Comment by zandbelt** [comment]
The callback to the Redirect URI is handled by mod_auth_openidc and not something you should have too look in to. After processing it mod_auth_openidc will set headers that are available to the application. Those are request headers, not response headers. You seem to conflate HTTP headers and URL parameters in to "header code"...

**Comment by gangavh** [comment]
Hi Hans,

 Thanks for the information.
  
  Our use case is typical web application with authentication and session management features - as depicted in the attached flow diagram.
 
 In this context, user session and identity to be managed at Apache HTTPD and send across user identity information to Tomcat application server to process the request. This may mean, Apache is acting as both Relying Party and Resource Server. 

 In this flow, we need access of ID_TOKEN at Apache layer and pass this information to Tomcat application. Please guide how can we achieve this?
 
 thanks
 ganga



![flow](https://cloud.githubusercontent.com/assets/8185302/24780857/aff369a0-1aef-11e7-8c6b-15f98a910570.jpg)

**Comment by zandbelt** [comment]
Please note: the issues list is meant for bug/feature requests; general questions about how the module works should go to the mailing list mod_auth_openidc@googlegroups.com
