### ISSUE TITLE
Maintaining and accessing session and user identity at Apache

### ISSUE THREAD

**Issue by gangavh** [pingidentity/mod_auth_openidc#253]
Hi,

 In continuation of the conversation in https://github.com/pingidentity/mod_auth_openidc/issues/252.

Thanks for the information.

Our use case is typical web application with authentication and session management features - as depicted in the attached flow diagram.

In this context, user session and identity to be managed at Apache HTTPD and sent to Tomcat application server to process the request. This may mean, Apache is acting as both Relying Party and Resource Server.

In this flow, we need access of ID_TOKEN and request object at Apache layer and pass this information to Tomcat application. Please guide how can we achieve this?

thanks
ganga
![flow](https://cloud.githubusercontent.com/assets/8185302/24781841/460a4b8c-1af7-11e7-9ef2-24a9f7228cd0.jpg)

**Comment by zandbelt** [comment]
You can pass the ID token and/or the individual claims from the ID token as headers to Tomcat, see: https://github.com/pingidentity/mod_auth_openidc/blob/master/auth_openidc.conf#L611

**Comment by zandbelt** [comment]
Please note: the issues list is meant for bug/feature requests; general questions about how the module works should go to the mailing list mod_auth_openidc@googlegroups.com
