### ISSUE TITLE
proxy for multi op

### ISSUE THREAD

**Issue by aicochow** [pingidentity/mod_auth_openidc#254]
hello,how can I configure proxy for multi op? 
some vhosts use proxy,but some vhosts(i.e  localhost) do not want to use proxy.

Example
op1:proxy
op2:no proxy

this is my configure

```
OIDCMetadataDir /etc/httpd/conf.d/vhost/auth_openidc_metadata

OIDCOutgoingProxy xxxxxx:xxxx

<Location /multiop/>
   AuthType openid-connect
   Require valid-user
   LogLevel debug
</Location>
```

**Comment by zandbelt** [comment]
By defining multiple vhosts, each vhost would contain a `OIDCOutgoingProxy` or omit it.

**Comment by zandbelt** [comment]
Please note: the issues list is meant for bug/feature requests; general questions about how the module works should go to the mailing list mod_auth_openidc@googlegroups.com
