### ISSUE TITLE
allow oauth2 to authenticate as openID connect with only code response type and no openid scope or id_token

### ISSUE THREAD

**Issue by mikofski** [pingidentity/mod_auth_openidc#257]
There is currently no widely available Apache HTTP server module for authenticating against OAuth2.0 using authorization code grant type, but OAuth2.0 is widely used. This would be very valuable asset for securing static content that is best served directly from Apache HTTP server. IMO `mod-auth-openidc` is the best suited module to accomplish this.

### Expected behaviour
If scope doesn't have `openid` and response type is set to only `"code"` and the provider response doesn't contain `id_token` then assume that the bearer is using OAuth2 and authenticate as in `oauth20` even though `AuthType` is `openid-connect`.

### Actual behaviour
OpenID connect doesn't work with pure OAuth2.0, but OAuth2.0 resource server only authenticates bearers who have already obtained a token and there doesn't seem to be a way to mix the two modes and achieve the expected behavior.

If response type is only "code" then OpenID connect works with OAuth2 provider:
* it creates the correct authorization link, and gets the authorization code with successful user authentication
* it exchanges the authorization code for a bearer token
But then it fails to authenticate the bearer's token because OpenID connect expects `id_token` but Oauth2 only has `access_token`.

### Minimized example that reproduces the behaviour

```
OIDCRedirectURI https://myapp.com/docs/
OIDCCryptoPassphrase passphrase
OIDCProviderIssuer https://myapp.com
OIDCProviderAuthorizationEndpoint https://myapp.com/o/authorize/
OIDCProviderTokenEndpoint https://myapp.com/o/token/
OIDCClientID client-id
OIDCClientSecret client-secret
OIDCScope "read write groups"
OIDCProviderTokenEndpointAuth client_secret_post

Alias /docs/ /home/me/myapp/docs/_build/html/
<Directory /home/me/myapp/docs/_build/html>
AuthType openid-connect
Require valid-user
LogLevel debug
</Directory>
```

**Comment by zandbelt** [comment]
There's a reason for OpenID Connect to exist on top of OAuth 2.0: that's because OAuth 2.0 in itself cannot be used to do Web SSO or user authentication in the way that you suggest.  By implementing a flow like you suggest you'd be open to impersonation attacks. Please see: https://oauth.net/articles/authentication/
