### ISSUE TITLE
Session is closed in the middle of work

### ISSUE THREAD

**Issue by security4java** [pingidentity/mod_auth_openidc#261]
The user start to work on our application and unfortunately was redirected to the login page.
The strange that the login page appears only in the middle of the screen. 
The user work all time so it looks like not related to the session expiration.
We use mod_auth_openidc version "2.1.2" and Keycloak version “2.5.1”
The logs files are attached.
[ssl_error_log.zip](https://github.com/pingidentity/mod_auth_openidc/files/953856/ssl_error_log.zip)

**Comment by zandbelt** [comment]
This may be due to https://github.com/pingidentity/mod_auth_openidc/issues/204; please upgrade to 2.1.6 or newer.

**Comment by zandbelt** [comment]
Did that work?

**Comment by security4java** [comment]
We have upgraded to 2.1.6 and tests it

**Comment by security4java** [comment]
Unfortunately the problem is reproduced.
Please find the attached logs.
We can provide our configuration if required.
[ssl_error_log.zip](https://github.com/pingidentity/mod_auth_openidc/files/961276/ssl_error_log.zip)

**Comment by zandbelt** [comment]
If you take a look at the logs you'll notice that the user or the application triggers some application specific logout URL:
````
[Thu Apr 27 10:46:29 2017] [debug] src/mod_auth_openidc.c(3049): [client clientIP] oidc_check_user_id: incoming request: "/application/logout?expiration=true", ap_is_initial_req(r)=1, referer: https://serverIP/
````
which then results in a logout call to mod_auth_openidc:
````
[Thu Apr 27 10:46:29 2017] [debug] src/mod_auth_openidc.c(3049): [client clientIP] oidc_check_user_id: incoming request: "/protected/redirect_uri?logout=https%3A%2F%2FserverIP%2Flogoff.htm%3Ferror%3DsessionExpired", ap_is_initial_req(r)=1, referer: https://serverIP/
````
which cleans the session cookie:
````
[Thu Apr 27 10:46:29 2017] [debug] src/util.c(852): [client clientIP] oidc_util_set_cookie: adding outgoing header: Set-Cookie: mod_auth_openidc_session=;Path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT;Secure;HttpOnly, referer: https://serverIP/
````
and sends the user to Keycloak for logout:
````
[Thu Apr 27 10:46:29 2017] [debug] mod_proxy_ajp.c(709): proxy: AJP: serving URL ajp://localhost:9009/auth/realms/app-realm/protocol/openid-connect/logout?id_token_hint=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ0YkprekJmZDNsWG56YUkyM0FYU2tSZFk3M00zNXp2U19oOUJrT1hGazVnIn0.eyJqdGkiOiI4MTBiMWMyZC0zM2YyLTQwZTktOTQ2Ny0zOWM0OGJhNmZiOTMiLCJleHAiOjE0OTMyMzM4NzgsIm5iZiI6MCwiaWF0IjoxNDkzMjMzNTc4LCJpc3MiOiJodHRwczovLzEwLjEwMC4xNy4xMC9hdXRoL3JlYWxtcy90dWZpbi1yZWFsbSIsImF1ZCI6InN0X2h0dHBkXzEwLjEwMC4xNy4xMCIsInN1YiI6IjdkM2E0ZWUyLTJmZmQtNDUwZC04ZWViLTlhYzNhN2YxY2U3OCIsInR5cCI6IklEIiwiYXpwIjoic3RfaHR0cGRfMTAuMTAwLjE3LjEwIiwibm9uY2UiOiJLUXRuUlZ4cHE5RU5iNEJqb2g5dllKNHFnMXJxd21wMHFKdDBwMGFOX0dZIiwiYXV0aF90aW1lIjoxNDkzMjMzNTc4LCJzZXNzaW9uX3N0YXRlIjoiMDQzZDA4ZWEtMmZlMi00MWRlLWJlNmEtMGY3NTliOWU3MjMwIiwiYWNyIjoiMSIsIm5hbWUiOiIiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbiNtZnNnMjJsbyJ9.L2ZeANc4ukLIvqYwW_aExFP4iQvD3uwBVTyAWY01QnDAMo5HBCjJrKGLXHFkSaGzkQHBw74tMcaAT9aKLP9WFXrxHYVLWw0aoqiEsGVPpausiN-w3z3u_fIaouQOsj7_4SKdHEKWI70o_NIP6ZXdAFLAQjkGYyDDF-KzlfOEihNEL9KJJ6BiLfSQ3Rcphm_Nd_7We5BgRSrGMbzomNk4dXrxvRaYzvSTIg1FUd2XE0X20gTaa-_UPUIuvEcAaF8Z4RMdYgjtgC_zE4qpAEPECDaSrXdGCkmG1Ibd3Z2suIq2YcYdYwkWSK7090TroCqL6WC_TVIY3uiH4VSvlfkkaA&post_logout_redirect_uri=https%3A%2F%2FserverIP%2Flogoff.htm%3Ferror%3DsessionExpired
````
then Keycloaks sends the user to a "loggedout" page:
````
[Thu Apr 27 10:46:29 2017] [debug] ajp_header.c(599): ajp_unmarshal_response: Header[2] [Location] = [https://serverIP/logoff.htm?error=sessionExpired]
````
So you'll have to debug your application to find out why it feels the session is expired and needs to trigger logout.

Looking at the logs it seems to do some interaction on its own outside of mod_auth_openidc to see if the session is expired:
````
[Thu Apr 27 10:46:21 2017] [debug] src/config.c(1776): [client clientIP] oidc_auth_fixups: overlaying env with 19 elements, referer: https://serverIP/status_frame.htm
...
[Thu Apr 27 10:46:21 2017] [debug] mod_deflate.c(687): [client clientIP] Zlib: Compressed 346 to 193 : URL /cgi-bin/st_get_expiration.cgi, referer: https://serverIP/status_frame.htm
...
[Thu Apr 27 10:46:21 2017] [debug] mod_deflate.c(687): [client clientIP] Zlib: Compressed 153 to 79 : URL /cgi-bin/st.cgi, referer: https://serverIP/
````

**Comment by security4java** [comment]
Unfortunately, the problem is back again without the application expiration functionality. 
Is it bug in mod_auth_openidc?
The logs are attached.
[ssl_error_log.zip](https://github.com/pingidentity/mod_auth_openidc/files/996242/ssl_error_log.zip)

**Comment by security4java** [comment]
Unfortunately, the problem is back again without the application expiration functionality. 
Is it bug in mod_auth_openidc?
The logs are attached.
[ssl_error_log.zip](https://github.com/pingidentity/mod_auth_openidc/files/996798/ssl_error_log.zip)
