### ISSUE TITLE
Support for empty OIDCClaimPrefix

### ISSUE THREAD

**Issue by lawrenceong** [pingidentity/mod_auth_openidc#264]
### Expected behaviour

We want to set **OIDCClaimPrefix** to an empty value, so that there is no prefix whatsoever for the headers being produced.

### Actual behaviour

Setting **OIDCClaimPrefix** to an empty value causes apache to not start up with the following message:

```
AH00526: Syntax error on line 586 of /etc/apache2/mods-enabled/auth_openidc.conf:
OIDCClaimPrefix takes one argument, The prefix to use when setting claims in the HTTP headers
```

### Minimized example that reproduces the behaviour

Set **OIDCClaimPrefix** to an empty value and start apache.

**Comment by zandbelt** [comment]
I agree it shouldn't crash and I should look in to that. 

But having no prefix means that the module cannot distinguish between headers that it should control and headers that are out of its own control. Which means that it cannot scrub headers that it should control, which in its turn means that the application cannot decide whether a header was rightfully set by mod_auth_openidc or manually set by a malicious user/browser.

**Comment by lawrenceong** [comment]
Yup, that is fine.  The idea is indeed to define it in an "allowed" list, as you mentioned in `OIDCAuthNHeader`.

**Comment by zandbelt** [comment]
I'll turn this into a feature request then. I'll accept a PR.

**Comment by zandbelt** [comment]
Looks like Apache does not crash but nicely reports that a value should be provided. So currently it works as expected.

**Comment by lawrenceong** [comment]
@zandbelt You are correct.  I mis-worded it as crash, when it should be, "not start up".  Have updated the bug report.

**Comment by zandbelt** [comment]
My preferred approach would be to leverage the existing primitive `OIDCWhiteListedClaims` https://github.com/pingidentity/mod_auth_openidc/blob/master/auth_openidc.conf#L768 to contain the "controlled" claims that will be scrubbed when `OIDCClaimPrefix` is not defined.

**Comment by lawrenceong** [comment]
Using `OIDCWhiteListedClaims` looks good to me.

When `OIDCClaimPrefix` is not defined, it currently defaults to `OIDC_CLAIM_`.  Should a new boolean parameter be introduced so that when specified will ensure that no default is set, ie empty string?  For example, `OIDCEmptyClaimPrefix`?

**Comment by zandbelt** [comment]
Rather than introducing a new directive I'm looking into a solution where `AP_INIT_RAW_ARGS` is used to parse the arguments rather than `AP_INIT_TAKE1` which requires a non-empty argument.

**Comment by zandbelt** [comment]
added in [2.3.0rc0](https://github.com/pingidentity/mod_auth_openidc/releases/v2.3.0rc0)
