### ISSUE TITLE
The error “Invalid Authentication Response” appears on the screen.

### ISSUE THREAD

**Issue by security4java** [pingidentity/mod_auth_openidc#265]
Probably it is due to fix of https://github.com/pingidentity/mod_auth_openidc/issues/226

We used 2.1.2 and configured the custom error page via OIDCDefaultURL
OIDCDefaultURL https://localhost/logoff.htm?error=longAuthenticationProcess.
In case of the long authentication process we see our custom error.

Recently we upgraded to 2.1.6 and unfortunately in case of the long authentication process we have the following error page:

```
Error: 
Invalid Authentication Response
Description: 
This is due to a timeout; please restart your authentication session by re-entering the URL/bookmark you originally wanted to access: https://<IP>/

```

Can we configure RP to redirect to our custom error and not to show the error page above?

**Comment by zandbelt** [comment]
You can use `OIDCHTMLErrorTemplate ` to handle this error in the way that you want: https://github.com/pingidentity/mod_auth_openidc/blob/master/auth_openidc.conf#L441
