### ISSUE TITLE
Problem with SSO redirect proto_state/cookie adding port number on the end of URL

### ISSUE THREAD

**Issue by matthewm174** [pingidentity/mod_auth_openidc#266]
Hi, I've been facing an issue with using the mod_auth_openidc module for apache.

 Running on apache 2.2.20, we have a loadbalancer in front of our apache. It seems like our URL is being redirected to a messed up form after returning from sso redirect. I've replaced URL with URL and used generic contexts, nonce and timestamp for example purposes.
 
 Breakdown of the issue I'm seeing:
URL.com/Context1/ -> goes to sso, sign in -> returned as URL.com:8000/Context1/

This causes the site to not resolve. I believe this is due to oidc interpreting the x-forwarded-port and adding it onto the url in this chunk of code

```
static const char *oidc_get_current_url_port(const request_rec *r,
	const char *scheme_str) {
	/* first see if there's a proxy/load-balancer in front of us */
	const char *port_str = oidc_util_hdr_in_x_forwarded_port_get(r);
	if (port_str == NULL) {
	/* see if we can get the port from the "X-Forwarded-Host" header */
	const char *host_hdr = oidc_util_hdr_in_x_forwarded_host_get(r);
	if (host_hdr) {
	port_str = strchr(host_hdr, ':');
	if (port_str)
	port_str++;
```

From the debug logs I was able to see potentially where the state was being saved, it seems to happen through OIDC directly. 
	
oidc_get_state_from_cookie: restored JSON state cookie value: {"original_url": "http://URL.com:8000/Context1/Context2/Context3", "original_method": "get", "issuer": "https://****.com/***", "response_type": "code", "nonce": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx", "timestamp": xxxxxxxx}, referer: http://URL.com/Context1/

I noticed this JSON was also held in the array "proto_state"

As well in the logs,
[debug] src/util.c(383): [client *.*.*.*] oidc_get_current_url: current URL 'http://URL:8000/Context1/'
I think this is the actual variable added to the cookie, as it's the first occurrence in the output.

The referer is correct, but the JSON state has the wrong original_url which I believe is inherited by that oidc_get_current_url. It should not contain the port. Is there a way to remove this port or alter our x-forwarded-port so that OIDC will not redirect to the URL+Port?

**Comment by zandbelt** [comment]
It seems your local Apache instance is running on port 8000 and there's a load-balancer in front of it on port 80. In that case the load-balancer should be configured to send the `X-Forwarded-Port` header with a value of `80` (or alternatively you can run the Apache instance on port 443 instead of port 8000). You probably also want to switch to HTTPs at some point.

**Comment by zandbelt** [comment]
see: https://github.com/pingidentity/mod_auth_openidc/wiki#8-how-do-i-run-mod_auth_openidc-behind-a-reverse-proxy
