### ISSUE TITLE
The “Server Error” appears after the successful authentication.

### ISSUE THREAD

**Issue by security4java** [pingidentity/mod_auth_openidc#267]
The “Server Error” appears after the successful authentication.
It happens once and we can not reproduce it again.
I have found this error in the log:

```
[Wed May 03 11:33:34 2017] [error] [client clientIP] oidc_util_http_call: curl_easy_perform() failed on: https://localhost/auth/realms/app-realm/.well-known/openid-configuration (NSS: client certificate not found (nickname not specified))
[Wed May 03 11:33:34 2017] [error] [client clientIP] oidc_provider_static_config: could not retrieve metadata from url: https://localhost/auth/realms/app-realm/.well-known/openid-configuration

```

Please note that we use 
```
OIDCOAuthSSLValidateServer Off
OIDCSSLValidateServer Off

```
The logs in the debug level attached.
[ssl_error_log.zip](https://github.com/pingidentity/mod_auth_openidc/files/972988/ssl_error_log.zip)

The error message is attached: 
![ieerror](https://cloud.githubusercontent.com/assets/1451975/25656341/457694e0-3001-11e7-9b65-757cdc95792a.png)

**Comment by zandbelt** [comment]
fix your curl/ca-certificates installation

**Comment by security4java** [comment]
Can you clarify?
Is the “Server Error” page caused by this error?
`[Wed May 03 11:33:34 2017] [error] [client clientIP] oidc_util_http_call: curl_easy_perform() failed on: https://localhost/auth/realms/app-realm/.well-known/openid-configuration (NSS: client certificate not found (nickname not specified))
`
Why it happens only once?
