### ISSUE TITLE
Clarify documentation / examples for OIDCCryptoPassphrase

### ISSUE THREAD

**Issue by cdman** [pingidentity/mod_auth_openidc#268]
Currently the documentation just mentions `OIDCCryptoPassphrase` in examples, usually like this:

```
OIDCCryptoPassphrase <password>
```

From this I'm left with the question what should I substitute `<password>` with. My understanding is that this is just used to encrypt / sign the cookie set by the module and can be any random value (with the mention that if there are multiple servers which could handle the request - like behind a load-balancer - they all need to have the same value so that they can read each-others cookies), but perhaps it would be good to explicitly document this somewhere (in the README, Wiki, etc).

PS. Thank you for maintaining this module!

**Comment by zandbelt** [comment]
FWIW: there's a line of doc on it here: https://github.com/pingidentity/mod_auth_openidc/blob/master/auth_openidc.conf#L16

**Comment by pieterlukasse** [comment]
I am guessing it should be this one https://packages.debian.org/sid/libapache2-mod-auth-openidc, since my docker image starts with `FROM httpd:2.4` which is based on `FROM debian:stretch-slim`.
