### ISSUE TITLE
Ability to specify audience during authentication 

### ISSUE THREAD

**Issue by stevezau** [pingidentity/mod_auth_openidc#269]
Looking to see how we can specify an audience during authentication?

### Expected behaviour
Able to specify an audience IE:
```
GET https://xxxxxxxx.com/authorize?
  audience=API_IDENTIFIER&
  scope=SCOPE&
  response_type=code&
  client_id=XXXXXXXXXXXX&
  redirect_uri=https://YOUR_APP/callback&
  state=STATE
```

### Actual behaviour
Cannot see an option for this within the wiki.

**Comment by stevezau** [comment]
I guess we can use OIDCAuthRequestParams but should there be a specific parameter for aud?

**Comment by zandbelt** [comment]
`audience` is a non-standard parameter and would necessarily have to be part of `OIDCAuthRequestParams`; also, if you're trying to influence the `aud` setting that is returned in the `id_token` then there' s no defined way to do that; by spec that value would be filled with the `client_id`

**Comment by stevezau** [comment]
@zandbelt thanks, makes sense. will close this
