### ISSUE TITLE
oidc_check_max_session_duration appears after about 10 min after login.

### ISSUE THREAD

**Issue by security4java** [pingidentity/mod_auth_openidc#270]
We use mod_auth_openidc version "2.1.6" and Keycloak version “2.5.1”
We have configured OIDCSessionMaxDuration 43000
Unfortunately the oidc_check_max_session_duration warning appears after about 10 min after login.
The login logs:
```
[Mon May 08 09:47:22 2017] [debug] src/util.c(852): [client clientIP] oidc_util_set_cookie: adding outgoing header: Set-Cookie: mod_auth_openidc_session=c75721af-020c-4cb1-95fd-d12ff399fe98;Path=/;Secure;HttpOnly, referer: https://serverIP/auth/realms/app-realm/protocol/openid-connect/auth?response_type=code&scope=openid&client_id=st_httpd_192.168.2.102&state=4LEohhGikZhoDD6MDHm4xNad9QI&redirect_uri=https%3A%2F%2FserverIP%2Fprotected%2Fredirect_uri&nonce=p7pxhS1SY2hc52RLJ7zK1m15JynGgcIZt9EeVWKZ6uM
[Mon May 08 09:47:22 2017] [debug] src/mod_auth_openidc.c(1888): [client clientIP] oidc_handle_authorization_response: session created and stored, returning to original URL: https://serverIP/, original method: get, referer: https://serverIP/auth/realms/app-realm/protocol/openid-connect/auth?response_type=code&scope=openid&client_id=st_httpd_192.168.2.102&state=4LEohhGikZhoDD6MDHm4xNad9QI&redirect_uri=https%3A%2F%2FserverIP%2Fprotected%2Fredirect_uri&nonce=p7pxhS1SY2hc52RLJ7zK1m15JynGgcIZt9EeVWKZ6uM

```
the oidc_check_max_session_duration warning logs:
```
[Mon May 08 09:58:23 2017] [warn] [client clientIP] oidc_check_max_session_duration: maximum session duration exceeded for user: admin, referer: https://serverIP/main_tab.htm
```

The logs are attached.
[ssl_error_log.zip](https://github.com/pingidentity/mod_auth_openidc/files/999172/ssl_error_log.zip)

**Comment by zandbelt** [comment]
It may be because of https://github.com/pingidentity/mod_auth_openidc/commit/703dfc8e7c900f43ad1f493bba213123e008419c so I'd advise you to use a different cache backend until the next release comes out.

**Comment by security4java** [comment]
We must use file storage (OIDCCacheType file).
Do you have opened issue for https://github.com/pingidentity/mod_auth_openidc/commit/703dfc8e7c900f43ad1f493bba213123e008419c

**Comment by zandbelt** [comment]
see edited comment

**Comment by security4java** [comment]
Can it be fixed in 2.1.x?

We can not upgrade now ...

**Comment by zandbelt** [comment]
please look at the edited comment: the file storage type is not the problem; you have misconfigured `OIDCSessionMaxDuration`; perhaps is was specified in multiple places

**Comment by security4java** [comment]
We have it only once. I do not understand why the issue is closed

**Comment by zandbelt** [comment]
because you keep ignoring the answers given: please stop opening issues for what are not bugs or feature requests; use the mailing list for that

**Comment by security4java** [comment]
I have missed your eddied comment – sorry.
I think the module have the bug: after the authentication the oidc_check_max_session_duration is not resets.
You can not provide logs in the mailing list – therefore the correct way is to open Jira issues.

**Comment by zandbelt** [comment]
you can discuss commercial support to debug your setup here: info@zmartzone.eu

**Comment by zandbelt** [comment]
for the record: this was indeed due to a misconfiguration

**Comment by security4java** [comment]
Today we discussed other bug :)

https://github.com/pingidentity/mod_auth_openidc/issues/245

The “Bad Request” error appears · Issue #245 · pingidentity/mod_auth_openidc<https://github.com/pingidentity/mod_auth_openidc/issues/245>
github.com
After the successful authentication during normal work unfortunately the “Bad Request” error appears Bad Request Your browser sent a request that this server could not understand. Size of a request...




________________________________
