### ISSUE TITLE
Problem to install

### ISSUE THREAD

**Issue by rha3d** [pingidentity/mod_auth_openidc#271]
I am trying to install the release 2.2.0 but i got the following message 

Error: Package: mod_auth_openidc-2.2.0-1.el6.x86_64 (/mod_auth_openidc-2.2.0-1.el6.x86_64)
           Requires: libhiredis.so.0.12()(64bit)

I am working with Oracle Linux Server release 6.5 and currently it is running the release 1.8

**Comment by zandbelt** [comment]
The release notes at https://github.com/pingidentity/mod_auth_openidc/releases/tag/v2.2.0 say in the "Packaging Notes" section:

> Centos 6 RPMs depend on libhiredis-0.12 now e.g. from https://pkgs.org/centos-6/puias-unsupported-x86_64/
