### ISSUE TITLE
Support for OpenID connect - on Apache2.4 on Windows 64

### ISSUE THREAD

**Issue by ujwalajadhav** [pingidentity/mod_auth_openidc#275]
###### Environment

- mod_auth_openidc version 2.2.0 / 1.8.10
- Apache version 2.4 
- platform/distro  - Windows 7 64 -bit

Steps did to install mod_auth_openidc:

1)	Registered application by creating a client at the corporate oidc server
Saved clientid, client secret, Redirect_URIs and other required information.
2)	Downloaded the mod_auth_openidc library from Github- https://github.com/pingidentity/mod_auth_openidc/releases
File: mod_auth_openidc-2.2.0-apache-2.4.x-win64.zip
Unzipped this file and copied the contents from bin and modules folder in the Apache folders respectively

3)	Installed the curl-ca-bundle.crt which is in Apache24/bin folder by double clicking it.

4)	Modified the httpd.conf file and added the following line the file -
LoadModule auth_openidc_module modules/mod_auth_openidc.so

5)	Configured mod_auth_openidc from template present at - https://github.com/pingidentity/mod_auth_openidc/blob/master/auth_openidc.conf
Modified and saved this file with the client details done in step 1.

6)	Copied this file in the C:\Apache24\conf\ folder

After doing this configuration we restarted the server and it is not getting started. 

When commented -  “LoadModule auth_openidc_module modules/mod_auth_openidc.so” this line from httpd.conf file, there is no problem starting the server.

###### Expected behavior

Server should start and when accessing the webpage it should bring the SSO page asking for user credentials.

###### Actual behavior
Server is not getting started.

###### Configuration and Log files
No error in log files.

**Comment by zandbelt** [comment]
You'll need to copy all of the files from the `/bin` folder in the ZIP file to the Apache `/bin/` folder: 3 DLLs and the `curl-ca-bundle.crt`. The `cjose.dll`, `libcurl.dll` and `jansson.dll` are required dependencies.

**Comment by ujwalajadhav** [comment]
Thank you for your reply. 
Yes I have copied all the contents from bin folder in the ZIP file to Apache/bin/ folder as mentioned in the step 2, and still could not start the Apache server.

**Comment by ujwalajadhav** [comment]
We could restart the Apache server with below resolution. 

Resolution:

mod_auth_openidc library requires msvcr120.dll which is the newer version of Microsoft VC ++. It looks for this file. We used dependency walker software to see the tree and what are the required files for the mod_auth_openidc.iso. It showed missing msvcr120.dll file. We had to update the current vc++ which added this missing dll in the windows\System32 folder. and we could restart the server. 

Also we had to add this statment - "Include oidc.conf" in httpd.conf file.

Hope this helps for any future developers who are not able to restart the server when integrating with Openid connect.

**Comment by zandbelt** [comment]
That's very useful information to have, thanks!

**Comment by tiwari3010** [comment]
@zandbelt Thanks for the posts above, I tried all the steps on Windows 8 and Windows 2012 R2, but apache is not starting

C:\Apache24\bin>httpd.exe -version
Server version: Apache/2.4.27 (Win64)
Apache Lounge VC15 Server built:   Jul  7 2017 12:46:00
mod_auth_openidc-2.3.1-apache-2.4.x-win64
copied all the files to Bin and Module folder of apache24.
Confirmed I have Microsoft VC++ running on both windows 8 and 2012 R2.

While starting apache getting error:

The Apache service named  reported the following error:
>>> httpd.exe: Syntax error on line 181 of C:/Apache24/conf/httpd.conf: Cannot load modules/mod_auth_openidc.so into server: The specified module could not be found.     .

Please suggest.

**Comment by zandbelt** [comment]
Perhaps you could try and use the dependency walker as well.

**Comment by zandbelt** [comment]
For the record: I can produce a version compiled with Visual Studio 2017 that would rely on the Visual C++ Redistributable for Visual Studio 2015. Anyone interested in using that can contact me.

**Comment by tiwari3010** [comment]
Hi @zandbelt, I would be interested in testing using Visual C++ Redistributable for 2015. Please send me the link I can download and steps to perform for running on my local or Windows 2012 R2 servers.

**Comment by andreasljung** [comment]
Hi

Did you get it to work?

I am trying to run the latest "release 2.3.2" and I get the error in the Event log when I try to start the Apache server from Activity Monitor

The Apache service named  reported the following error:
>>> httpd.exe: Syntax error on line 181 of C:/Apache24/conf/httpd.conf: Cannot load modules/mod_auth_openidc.so into server: The specified module could not be found. "

But if I try to run httpd.exe from commandline I get:

httpd.exe: Syntax error on line 181 of C:/Apache24/conf/httpd.conf: Cannot load
modules/mod_auth_openidc.so into server: %1 is not a valid Win32 application.

I am running:

Apache 2.4.28 x64
Microsoft Visual C++ 2015 Restributable (x64) - 14.0.24123

**Comment by zandbelt** [comment]
Which Windows platform are you on? The binaries are 64bit.

**Comment by zandbelt** [comment]
Can you run http://dependencywalker.com/ to see if/which dependency is the issue?

**Comment by andreasljung** [comment]
I am using Windows Server 2012 (64bit)

![image](https://user-images.githubusercontent.com/3244906/31425074-f2e8e5a8-ae5d-11e7-864f-8f053900c44c.png)

**Comment by zandbelt** [comment]
Could it be that you are not using an Apache setup/package that is SSL enabled?

**Comment by andreasljung** [comment]
I have now enabled SSL for the apache server and installed OpenSSL for Windows 64 bit. But I still get the same error for this module.

**Comment by andreasljung** [comment]
It seemed to have been some issue with version 1.1.0 of OpenSSL 64bit. I saw the latest comment on this thread and instead I choose version 1.0.2 and then it worked.

https://stackoverflow.com/questions/40017498/cannot-load-modules-mod-ssl-so-into-server

**Comment by zandbelt** [comment]
ah, right; I'll add that to the release notes, thanks

**Comment by ShirleyAu** [comment]
![image](https://user-images.githubusercontent.com/39824330/58313160-7e637f00-7e3f-11e9-9a62-d352b3ae4cc2.png)

I cannot start the httpd.exe, anyone have idea?

**Comment by ujwalajadhav** [comment]
Also, make sure you have latest copy of Microsoft VC++. Server won’t restart if missing msvcr120.dll file at windows\System32 folder.

**Comment by ShirleyAu** [comment]
I already install Microsoft Visual C++ 2015-2019 Redistributable (x64).

![image](https://user-images.githubusercontent.com/39824330/58397934-9af0f880-8085-11e9-9fbe-b7d2a8e0788b.png)

![image](https://user-images.githubusercontent.com/39824330/58397901-7d239380-8085-11e9-881d-9885284773e2.png)

**Comment by ping2sri** [comment]
Unable to find below modules. Can someone help on this. 

Downloaded the mod_auth_openidc library from Github- https://github.com/pingidentity/mod_auth_openidc/releases
File: mod_auth_openidc-2.2.0-apache-2.4.x-win64.zip

**Comment by obou-uobo** [comment]
> ping2sri
I found 
File:mod_auth_openidc-2.3.11rc2licensed-apache-2.4.x-win64.zip
bellow site
https://mod-auth-openidc.org/download/?C=M;O=D

Isn't it availavle?

**Comment by ping2sri** [comment]
obou-uobo,
https://mod-auth-openidc.org/download/?C=M;O=D link is working fine now. but still I am getting same error. Cannot load modules/mod_auth_openidc.so into server: The specified module could not be found. 
my server has VC++ 2013.
![image](https://user-images.githubusercontent.com/55763267/70071550-84db6c00-15c3-11ea-9c48-64a9f6677a57.png)

**Comment by ping2sri** [comment]
![image](https://user-images.githubusercontent.com/55763267/70075537-0387d780-15cb-11ea-8eac-0cb08c4ec6d4.png)
find Dependency details.

**Comment by ping2sri** [comment]
![image](https://user-images.githubusercontent.com/55763267/70075665-39c55700-15cb-11ea-9fea-cd089626247a.png)
Dependency details.

**Comment by zandbelt** [comment]
support for the Windows build only comes as part of a commercial support subscription

**Comment by stagging18** [comment]
I am not able to see the **mod_auth_openidc-2.2.0-apache-2.4.x-win64.zip**  file in any of the release.
Can anyone please help me to find this.

Regards,
Rajesh

**Comment by roman-la** [comment]
@stagging18 Look here https://mod-auth-openidc.org/download/?C=M;O=D

**Comment by Nareshgarg0976** [comment]
I am unable to find the latest version for windows. Could someone please help me with that?

**Comment by zandbelt** [comment]
> I am unable to find the latest version for windows. Could someone please help me with that?

https://github.com/zmartzone/mod_auth_openidc/issues/275#issuecomment-561294508

**Comment by Nareshgarg0976** [comment]
I am getting this error. 
C:\Apache24\bin>httpd
httpd: Syntax error on line 74 of C:/Apache24/conf/httpd.conf: Cannot load modules/mod_auth_openidc.so into server: The operating system cannot run %1.
