### ISSUE TITLE
oidc_get_current_url_port redirect uses local listen port

### ISSUE THREAD

**Issue by douglasc-nflx** [pingidentity/mod_auth_openidc#278]
###### Environment

mod_auth_openidc 2.2.0-1-trusty
Apache 2.4.18 (Ubuntu)

###### Expected behaviour

Apache2 is locally bound to a non-standard listen port (e.g. 5000), but traffic is routed such that clients reach it through the standard port (443).  Clients are redirected to the original URL and port after authenticating.

###### Actual behaviour

After authentication success, mod_auth_openidc responds with a 302 that incorrectly specifies the locally bound port in the redirect URL.

The redirect port is chosen in `oidc_get_current_url_port` which looks for an `X-Forwarded-Port` header, not added by mod_proxy, then an `X-Forwarded-Host` header, which doesn't specify a port, then a `Host` header, again which is missing a port value, because its the standard.  It finally assumes to use the locally bound port when no port was given elsewhere.

As a workaround, one can add an `X-Forwarded-Port` ahead of mod_auth_openidc:

```RequestHeader set X-Forwarded-Port 443 early```

Perhaps if X-Forwarded-Port is missing but X-Forwarded-Host is present with no port specified, this function should assume the standard port for the X-Forwarded-Proto rather than assume the local port; or expose this as a configuration option.

**Comment by zandbelt** [comment]
I believe that would be a more sane default indeed.

**Comment by zandbelt** [comment]
On 2nd thought, looking at:
https://github.com/pingidentity/mod_auth_openidc/blob/master/src/util.c#L396
shows that when `X-Forwarded-Host` is present,  no further processing is done. When only `Host` is present, the  the local port is determined.

Which seems to me the behavior you're looking for, are you saying that it doesn't work for you? In that case I would try and confirm that `X-Forwarded-Host` is actually set.

**Comment by douglasc-nflx** [comment]
You're right, but actually my original assessment was slightly wrong.  The code will work fine if there was some actual http proxy in front of Apache. However our case is just network routing, there is no `X-Forwarded-Host` header.  Only a `Host` header, which is where the fall-through to the local bound port occurs.

**Comment by zandbelt** [comment]
That's an a-typical use case that I'd rather see handled with `RequestHeader` (or running the server on the same port) than adapting the current code.

I believe local port detection was originally included to deal with user agents that don't provide the port in the `Host` header and I don't want to break backwards compatibility with that.

**Comment by zandbelt** [comment]
you did mention `X-Forwarded-Proto` and the previous commit does address that: when that header has been set, it assumes the default port for that protocol; when no `X-*` headers have been set the behavior stays as is
