### ISSUE TITLE
customizable error pages

### ISSUE THREAD

**Issue by rmbleeker** [pingidentity/mod_auth_openidc#280]
I'm wondering if there is a way to customize the mod_auth_openidc error pages like the one below, similar to how you can use custom error pages in Apache. It would be nice if you could make them look like the site you're protecting with OpenID.

<img width="479" alt="screen shot 2017-06-22 at 15 15 16" src="https://user-images.githubusercontent.com/4312801/27435991-07c3daf2-575e-11e7-90fa-64c06d56cd98.png">

**Comment by rmbleeker** [comment]
Thanks, I completely missed that.

**Comment by zandbelt** [comment]
Agree, it is kind of hidden. I've added it to the FAQ Wiki now: https://github.com/pingidentity/mod_auth_openidc/wiki#19-how-do-i-customize-the-user-facing-error-pages

**Comment by rmbleeker** [comment]
I just wanted to ask a quick follow-up question concerning the OIDCHTMLErrorTemplate option. Is it correct that this option can only take an absolute path? At least that's the only way I got it to work.

**Comment by zandbelt** [comment]
Yeah, it is absolute only right now. Making it relative (or absolute) to the Apache root dir is most probably a one-line (untested) fix:
```
diff --git a/src/util.c b/src/util.c
index 1529a1c..375e451 100644
--- a/src/util.c
+++ b/src/util.c
@@ -1329,6 +1329,8 @@
 
 	char *html = "";
 
+	html_template = ap_server_root_relative(r->pool, html_template);
+
 	if (html_template != NULL) {
 
 		if (html_error_template_contents == NULL) {
```
If you can confirm this works for you I'll include that in the master branch for the next release.

**Comment by rmbleeker** [comment]
I'm currently using this mod on a production system so I'm hesitant to compile and test this there. I would have to setup a test environment but I'm not sure when I'll be able to do that, sorry.

**Comment by zandbelt** [comment]
that small patch was wrong; I addressed it correctly and more complete in the last commit; thanks
