### ISSUE TITLE
Multiple redirect URIs for multiple tomcat instances

### ISSUE THREAD

**Issue by ujwalajadhav** [pingidentity/mod_auth_openidc#281]
I have two tomcat instances running on Apache server for two applications.

How to configure 2 redirect URIs in oidc.conf file for each instance? As I have two tomcat instances running, there is an uri for each application. 

for two instances, do we need to create two oidc*.conf files? because 
<location /abc>
...
..
</location>
and other setting will be in one file and same for other instance.

###### Environment

- mod_auth_openidc version 2.2 
- Apache version 2.4
- platform/distro  windows 7

###### Expected behaviour
Each tomcat instance should serve for each redirect URI.

###### Actual behaviour
Only one instance is entertaining for an URI

###### Minimized example
for e.g. I have application1 running on tomcat instance1, and application2 running on tomcat instance 2 on Apache2.4.
In OIDC.conf file I have below redirect URI set
OIDCRedirectURI http://instance1_redirect_uri/ for application1 and corresponding client is registered on client portal.

for second instance how to configure oidc.conf file so it serves both the uri for 2 tomcat instances? 

Any help with this issue is really appreciated.

**Comment by zandbelt** [comment]
If the tomcat apps are path-separated - as you seem to suggest - you'd share the redirect URI. The session cookie by default will validate on both paths:
```
<Location /abc>
  AuthType openid-connect
  Require valid-user
</Location>

<Location /def>
  AuthType openid-connect
  Require valid-user
</Location>

<Location /redirect_uri>
  AuthType openid-connect
  Require valid-user
</Location>
```
But if they live on different hostnames, you'd use different vhosts with different redirect URIs.

**Comment by ujwalajadhav** [comment]
Both applications use different vhosts and have different redirect URIs. They will be registered as different clients in the OIDC API portal. so the details we provide in oidc.conf file will be completely different for both the application. 

Do we provide 2 oidc.conf (e.g. oidc1.conf, oidc2.conf) files for each client? Please excuse me for my lack of knowledge. or we need to place these files somewhere else for vhosts?

Thank you.

**Comment by zandbelt** [comment]
Define two virtual hosts: https://httpd.apache.org/docs/2.4/vhosts/examples.html
