### ISSUE TITLE
Mod openidc Permission denied

### ISSUE THREAD

**Issue by gokulnathb** [pingidentity/mod_auth_openidc#285]
OIDCProviderMetadataURL https://aaa.test.com:9031/.well-known/openid-configuration
OIDCHTTPTimeoutShort 10000
OIDCSSLValidateServer Off
OIDCClientID client1
OIDCRedirectURI http://chelx2005.test.com/example/redirect_uri/
OIDCCryptoPassphrase dddddd
OIDCScope "openid mail"
OIDCOAuthRemoteUserClaim Username

Apache 2.4

[Thu Jul 20 21:56:51.168685 2017] [auth_openidc:debug] [pid 25185] src/cache/common.c(521): [client 10.113.138.160:51052] oidc_cache_get: enter: https://aaalx1010.test.com:9031/.well-known/openid-configuration (section=p, decrypt=0, type=shm)
[Thu Jul 20 21:56:51.169204 2017] [auth_openidc:debug] [pid 25185] src/cache/common.c(557): [client 10.113.138.160:51052] oidc_cache_get: cache miss from shm cache backend for key https://aaalx1010.test.com:9031/.well-known/openid-configuration
[Thu Jul 20 21:56:51.169216 2017] [auth_openidc:debug] [pid 25185] src/util.c(573): [client 10.113.138.160:51052] oidc_util_http_call: url=https://aaalx1010.test.com:9031/.well-known/openid-configuration, data=(null), content_type=(null), basic_auth=(null), bearer_token=(null), ssl_validate_server=0
[Thu Jul 20 21:56:56.684434 2017] [auth_openidc:error] [pid 25185] [client 10.113.138.160:51052] oidc_util_http_call: curl_easy_perform() failed on: https://aaalx1010.test.com:9031/.well-known/openid-configuration (Failed to connect to 10.66.158.248: Permission denied)]

When I connect with wget to the discovery url, the connection succeeds.

**Comment by zandbelt** [comment]
That's a firewall issue. See also: http://www.akashif.co.uk/php/curl-error-7-failed-to-connect-to-permission-denied

**Comment by gokulnathb** [comment]
Zan, Thanks for getting back, i did read the article and disabled selinux. But I was able to connect to the discovery url with wget successfully, it is failing only from apache mod connect.

**Comment by zandbelt** [comment]
Check it with `curl` from the same machine that runs `mod_auth_openidc`.

**Comment by gokulnathb** [comment]
Sorry, I was trying to say curl and typed it wget. Curl was a success.

**Comment by gokulnathb** [comment]
curl https://aaalx1010.test.com:9031/.well-known/openid-configuration -k

{"version":"3.0","issuer":"https:\/\/aaalx1010..test.com:9031","authorization_endpoint":"https:\/\/aaalx1010.test.com:9031\/as\/authorization.oauth2","token_endpoint":"https:\/\/aaalx1010..test.com:9031\/as\/token.oauth2","revocation_endpoint":"https:\/\/aaalx1010.test.com:9031\/as\/revoke_token.oauth2","userinfo_endpoint":"https:\/\/aaalx1010..test.com:9031\/idp\/userinfo.openid","jwks_uri":"https:\/\/aaalx1010.test.com:9031\/pf\/JWKS","ping_revoked_sris_endpoint":"https:\/\/aaalx1010..test.com:9031\/pf-ws\/rest\/sessionMgmt\/revokedSris","ping_end_session_endpoint":"https:\/\/aaalx1010..test.com:9031\/idp\/startSLO.ping","scopes_supported":["mail","openid"],"claims_supported":["email","family_name","given_name","middle_name","name","nickname","picture","preferred_username","profile","sub"],"response_types_supported":["code","token","id_token","code token","code id_token","token id_token","code token id_token"],"response_modes_supported":["fragment","query","form_post"],"subject_types_supported":["public"],"id_token_signing_alg_values_supported":["none","HS256","HS384","HS512","RS256","RS384","RS512","ES256","ES384","ES512"],"token_endpoint_auth_methods_supported":["client_secret_basic","client_secret_post"],"claim_types_supported":["normal"],"claims_parameter_supported":false,"request_parameter_supported":false,"request_uri_parameter_supported":false}

**Comment by zandbelt** [comment]
Which OS/distro, which version of mod_auth_openidc and how/where have you obtained binaries?
You should check with `ldd` that `mod_auth_openidc` links to the same `libcurl` as `curl` itself does.

**Comment by gokulnathb** [comment]
curl-7.29.0-35.el7.x86_64
libcurl-7.29.0-35.el7.x86_64
python-pycurl-7.19.0-19.el7.x86_64

mod_auth_openidc-2.3.0-1.el7.centos.x86_64

OS RHEL 7.3

**Comment by gokulnathb** [comment]
Downloaded from https://github.com/pingidentity/mod_auth_openidc/releases

**Comment by gokulnathb** [comment]
ldd /etc/httpd/modules/mod_auth_openidc.so
	libcurl.so.4 => /lib64/libcurl.so.4 (0x00007febe39af000)
ldd /bin/curl
	libcurl.so.4 => /lib64/libcurl.so.4 (0x00007f8fb3033000)

**Comment by gokulnathb** [comment]
SSL is disabled as well, not sure what is causing permission denied.

**Comment by zandbelt** [comment]
I believe it is selinux related and/or some other local security/firewall config setting. You can get commercial support to debug your setup via info@zmartzone.eu
