### ISSUE TITLE
OIDCProviderMetadataURL with multiple OP

### ISSUE THREAD

**Issue by remi-cc** [pingidentity/mod_auth_openidc#288]
Hello M. zandbelt,

Even if my RP has been registered with the OP (receiving client_ID and client_secret), i would like to refresh metadata about OP from the configuration endpoint, each hour for example.

When a single OP has been configured, it looks pretty easy to do that with "OIDCProviderMetadataURL" and "OIDCProviderMetadataRefreshInterval" parameters.

But when multiple OP has been configured (with OIDCMetadataDir), i can't refresh Metadata from OP's configuration endpoints. The OIDCProviderMetadataRefreshInterval parameter seems to refresh from JSON contained in OIDCMetadataDir only. But i'm trying to refresh directly from my OPs endpoints (e.g. https://www.myOP1.com/oauth2/.well-known/openid-configuration for the first and https://www.myOP2.com/oauth2/.well-known/openid-configuration for the second).

Is it possible to use/add this functionality please?
Thanks,

Rémi

**Comment by zandbelt** [comment]
`OIDCProviderMetadataRefreshInterval` is also used to check against the "last modified" file attribute of the `.provider` downloaded metadata file in a multi-provider setup. If the timestamp is older than the refresh interval, metadata should be downloaded again by pulling it from the well-known endpoint. Are you saying this doesn't work for you?

**Comment by remi-cc** [comment]
Thanks for your reply.

It doesn't seem to work, i catch any request to the well known endpoint and my metadata are not updated.

There is no well-known endpoint explicitely specified in my op.provider file and the discovery specs doesn't specify this parameter in the OpenID Provider Metadata response.

My question is how this endpoint is determined by  mod_auth_openidc?

Is the issuer value from op.conf concatenated with «/.well-know/openid-configuration»?

Or the webfinger protocol on the issuer value is used for each update to determine the well_known endpoint?

I must missed something

**Comment by zandbelt** [comment]
Indeed the URL is constructed from the issuer value as the spec dictates here: https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfig

You should set `OIDCProviderMetadataRefreshInterval` explicitly in a multi-provider setup as the default to never update it, see: https://github.com/pingidentity/mod_auth_openidc/blob/master/auth_openidc.conf#L710

**Comment by remi-cc** [comment]
Ok, i though that updates was made as soon as apache2 started.
But it needs an initial request on protected ressources.

So it works fine,

Thanks for your support and all your work for this product.

Rémi

**Comment by eric-gagnon** [comment]
@zandbelt 

I noticed that with Azure B2C, the metada url cannot be calculated from issuer + /.well-known/openid-configuration. Seems like Microsoft reinvented the specifications!

The issuer in my file looks like that:
https://sometenant.b2clogin.com/sometenant.onmicrosoft.com/v2.0/

But the "live" documentation for Azure b2c client in the portal present the metadata url as:
https://sometenant.b2clogin.com/sometenant.onmicrosoft.com/<policy-name>/v2.0/.well-known/openid-configuration

We have to replace policy name by a user flow (concept of azure b2c) identifier 

So the metadata is really at : https://sometenant.b2clogin.com/sometenant.onmicrosoft.com/b2c_some_user_flow_signin/v2.0/.well-known/openid-configuration

I'll document this as a known issue and manually refresh as needed.

**Comment by zandbelt** [comment]
ok, thanks for the note; I guess you'll need to set `OIDCValidateIssuer Off` then, see: https://github.com/zmartzone/mod_auth_openidc/blob/v2.4.12.3/auth_openidc.conf#L157-L160
