### ISSUE TITLE
Wiki page on access and refresh tokens has been deleted

### ISSUE THREAD

**Issue by quartje** [pingidentity/mod_auth_openidc#289]
In commit  068b9c5 the wiki page https://github.com/pingidentity/mod_auth_openidc/wiki/Access-Tokens-and-Refresh-Tokens has been deleted, while it's still referenced on the wiki home page. Is that by accident or is it not relevant anymore?

**Comment by zandbelt** [comment]
I hope it was an accident:
```
git show 068b9c5
commit 068b9c5cbc432d14aa812afc4832517b11a8b84d
Author: kancp <Pkancharla@pfs.com>
Date:   Thu Jun 1 14:00:39 2017 -0400

    Destroyed Access Tokens and Refresh Tokens (markdown)

```
I restored it now, thanks.
