### ISSUE TITLE
Session timeout min is 15 seconds - need to lower to 1

### ISSUE THREAD

**Issue by cdnsteve** [pingidentity/mod_auth_openidc#290]
###### Expected behaviour
- The min session lifetime should be allowed to be 1. 

###### Actual behaviour
Cannot change minimum session lifetime lower than 15 seconds.  We need to change to 1. 
- OIDC_SESSION_MAX_DURATION_MIN is hard coded to `15`

Not sure if there's a specific reason for the limitation?
We found when logging out of OIDC, you wouldn't be logged out of the Apache module. The user would remain logged in for the duration of the minimum session lifetime, since the mod_auth_openidc still remained.  It was originally set to `0` and our JWT setting was 5 minutes. This caused the user to be logged out of SSO but they were still logged into the app via the Apache module for 5 more minutes.

When changing to the lowest allowed value, 15, we logged out of OIDC, it woud only allow the user to remain in the app for the 15 seconds.  Ideally we'd like to see this changed to 1 to prevent any issues.

###### Minimized example
https://github.com/pingidentity/mod_auth_openidc/blob/d77ec0228901d25bcbc873950d964d5c1e00254a/src/parse.c#L503

Thanks!
Steve

**Comment by zandbelt** [comment]
It is relatively arbitrary indeed, meant to prevent people from shooting themselves in the foot.

A setting of 1 seconds means that every 1 second users would be sent off the the OP to authenticate. It sounds like what you really want is Single Logout:
https://github.com/pingidentity/mod_auth_openidc/wiki#9-how-do-i-logout-users

**Comment by cdnsteve** [comment]
Thanks for your quick response 👍
