### ISSUE TITLE
mod_authnz_ldap with openidc

### ISSUE THREAD

**Issue by gokulnathb** [pingidentity/mod_auth_openidc#295]
Apache mod_openidc can authenticate users which works fine.
Apache mod_openidc can authorize users by defining the user string in the apache config file, which also works.
I would like to mod_openidc to authorize users only if a user is part of a ldap group. I have seen configs for mod_ldap_auth which does ldap search without binding.
Does mod_openidc work in conjunction with mod_authnz_ldap? I am trying to authenticate with ldap directory/AD and authorize only users based on LDAP/AD groups. Has anyone tested this scenario?

**Comment by w112nxs** [comment]
The wiki has detailed documentation on options that you can use for authorization

https://github.com/pingidentity/mod_auth_openidc/wiki/Authorization

Thanks
Nishad

**Comment by zandbelt** [comment]
Especially this section:
https://github.com/pingidentity/mod_auth_openidc/wiki/Authorization#2-mod_authnz_ldap

**Comment by gokulnathb** [comment]
Thank you for getting back.
Yes I can see that the mod_authnz_ldap is supported, but I am trying to clarify if ldap bind is supported, as the anonymous ldap bind is not allowed. I have not seen any ldap bind config. So, can I assume the ldap bind parameter from apache mod_authz_ldap would suffice?

**Comment by zandbelt** [comment]
I don't know: that would be a question to ask in a mod_authz_ldap forum or just give it a try.

**Comment by make-all** [comment]
Normally you would bind to LDAP as a hardcoded user in the Apache config - you do not have access to the password for the user who is logging in if you are using mod_auth_openidc for the Authentication stage, so you cannot bind as the user who is logging in.

**Comment by gokulnathb** [comment]
Great thank you so much, you answered my question. I was trying to check if anyone was able to get  LDAP BIND (Service account and password) to work.

Like you said, all other users would be authorized based on AD groups, the group lookup in AD will be performed by the initial LDAP Bind credentials.
