### ISSUE TITLE
Add FreeBSD instructions to documentation

### ISSUE THREAD

**Issue by zi0r** [pingidentity/mod_auth_openidc#298]
I've added mod_auth_openidc to the FreeBSD ports tree:
[http://www.freshports.org/www/mod_auth_openidc](http://www.freshports.org/www/mod_auth_openidc)

The following should either be added to INSTALL or the wiki to instruct FreeBSD users how they can use the ports tree or package to install mod_auth_openidc (without having to manually build it/install dependencies):

> FreeBSD users can use one of the following two options to install mod_auth_openidc:
> 
> To install the port: cd /usr/ports/www/mod_auth_openidc/ && make install clean
> To add the package: pkg install ap24-mod_auth_openidc

**Comment by zandbelt** [comment]
I've added it to the INSTALL in the latest commit and to the Wiki here:
https://github.com/pingidentity/mod_auth_openidc/wiki#11-where-can-i-get-binary-packages
Thanks.

**Comment by erickengelke** [comment]
I tried both methods, but don't see the package on FreeBSD 11.0 Release.  Is it in 11.1?

**Comment by zi0r** [comment]
You'll need a current ports tree to build from ports.  You can use portsnap to update your local tree:
https://www.freebsd.org/doc/handbook/ports-using.html

The package was build and added to the FreeBSD repo on: 2017-Sep-14 11:23.

If you're still running into issues, please paste details on what you're seeing.
