### ISSUE TITLE
Getting ID Token info

### ISSUE THREAD

**Issue by ricardinhorio** [pingidentity/mod_auth_openidc#300]
Hi Folks,

I could installed properly that module on my Apache 2.4.6 and choose it to protect path www.mydomain.com.br/secure.

In my main page, at www.mydomain.com.br I put a link to /secure and it is redirecting properly to the SSO in order to authenticate the login.

My question is, and if I want to keep the user on the same page, instead of showing a link to /secure that is being called LOGIN (as a button), redirect it to the same main page of mydomain and show the Hi Someone, instead of the button?

The cookies are there but I am little bit on how to get those information since I am pretty new to Drupal and PHP.
My applications using keycloak java adapter are going fine but this module on Apache with Drupal/PHP apps are getting me crazy. hehehhe

Thanks for your attention.

Best Regards,
Ricardo Morais

**Comment by ricardinhorio** [comment]
Hi zandbelt, could you guys just give me some advise instead of just closing the ticket?

**Comment by zandbelt** [comment]
please read the text that you deleted when you created an issue in this project and follow those guidelines
