### ISSUE TITLE
Installation from source: Apache does not start due it can't load mod_auth_openidc.so : undefined symbol: CJOSE_HDR_ALG_PS256

### ISSUE THREAD

**Issue by jgrisa** [pingidentity/mod_auth_openidc#301]
Hi

We are tryin to install  mod_auth_openidc.so  from sources (last mod_auth_openidc-2.3.2), on our compiled apache.

Prerequisites apears ok ( all compiled & installed from sources)
--------------------
server:
Red Hat Enterprise Linux Server release 7.3 (Maipo)
arch x86_64
-------------
Apache:
$ /software/apache/software/httpd/bin/httpd -v
Server version: Apache/2.4.27 (Unix) (compiled from source)
--------------
cjose-0.5.1:
 /software/apache/software/cjose/lib/
-------------------
 OpenSSL :
/software/apache/software/openssl-1.0.2k/bin/openssl
OpenSSL> version
OpenSSL 1.0.2k  26 Jan 2017
OpenSSL>
----------------------------------
 Curl:
/software/apache/software/curl/bin/curl -V
curl 7.34.0 (x86_64-unknown-linux-gnu) libcurl/7.34.0 OpenSSL/1.0.2k
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smtp smtps telnet tftp
Features: IPv6 Largefile NTLM NTLM_WB SSL TLS-SRP
-----------------------------
 Jansson:
jansson-2.10
/software/apache/software/jansson/lib/
------------------------
 pcre3:
/software/apache/software/pcre/bin/pcretest
PCRE version 8.35 2014-04-04
---------------------
 pkg-config
$ pkg-config --version
0.27.1
--------------------------------------------

configuration and installtion is ok: (includeed enviroments vars) lest see an example:

preparing:

./autogen.sh

- configured with ptahs as enviromet  vars:

PCRE_CFLAGS="-I/software/apache/software/pcre/include" PCRE_LIBS="-L/software/apache/software/pcre/lib" CJOSE_CFLAGS="-I/software/apache/software/cjose/include" CJOSE_LIBS="-L/software/apache/software/cjose/lib" JANSSON_CFLAGS="-I/software/apache/software/jansson/include" JANSSON_LIBS="-L/software/apache/software/jansson/lib" APR_CFLAGS="-I/software/apache/software/httpd/include"   APR_LIBS="-L/software/apache/software/httpd/lib" OPENSSL_LIBS="-L/software/apache/software/openssl-1.0.2k/lib" OPENSSL_CFLAGS="-I/software/apache/software/openssl-1.0.2k/include" CURL_CFLAGS="-I/software/apache/software/curl/include"  CURL_LIBS="-L/software/apache/software/curl/lib" ./configure --with-apxs2=/software/apache/software/httpd/bin/apxs
---------
all seems ok:
---------
checking for pkg-config... /bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for CURL... yes
checking for OPENSSL... yes
checking for APR... yes
checking for JANSSON... yes
checking for CJOSE... yes
checking for PCRE... yes
checking for HIREDIS... no
configure: creating ./config.status
config.status: creating Makefile

------------------------
make
make install

----------
all seems well installed :

-----------------
/software/apache/software/httpd/bin/apxs  -i -n mod_auth_openidc src/mod_auth_openidc.la
/software/apache/software/httpd/build/instdso.sh SH_LIBTOOL='/software/apache/software/httpd/build/libtool' src/mod_auth_openidc.la /software/apache/software/httpd/modules
/software/apache/software/httpd/build/libtool --mode=install install src/mod_auth_openidc.la /software/apache/software/httpd/modules/
libtool: install: install src/.libs/mod_auth_openidc.so /software/apache/software/httpd/modules/mod_auth_openidc.so
libtool: install: install src/.libs/mod_auth_openidc.lai /software/apache/software/httpd/modules/mod_auth_openidc.la
libtool: install: install src/.libs/mod_auth_openidc.a /software/apache/software/httpd/modules/mod_auth_openidc.a
libtool: install: chmod 644 /software/apache/software/httpd/modules/mod_auth_openidc.a
libtool: install: ranlib /software/apache/software/httpd/modules/mod_auth_openidc.a
libtool: finish: PATH="/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/apache/.local/bin:/home/apache/bin:/sbin" ldconfig -n /software/apache/software/httpd/modules
----------------------------------------------------------------------
Libraries have been installed in:
   /software/apache/software/httpd/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the '-LLIBDIR'
flag during linking and do at least one of the following:
   - add LIBDIR to the 'LD_LIBRARY_PATH' environment variable
     during execution
   - add LIBDIR to the 'LD_RUN_PATH' environment variable
     during linking
   - use the '-Wl,-rpath -Wl,LIBDIR' linker flag
   - have your system administrator add LIBDIR to '/etc/ld.so.conf'

See any operating system documentation about shared libraries for
more information, such as the ld(1) and ld.so(8) manual pages.
----------------------------------------------------------------------
chmod 755 /software/apache/software/httpd/modules/mod_auth_openidc.so

-----------------------------------------

I load the libs at apache var LD_LIBRARY_PAT:

/software/apache/software/httpd/bin/envvars
----------------------
#
if test "x$LD_LIBRARY_PATH" != "x" ; then
  LD_LIBRARY_PATH="/software/apache/software/httpd/lib:$LD_LIBRARY_PATH"
else
  LD_LIBRARY_PATH="/software/apache/software/httpd/lib"
fi
LD_LIBRARY_PATH="/software/apache/software/curl/lib:/software/apache/software/openssl-1.0.2k/lib:/software/apache/software/curl/lib/software/apache/software/curl/lib:/software/apache/software/pcre/lib:/software/apache/software/jansson/lib:/software/apache/software/cjose/lib:/software/apache/software/httpd/modules:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH
-------------------

as root i load libraries at

# vi  /etc/ld.so.conf.d/libs.conf
---------------------------------------
/software/apache/software/libmcrypt/lib
/software/apache/software/ltdl/lib
/software/apache/software/curl/lib
/software/apache/software/openssl-1.0.2k/lib
/software/apache/software/cjose/lib
------------------------------

ldconfig

--------------

All seems ok, but apache does not start:

------------

/software/apache/software/httpd/bin/apachectl stop
httpd: Syntax error on line 83 of /software/apache/software/httpd/conf/httpd.conf: Cannot load modules/mod_auth_openidc.so into server: /software/apache/software/httpd/modules/mod_auth_openidc.so: undefined symbol: CJOSE_HDR_ALG_PS256

---------------------------

Thanks in advance

Jose Luis

**Comment by zandbelt** [comment]
Can't you just use the one that is distributed as part of the release page of this project i.e. https://github.com/pingidentity/mod_auth_openidc/releases/download/v2.3.2/mod_auth_openidc-2.3.2-1.el7.centos.x86_64.rpm?

**Comment by zandbelt** [comment]
For your convenience I have pasted the Dockerfile with the step-by-step build commands that I use to create the RPM. If you can confirm this procedure and spot where the difference is then please us know here.

```
FROM centos:centos7
MAINTAINER Hans Zandbelt <hans.zandbelt@zmartzone.eu>

# CentOS Linux release 7.0.1406 (Core)

RUN rpm --import http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
RUN rpm -ihv http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-10.noarch.rpm

RUN yum update -y

# install dev tools
RUN ${CMD_PREFIX} yum install -y rpm-build gcc tar git autoconf automake libtool make

# setup rpmbuild environment
WORKDIR /opt/rpmbuild
ENV HOME /opt/rpmbuild
RUN mkdir -p $HOME/rpm/{BUILD,SRPMS,SPECS,SOURCES,RPMS}
RUN echo "%_topdir $HOME/rpm" > ~/.rpmmacros

# mod_auth_openidc depends
RUN ${CMD_PREFIX} yum install -y openssl-devel 
RUN ${CMD_PREFIX} yum install -y jansson-devel
RUN ${CMD_PREFIX} yum install -y httpd httpd-devel curl-devel pcre-devel check-devel

ENV CJOSE_VERSION 0.5.1
ENV CJOSE_TGZ cjose-${CJOSE_VERSION}.tar.gz
ENV MOD_AUTH_OPENIDC_TGZ mod_auth_openidc-${MOD_AUTH_OPENIDC_VERSION}.tar.gz
ENV MOD_AUTH_OPENIDC_ORIG_TGZ libapache2-mod-auth-openidc_${MOD_AUTH_OPENIDC_VERSION}.orig.tar.gz

# build cjose RPM
RUN curl -o ${HOME}/rpm/SOURCES/${CJOSE_TGZ} https://mod-auth-openidc.org/download/${CJOSE_TGZ}
ADD cjose.spec ${HOME}/rpm/SPECS/cjose.spec
RUN ${CMD_PREFIX} rpmbuild --define "release ${CJOSE_VERSION}" -bb ${HOME}/rpm/SPECS/cjose.spec

#install cjose RPM
RUN yum localinstall -y /opt/rpmbuild/rpm/RPMS/x86_64/cjose-${CJOSE_VERSION}-1.el7.centos.x86_64.rpm

RUN yum install -y hiredis-devel

ENV MOD_AUTH_OPENIDC_VERSION 2.3.2
ENV MOD_AUTH_OPENIDC_TGZ mod_auth_openidc-${MOD_AUTH_OPENIDC_VERSION}.tar.gz

# build mod_auth_openidc RPM
RUN curl -o ${HOME}/rpm/SOURCES/${MOD_AUTH_OPENIDC_TGZ} https://mod-auth-openidc.org/download/${MOD_AUTH_OPENIDC_TGZ}
ADD mod_auth_openidc.spec ${HOME}/rpm/SPECS/mod_auth_openidc.spec
ENV HIREDIS_LIBS -lhiredis
RUN ${CMD_PREFIX} rpmbuild --define "release ${MOD_AUTH_OPENIDC_VERSION}" -bb ${HOME}/rpm/SPECS/mod_auth_openidc.spec
```

**Comment by zandbelt** [comment]
any luck with that?

**Comment by jgrisa** [comment]
Sorry, but I,dont need a rpm package, I just need compile and install form
source, on a custom path.
At our IT depatnament we use to compile our own version of apache, with
php, ldap,ssl, compiled fron sources ...

2017-10-05 15:47 GMT+02:00 Hans Zandbelt <notifications@github.com>:

**Comment by zandbelt** [comment]
Ok, you're on your own then or you can discuss commercial support on info@zmartzone.eu

**Comment by brzler** [comment]
I have the same problem.
Compilation works but there must be something missing in the outcome ...
@jgrisa did you found the issue?

**Comment by brzler** [comment]
Using only PKG_CONFIG_PATH environment variable helped.
Using anything else leads to statically linked libs and so Apache can't find the module's dependencies even though they are on the ld library path.

**Comment by toolmantim422** [comment]
@brzler 
Could you specify where you used that " PKG_CONFIG_PATH environment variable" as I am facing the same issue.
It compiles fine, but then Apache will not start and throws this error.
httpd: Syntax error on line 123 of ..../conf/httpd.conf: Cannot load libjansson_module into server: libjansson_module: cannot open shared object file: No such file or directory

Thanks
