### ISSUE TITLE
apache segmentation fault when config invalid

### ISSUE THREAD

**Issue by iconoeugen** [pingidentity/mod_auth_openidc#303]
###### Environment

- mod_auth_openidc-2.3.2 - init - cjose 0.5.1, OpenSSL 1.0.2k-fips  26 Jan 2017, EC=yes, GCM=yes, Redis=yes, JQ=no
- mod_ssl/2.4.6 compiled against Server: Apache/2.4.6, Library: OpenSSL/1.0.2k
- CentOS Linux release 7.4.1708 (Core) docker image

###### Expected behaviour

Apache should stop running with error log entry stating the configuration is invalid

###### Actual behaviour

Apache stops with Segmentation Fault:

###### Minimized example

Configure invalid value for OIDCProviderMetadataURL to trigger the Segmentation Fault, ie:

```
OIDCProviderMetadataURL example.com/auth/realms/test/.well-known/openid-configuration
```

If value has protocol then Apache start successfully:
```
OIDCProviderMetadataURL https://example.com/auth/realms/test/.well-known/openid-configuration
```

###### Configuration and Log files
```
[Tue Oct 10 13:46:40.487319 2017] [auth_openidc:info] [pid 121] mod_auth_openidc-2.3.2 - init - cjose 0.5.1, OpenSSL 1.0.2k-fips  26 Jan 2017, EC=yes, GCM=yes, Redis=yes, JQ=no
[Tue Oct 10 13:46:40.488648 2017] [auth_openidc:debug] [pid 121] src/cache/shm.c(130): oidc_cache_shm_post_config: initialized shared memory with a cache size (# entries) of: 500, and a max (single) entry size of: 16913
[Tue Oct 10 13:46:40.489708 2017] [auth_openidc:debug] [pid 121] src/cache/shm.c(130): oidc_cache_shm_post_config: initialized shared memory with a cache size (# entries) of: 500, and a max (single) entry size of: 16913
[Tue Oct 10 13:46:40.489718 2017] [auth_openidc:debug] [pid 121] src/config.c(1892): oidc_config_check_vhost_config: enter
Segmentation fault (core dumped)
```

**Comment by zandbelt** [comment]
Good catch, thanks; the fix will be included in 2.3.3.
