### ISSUE TITLE
Redirect URI problem

### ISSUE THREAD

**Issue by karuatcsg** [pingidentity/mod_auth_openidc#44]
I am trying to protect 'content' folder served by Apache/2.2.22 (Ubuntu). Here is my config entry

        OIDCProviderMetadataURL http://192.168.1.11:8080/openid-connect-server-webapp/.well-known/openid-configuration
        OIDCCryptoPassphrase helloworld
        OIDCRedirectURI http://192.168.1.11:100/content/redirect_uri
        OIDCScope "openid email profile"
        #OIDCCookiePath /
        #OIDCCookieDomain 192.168.1.11

        OIDCClientID xxxxxxxx
        OIDCClientSecret xxxxxxxxxxxxxxxxx

        <Location /content>
           AuthType openid-connect
           Require claim preferred_username:guest
        </Location>

As you can see my OP is running on Tomcat on the same server.

When I access http://192.168.1.11:100/content/user/index.html I get the following error on the browser

HTTP Status 404 - /openid-connect-server-webapp/oauth/error

However if the redirect_uri is not under "/content" say "/redirect_uri" all URL's referring to "/content/**" get redirected to /redirect_uri/index.html

I am not able to make this work, any help is appreciated.

thanks,
Karunakar

**Comment by zandbelt** [comment]
Your config looks OK. Can you show the contents of `http://192.168.1.11:8080/openid-connect-server-webapp/.well-known/openid-configuration`? It looks like the `openid-configuration` metadata contains an authorization endpoint for the provider that is wrong/invalid.

**Comment by karuatcsg** [comment]
This is the content of http://192.168.1.11:8080/openid-connect-server-webapp/.well-known/openid-configuration

{
	"request_parameter_supported": true,
	"id_token_encryption_alg_values_supported": ["RSA-OAEP",
	"RSA1_5",
	"RSA-OAEP-256"],
	"registration_endpoint": "http://192.168.1.11:8080/openid-connect-server-webapp/register",
	"userinfo_signing_alg_values_supported": ["HS256",
	"HS384",
	"HS512",
	"RS256",
	"RS384",
	"RS512"],
	"token_endpoint": "http://192.168.1.11:8080/openid-connect-server-webapp/token",
	"request_uri_parameter_supported": false,
	"request_object_encryption_enc_values_supported": ["A192CBC-HS384",
	"A192GCM",
	"A256CBC+HS512",
	"A128CBC+HS256",
	"A256CBC-HS512",
	"A128CBC-HS256",
	"A128GCM",
	"A256GCM"],
	"token_endpoint_auth_methods_supported": ["client_secret_post",
	"client_secret_basic",
	"client_secret_jwt",
	"private_key_jwt",
	"none"],
	"userinfo_encryption_alg_values_supported": ["RSA-OAEP",
	"RSA1_5",
	"RSA-OAEP-256"],
	"subject_types_supported": ["public",
	"pairwise"],
	"id_token_encryption_enc_values_supported": ["A192CBC-HS384",
	"A192GCM",
	"A256CBC+HS512",
	"A128CBC+HS256",
	"A256CBC-HS512",
	"A128CBC-HS256",
	"A128GCM",
	"A256GCM"],
	"claims_parameter_supported": false,
	"jwks_uri": "http://192.168.1.11:8080/openid-connect-server-webapp/jwk",
	"id_token_signing_alg_values_supported": ["HS256",
	"HS384",
	"HS512",
	"RS256",
	"RS384",
	"RS512",
	"none"],
	"authorization_endpoint": "http://192.168.1.11:8080/openid-connect-server-webapp/authorize",
	"require_request_uri_registration": false,
	"introspection_endpoint": "http://192.168.1.11:8080/openid-connect-server-webapp/introspect",
	"request_object_encryption_alg_values_supported": ["RSA-OAEP",
	"RSA1_5",
	"RSA-OAEP-256"],
	"service_documentation": "http://192.168.1.11:8080/openid-connect-server-webapp/about",
	"response_types_supported": ["code",
	"token"],
	"token_endpoint_auth_signing_alg_values_supported": ["HS256",
	"HS384",
	"HS512",
	"RS256",
	"RS384",
	"RS512"],
	"revocation_endpoint": "http://192.168.1.11:8080/openid-connect-server-webapp/revoke",
	"request_object_signing_alg_values_supported": ["HS256",
	"HS384",
	"HS512",
	"RS256",
	"RS384",
	"RS512"],
	"claim_types_supported": ["normal"],
	"grant_types_supported": ["authorization_code",
	"implicit",
	"urn:ietf:params:oauth:grant-type:jwt-bearer",
	"client_credentials",
	"urn:ietf:params:oauth:grant_type:redelegate"],
	"scopes_supported": ["openid",
	"profile",
	"email",
	"address",
	"phone",
	"offline_access"],
	"userinfo_endpoint": "http://192.168.1.11:8080/openid-connect-server-webapp/userinfo",
	"userinfo_encryption_enc_values_supported": ["A192CBC-HS384",
	"A192GCM",
	"A256CBC+HS512",
	"A128CBC+HS256",
	"A256CBC-HS512",
	"A128CBC-HS256",
	"A128GCM",
	"A256GCM"],
	"op_tos_uri": "http://192.168.1.11:8080/openid-connect-server-webapp/about",
	"issuer": "http://192.168.1.11:8080/openid-connect-server-webapp/",
	"op_policy_uri": "http://192.168.1.11:8080/openid-connect-server-webapp/about",
	"claims_supported": ["sub",
	"name",
	"preferred_username",
	"given_name",
	"family_name",
	"middle_name",
	"nickname",
	"profile",
	"picture",
	"website",
	"gender",
	"zone_info",
	"locale",
	"updated_time",
	"birthdate",
	"email",
	"email_verified",
	"phone_number",
	"address"]
}

**Comment by karuatcsg** [comment]
But some more tinkering showed that the redirect URI's I had on OP and the ones in the apache config were not matching. Once I fixed it, the problem seems to have gone away.

I however request you to check the contents of `http://192.168.1.11:8080/openid-connect-server-webapp/.well-known/openid-configuration` just in case I am missing something.

Thank you!

**Comment by zandbelt** [comment]
seems OK to me
