### ISSUE TITLE
Support for Single Sign Out

### ISSUE THREAD

**Issue by karuatcsg** [pingidentity/mod_auth_openidc#46]
We set up an OAuth/OpenID Connect server and our application authenticates users against the OAuth/OpenID Connect server. We have an Apache web server that uses mod_auth_openidc and that Apache web server serves the content to authenticated users of our application.

When a user signs off/out from the application, we want the Apache server to stop serving the content. However mod_auth_openidc cookie on the user browser is valid even after revoking the access tokens on the OAuth/OpenID connect server. Is there a way for mod_auth_openidc to support "federated sign out" or "single sing out"? Any guidance is appreciated.

By the way we use

`OIDCProviderMetadataURL http://svr-IP/openid-connect-server/.well-known/openid-configuration`

in our Apache configuration.

thanks,
Karunakar

**Comment by zandbelt** [comment]
**mod_auth_openidc** supports OpenID Connect Session Management which includes Single Logout, see: https://github.com/pingidentity/mod_auth_openidc/wiki/Session-Management

If you can ensure that OpenID Connect Provider software supports Session Management, it should automatically be used when a user triggers logout as described in: https://github.com/pingidentity/mod_auth_openidc/wiki#9-how-do-i-logout-users

Note that revoking refresh tokens and access tokens on the Authorization Server will not logout users in the clients, that is the nature of federated single-sign-on. If you'd wanted to initiate SLO from the Authorization Server your would have to make sure that the "OP iframe" that is produced for Session Management by the Authorization Server periodically checks for some trigger that would initiated SLO through the OP's endpoint for that.

**Comment by karuatcsg** [comment]
Thank you, this helps.
