### ISSUE TITLE
Incorrect Google domain example claim hd:<your domain>

### ISSUE THREAD

**Issue by markwormgoor** [pingidentity/mod_auth_openidc#48]
The examples given in the documentation for using Google Apps domain accounts are incorrect, which took me quite a bit of googling/searching to correct. The example states the following is required:
  OIDCScope "openid profile"
  Require claim hd:&lt;your-domain&gt;

However, the hd claim is only returned if you ask for e-mail according too Google's documentation: https://developers.google.com/+/api/openidconnect/getOpenIdConnect. Hence, the correct example would be:
  OIDCScope "openid email"
  Require claim hd:&lt;your-domain&gt;

Note: I don't think profile is required for Google - or adds any value.

**Comment by zandbelt** [comment]
I must have got my wires crossed somewhere.., thanks

**Comment by markwormgoor** [comment]
Graag gedaan :).

Mark

2015-01-21 20:18 GMT+01:00 Hans Zandbelt <notifications@github.com>:

**Comment by zandbelt** [comment]
Insgelijks :+1:
