### ISSUE TITLE
problem in token endpoint with self signed certificates

### ISSUE THREAD

**Issue by jennyfurtado2** [pingidentity/mod_auth_openidc#56]
I am testing mod_auth_openidc in my local machine. I keep getting this error when retrieving the token
 
 [auth_openidc:error] [pid 468628:tid 2900] [client 127.0.0.1:52791] oidc_util_http_call: curl_easy_perform() failed on: https://localhost/auth/oidc/token (SSL certificate problem: self signed certificate)
[auth_openidc:warn] [pid 468628:tid 2900] [client 127.0.0.1:52791] oidc_proto_token_endpoint_request: error when calling the token endpoint (https://localhost/auth/v3/oidc/token)

Not sure if it is a real issue or some extra flag I need to set in http.conf

I am using mod_ssl and the following configs in the http.conf for mod_auth_openidc

      OIDCClientID mnWfbpfbOroRlOg1qlv49eN5jBMa
    OIDCClientSecret V1H9N67jSwiw0SvEl3eTzTgHH84a
    OIDCCryptoPassphrase Somepass
   	OIDCRedirectURI http://localhost/oidc/redirect_uri
    OIDCProviderAuthorizationEndpoint https://localhost/auth/oidc/auth
	OIDCProviderTokenEndpoint  https://localhost/auth/oidc/token
    
	OIDCProviderIssuer localhost/auth/oidc/auth
	<Location "/oidc/">
        AuthType openid-connect
        Require valid-user
    </Location>

**Comment by zandbelt** [comment]
That's because your OpenID Connect provider runs on localhost with a self-signed certificate. You'll need to disable SSL validation to make that work with:

    OIDCSSLValidateServer Off

Of course you should not use this in production.

**Comment by jennyfurtado2** [comment]
Thank you that was the flag I was looking for.
One issue I noticed is that when going to the tokenendpoint above it is not passing the clientID and the clientSecret. I added the flag OIDCResponseType "code token" and other combinations but none seems to work.

**Comment by zandbelt** [comment]
By default it passes the `client_id` and `client_secret` in the HTTP Basic Authorization header since that is what the spec demands. If you want to have the credentials presented as part of the post parameters you'll need to specify:

    OIDCProviderTokenEndpointAuth client_secret_post

**Comment by jennyfurtado2** [comment]
Thank you again setting that flag worked.
Yet another question: It seems the module doesnt support HmacSHA256 encryption for the JWT token (although the JWT spec says it should). Or maybe I am wrong here?

**Comment by zandbelt** [comment]
HmacSHA256 is supported where the Content Encryption Key is encrypted using RSAES-PKCS1-V1_5 or AES Key Wrap. mod_auth_openidc supports the minimal required set of encryption capabilities as defined in the JWT spec:

> Support for encrypted JWTs is OPTIONAL. If an implementation provides encryption capabilities,
> of the encryption algorithms specified in [JWA], only RSAES-PKCS1-V1_5 with 2048 bit keys 
> (RSA1_5), AES Key Wrap with 128 and 256 bit keys (A128KW and A256KW), and the composite
> authenticated encryption algorithm using AES CBC and HMAC SHA-2 (A128CBC-HS256 and
> A256CBC-HS512) MUST be implemented by conforming implementations.

**Comment by jennyfurtado2** [comment]
Thank you. I did encrypt it with AESKW 256. Then I built the JWT token in the json form ("." separate each
base64urlencode)
base64urlencode({"typ":"JWT","alg":"A256KW"}).
base64UrlEncode({"iss":"auth.test.com","sub":"UserIDHere","aud":"xyz.audience.test.com","iat":"1426271710","exp":1426272310}).
base64urlEncode([-12, 93, -79, 50, -97, -89, 124, 100, -78...])

after a few seconds apache crashes. In the logs I see 
[auth_openidc:error] [pid 1007240:tid 2308] [client 127.0.0.1:49399] oidc_util_decode_json_and_check_error: JSON parsing returned an error: '[' or '{' expected near '<'

**Comment by zandbelt** [comment]
I don't see encryption happening; it would be better to use an existing library for construction encrypted JWTs rather than constructing it yourself. You seem to produce a JWT that syntactically is a signed JWT (since it has 3 elements) but signals encryption in the header.

**Comment by jennyfurtado2** [comment]
I thought about using a lib but it seemed so easy to do it myself. I am following the example in section 3.1 of http://openid.net/specs/draft-jones-json-web-token-07.html almost to the letter

The array [-12,93, -79...] above is the byte version of the AESKW256 encrypted key. Probably I have some bug in this last step.

**Comment by zandbelt** [comment]
The example that you refer to is a signed JWT, not an encrypted JWT and it uses `{"alg":"HS256"}`. Besides that, that link is to an old and expired version of the draft. The latest - to-be-standardized - version is here: http://self-issued.info/docs/draft-ietf-oauth-json-web-token.html

**Comment by jennyfurtado2** [comment]
Does openidc support this signed format? I am imagining it cant because it would have to know which algorithm encoded the signature part of the token.

**Comment by zandbelt** [comment]
Yes it does, see: https://github.com/pingidentity/mod_auth_openidc/blob/master/test/test.c#L156

**Comment by jennyfurtado2** [comment]
Thank you so much. 

openidc now logs these errors when it gets the token

 [auth_openidc:error] [pid 1047372:tid 2904] [client 127.0.0.1:56059] oidc_proto_validate_nonce: id_token JSON payload did not contain a "nonce" string: [src\\jose\\apr_jwt.c:206: apr_jwt_get_string]: mandatory JSON key "nonce" could not be found\n

My payload/claims is simply
{"iss":"auth.test.com","sub":"UserIDHere","aud":"xyz.audience.test.com","iat":"1426271710","exp":1426272310}

do I need to add the nonce key? Where do I get it from? (it is not in the headers/post)

**Comment by zandbelt** [comment]
a `nonce` is sent in the authentication requests that mod_auth_openidc sends to OPs; by spec the OP is required to include the `nonce` as part of the `id_token` that is produced and sent back to the RP; the nonce allows for correlation of the session at the RP and the `id_token` produced by the OP, see: http://www.thread-safe.com/2011/08/openid-connect-nonce.html

so you can get the `nonce` value from the query parameters in the authorization request that mod_auth_openidc sends out

**Comment by jennyfurtado2** [comment]
Thank you again. Apache recieves the token and now I would like to send it to some endpoint were some processing could be done and will then login the user. I thought that was the purpose of OIDCProviderUserInfoEndpoint? Despite me having OIDCProviderUserInfoEndpoint https://localhost/auth/oidc/login it redirects to localhost/oidc/ (the <Location location).

**Comment by jennyfurtado2** [comment]
I need to use several different providers say
localhost/oidc/p1
localhost/oidc/p2
It seems the way to specify the proper urls is through OIDCMetadataDir. What goes in a file located in that directory?
Is it a series of 
OIDCRedirectURI for p1
OIDCProviderTokenEndpoint for p1
...
OIDCRedirectURI for p2
OIDCProviderTokenEndpoint for p2?

**Comment by zandbelt** [comment]
See: https://github.com/pingidentity/mod_auth_openidc#openid-connect-sso-with-multiple-openid-connect-providers

there are 3 types of files in there; the ones ending with `.provider` are regular OpenID Connect OP metadata as described in http://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata

please use the mailing list for `mod_auth_openidc@googlegroups.com` for asking questions; the Issues section is for bugs and feature requests

**Comment by jennyfurtado2** [comment]
Thanks Hans. I put a question on the mailing list on how to handle multiple providers coming from different urls.
