### ISSUE TITLE
500 error, state cookie not found

### ISSUE THREAD

**Issue by billsimon** [pingidentity/mod_auth_openidc#59]
```
[Thu Mar 26 13:57:47.562524 2015] [auth_openidc:error] [pid 18813] [client x.x.x.x] oidc_restore_proto_state: no "mod_auth_openidc_state_OY9IpBaBrzg-OKpkaw0OBTNm0BE" state cookie found
[Thu Mar 26 13:57:47.562596 2015] [auth_openidc:error] [pid 18813] [client x.x.x.x] oidc_unsolicited_proto_state: could not parse JWT from state: invalid unsolicited response: [src/jose/apr_jwt.c:172: apr_jwt_base64url_decode_object]: JSON parsing (json_loads) failed: unable to decode byte 0x8f near '9' (9\x8fH\xa4\x16\x81\xaf8>8\xaadk\r\x0e\x053f\xd0\x11)\n
[Thu Mar 26 13:57:47.562602 2015] [auth_openidc:error] [pid 18813] [client x.x.x.x] oidc_authorization_response_match_state: unable to restore state
```

I'm using mod_auth_openidc with Office 365/Azure AD. I get the errors above when I come back to a browser window or tab after it has been open for > 24 hours.

I thought there was a problem with the session storage. I had the aforementioned error when I was using "shm" so I changed to filesystem storage and get the same.

**Comment by billsimon** [comment]
Additionally, no amount of refreshing or changing the URL works. What happens is that the browser is redirected to the redirect URL defined in the mod_auth_openidc config and receives the 500 error. The only way to resolve the problem is to find the cookie on the client side and remove it.

**Comment by zandbelt** [comment]
which cookie do you need to remove to solve the issue?

**Comment by billsimon** [comment]
Good question. I don't know, because I am using Safari and I just have to
remove all cookies for a host or domain.

**Comment by zandbelt** [comment]
would you be able to share a browser trace: I need to see what the outgoing request and incoming response look like client side

**Comment by billsimon** [comment]
As I refreshed the screen with the debugger running, the request worked as expected. I didn't clear the cookies or manipulate the server in any way. So I'm not sure what happened here but I will try to capture it again next time. The problem has been affecting me since I configured this system several days ago. Thanks.

**Comment by zandbelt** [comment]
which version of mod_auth_openidc are you using and what settings have you configured?

**Comment by billsimon** [comment]
I'm working from the git master branch and currently at 929e739b559fd363e29184dcd9a18dcc16f1ddb6.

Here are the settings I have other than defaults:

```
grep -v "^#" auth_openidc.conf | grep -v "^$"
OIDCRedirectURI https://mysite/oauth2
OIDCCryptoPassphrase XXXXX
OIDCCookiePath /
OIDCClientID ...
OIDCClientSecret ...
OIDCProviderIssuer https://sts.windows.net/...
OIDCProviderAuthorizationEndpoint https://login.windows.net/...
OIDCProviderJwksUri https://login.windows.net/common/discovery/keys
OIDCProviderTokenEndpoint https://login.windows.net/...
OIDCProviderTokenEndpointAuth client_secret_post
OIDCProviderUserInfoEndpoint https://login.windows.net/...
OIDCProviderEndSessionEndpoint https://login.windows.net/...
OIDCCacheType file
OIDCCacheDir /var/cache/apache2/mod_auth_openidc/cache
OIDCSessionInactivityTimeout 86400
OIDCRemoteUserClaim upn
```

**Comment by zandbelt** [comment]
I will try and reproduce this behaviour as well.

Two remarks about your setup:
- you're better off using a single `OIDCMetadataURL https://sts.windows.net/<tenantid>/.well-known/openid-configuration` statement replacing all of the `OIDCProvider*` settings
- I believe sticking to a relatively short `OIDCSessionInactivityTimeout` and setting `OIDCSessionMaxDuration` to 24 hours achieves the required behavior in a more secure way

**Comment by zandbelt** [comment]
I was not able to reproduce this behavior so far; any news from your side?

**Comment by billsimon** [comment]
Sorry to keep you waiting. It now happens inconsistently and I can't figure out the pattern. I'm going to play with different timings and see what happens.

**Comment by billsimon** [comment]
The problem seems to be gone after following your suggestions about how to set the OIDCSessionInactivityTimeout and OIDCSessionMaxDuration values.
