### ISSUE TITLE
Question: Does the module support Role Based Authorization

### ISSUE THREAD

**Issue by harryyeh** [pingidentity/mod_auth_openidc#60]
Great work on this module, I have it working with Google Authentication when logging in. However, I don't want everyone in the domain example.com to have access to the site, only people in specific group. Essentially wanted to know if the module supports RBAC (role based access control)

For example the domain is example.com and the group name in google we have created is developers. Is it possible to do this?

Thanks

**Comment by zandbelt** [comment]
Unfortunately accessing group information needs to be done with an separate Google specific call to the Google Directory API which is not part of the OpenID Connect standardized APIs and as such is not implemented in mod_auth_openidc (and won't be either unless someone adds it in a Google specific branch).
