### ISSUE TITLE
Session timeout - Invalid request towards redirect url

### ISSUE THREAD

**Issue by norrs** [pingidentity/mod_auth_openidc#61]
I noticed I got this in my redirect url: 

```
https://admin.example.net/redirect_uri?state=foo&code=randomlonghash#/dashboard/error-logs?_g=()&_a=(filters:!((meta:(disabled:!t,index:%5B...
```

which mod_auth_openidc says is invalid request towards redirect url.
I assume this is due to the fragment[1] not being stripped?
Where fragment is `#/dashboard/error-logs?_g=()&_a=(filters:!((meta:(disabled:!t,index:%5B..."`

[1] http://en.wikipedia.org/wiki/URI_scheme#Examples

**Comment by zandbelt** [comment]
yes, a fragment should be stripped in/by the browser and not end up on the server side; something fishy is going on in the browser/client, see http://stackoverflow.com/questions/9384373/do-browsers-remove-in-url-automatically

**Comment by norrs** [comment]
Ah, browser bug then.

Leaving this here as well, as this popped up in the logs:
```
 oidc_util_json_string_print: oidc_util_check_json_error: response contained an "error" entry with value: ""internal_failure"", referer: https://protected-vhost-reverse-proxy.example.net:4xxx/
 oidc_proto_resolve_code_and_validate_response: failed to resolve the code, referer: https://protected-vhost-reverse-proxy.example.net:4xxx/
```

**Comment by norrs** [comment]
@zandbelt :  seems like it's been a long lasting bug for chrome users, the simplest test even fails.. http://greenbytes.de/tech/tc/datauri/#simplewfrag   (which is more or less in use by every javascript application..)

https://code.google.com/p/chromium/issues/detail?id=123004 
https://bugs.webkit.org/show_bug.cgi?id=68089

Taking this into consideration, is this something you want to temporarily be nice and fix on your side in mod_auth_openidc?

I guess it is no fun to have URI scheme parsing in your module, but I have to admit this is kinda a deal breaker if you want to protect javascript applications. 

A sad day for broken browsers :'(

**Comment by zandbelt** [comment]
hmm, I'm actually OK with fixing that in mod_auth_openidc; if you could provide a patch that would be even better :-)

**Comment by norrs** [comment]
Seems like apache[1] has some internals available for URI parsing, so I'll see if I can give it a peak later tonight.

http://docstore.mik.ua/orelly/apache_mod/158.htm

**Comment by zandbelt** [comment]
Can you paste your Apache log with debugging turned on? I can't reproduce this because the fragment seems to stripped off correctly by apache itself (or I have a different Chrome version that works).

**Comment by norrs** [comment]
I've enabled debug now, I'll see what happens after session timeout. (as I assume that is what is triggering it). 
We're still on apache 2.2 branch.. might be related to that?

**Comment by norrs** [comment]
I'm having difficulties reproducing the error as well @zandbelt...
I'll leave debug on a bit and see if I'm able to reproduce it.
