### ISSUE TITLE
curl_easy_escape  errror

### ISSUE THREAD

**Issue by Tomrunning8** [pingidentity/mod_auth_openidc#62]
Hope you can provide some advise to my problem below.

I am having problem loading the mod_auth_openidc.so
Below is the error when I try to load Apache.

httpd: Syntax error on line 175 of /usr/local/httpd/conf/httpd.conf: Cannot load modules/mod_auth_openidc.so into server: /usr/local/httpd/modules/mod_auth_openidc.so: undefined symbol: curl_easy_escape

This is what I use to build and it seem to work with no errors.
./configure --with-apxs2=/usr/local/httpd/bin/apxs CURL_CFLAGS=/usr/local/bin CURL_LIBS=/usr/local/lib

/usr/local/bin  is where the curl binary that I just build today.
/usr/local/lib is where the curl library that I just build today.

Thank you.
Y

**Comment by zandbelt** [comment]
You should most probably use `CURL_CFLAGS=-I/opt/local/include` and `-L/opt/local/lib -lcurl` assuming that libcurl cannot be found by pkg-config automatically.

**Comment by Tomrunning8** [comment]
OS= Redhat 7.1 EN


These are my build options:
./configure --with-apxs2=/usr/local/httpd/bin/apxs CURL_CFLAGS=/usr/local/curl/include CURL_LIBS=/usr/local/curl/lib/ OPENSSL_CFLAGS=/usr/local/openssl/include OPENSSL_LIBS=/usr/local/openssl/lib APR_CFLAGS=/usr/local/lib64/apr/include APR_LIBS=/usr/local/lib64/apr/lib JANSSON_CFLAGS=/usr/local/jansson/include JANSSON_LIBS=/usr/local/jansson/lib

These are what it come back with:
checking for pkg-config... /bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for CURL... yes
checking for OPENSSL... yes
checking for APR... yes
checking for JANSSON... yes
checking for PCRE... yes
checking for HIREDIS... no
configure: creating ./config.status
config.status: creating Makefile


These are some of the warning while running make:  But not error at the end of the make.
gcc: warning: /usr/local/openssl/include: linker input file unused because linking not done
gcc: warning: /usr/local/curl/include: linker input file unused because linking not done
gcc: warning: /usr/local/jansson/include: linker input file unused because linking not done

Thanks,
Y

**Comment by zandbelt** [comment]
There's a binary package for Centos7 on the Releases page. There's also a Dockerfile that shows how to build the package on Redhat/CentOS 7 here: https://github.com/zandbelt/mod-auth-openidc-dist/blob/master/centos/7/build/Dockerfile You should not need to provide the environment variables manually if you've installed the required "-devel" packages

**Comment by Tomrunning8** [comment]
I am using Redhat 7.1 OS distribution but all my Apache, APR, Openssl was manually build with the latest  release.  It is bit customize to meet our Web server requirements.  

Any ideas where to start looking for the problem?
Cannot load modules/mod_auth_openidc.so into server: /usr/local/httpd/modules/mod_auth_openidc.so: undefined symbol: curl_easy_escape


The config.log seems to indicate that it find all the nescessary path and pkg for CURL
config.log:  $ ./configure --with-apxs2=/usr/local/httpd/bin/apxs CURL_CFLAGS=/usr/local/curl/include CURL_LIBS=/usr/local/curl/lib/ OPENSSL_CFLAGS=/usr/local/openssl/include OPEN          SSL_LIBS=/usr/local/openssl/lib APR_CFLAGS=/usr/local/lib64/apr/include APR_LIBS=/usr/local/lib64/apr/lib JANSSON_CFLAGS=/usr/local/jansson/include JANSSON_LIBS=/usr/local/jansson          /lib
config.log:PATH: /usr/local/curl
config.log:PATH: /usr/local/curl/lib
config.log:PATH: /usr/local/curl/include
config.log:ac_cv_env_CURL_CFLAGS_value=/usr/local/curl/include
config.log:ac_cv_env_CURL_LIBS_value=/usr/local/curl/lib/
config.log:pkg_cv_CURL_CFLAGS=/usr/local/curl/include
config.log:pkg_cv_CURL_LIBS=/usr/local/curl/lib/
config.log:CURL_CFLAGS='/usr/local/curl/include'
config.log:CURL_LIBS='/usr/local/curl/lib/'

Thanks,
Y

**Comment by zandbelt** [comment]
You're passing directory paths in the environment variables, but they should be linker flags that consist of a combination of compiler specific options as in: `CURL_CFLAGS="-I/opt/local/include"` and `"CURL_LIBS=-L/opt/local/lib -lcurl"` etc.

**Comment by Tomrunning8** [comment]
The error is coming from ../src/util.c  file.
However, I am not quite sure what need to be done to fix the error.

Regarding the linker flags:  Is this what I need to use?
./configure --with-apxs2=/usr/local/httpd/bin/apxs CURL_CFLAGS="-I/usr/local/curl/include" "CURL_LIBS=-L/usr/local/curl/lib -lcurl  ??

Thanks,
Y

**Comment by zandbelt** [comment]
yes, with a closing double-quote after -lcurl

**Comment by Tomrunning8** [comment]
I have modified the build options as follow: and all the Linker warning gone away.

./configure --with-apxs2=/usr/local/httpd/bin/apxs CURL_CFLAGS="-I/usr/local/curl/include" "CURL_LIBS=-L/usr/local/curl/lib -lcurl" OPENSSL_CFLAGS="-I/usr/local/openssl/include" "OPENSSL_LIBS=-L/usr/local/openssl/lib/openssl -lopenssl" APR_CFLAGS=-I/usr/local/lib64/apr/include "APR_LIBS=-L/usr/local/lib64/apr/lib -lapr" JANSSON_CFLAGS=-I/usr/local/jansson/include "JANSSON_LIBS=-L/usr/local/jansson/lib -ljansson"

But I got a new errors:  Here is the last line:
/session.lo src/authz.lo src/util.lo src/config.lo src/crypto.lo src/proto.lo src/oauth.lo src/cache/lock.lo src/cache/shm.lo src/cache/memcache.lo src/cache/file.lo src/mod_auth_openidc.lo
/bin/ld: cannot find -lopenssl
collect2: error: ld returned 1 exit status
apxs:Error: Command failed with rc=65536
.
make: *** [src/mod_auth_openidc.la] Error 1

**Comment by zandbelt** [comment]
I guess your path is "/usr/local/openssl/lib" instead of "/usr/local/openssl/lib/openssl"? I'd also add "-lcrypto", so: `OPENSSL_LIBS="-L/usr/local/openssl/lib -lopenssl -lcrypto"`

**Comment by Tomrunning8** [comment]
Here are some of the extract data from the config.log file.
It seems not able to find information for PCRE and APXS2_OPTS.

Any suggestion? 
collect2: error: ld returned 1 exit status
apxs:Error: Command failed with rc=65536


  

## ----------- ##
## Core tests. ##
## ----------- ##
configure:2367: checking for PCRE
configure:2374: $PKG_CONFIG --exists --print-errors "libpcre"
configure:2377: $? = 0
configure:2391: $PKG_CONFIG --exists --print-errors "libpcre"
configure:2394: $? = 0


## ---------------- ##
## Cache variables. ##
## ---------------- ##
ac_cv_env_APR_CFLAGS_set=set
ac_cv_env_APR_CFLAGS_value=-I/usr/local/lib64/apr/include
ac_cv_env_APR_LIBS_set=set
ac_cv_env_APR_LIBS_value='-L/usr/local/lib64/apr/lib -lapr'
ac_cv_env_APXS2_OPTS_set=
ac_cv_env_APXS2_OPTS_value=
ac_cv_env_CURL_CFLAGS_set=set
ac_cv_env_CURL_CFLAGS_value=-I/usr/local/curl/include
ac_cv_env_CURL_LIBS_set=set
ac_cv_env_CURL_LIBS_value='-L/usr/local/curl/lib -lcurl'
ac_cv_env_HIREDIS_CFLAGS_set=
ac_cv_env_HIREDIS_CFLAGS_value=
ac_cv_env_HIREDIS_LIBS_set=
ac_cv_env_HIREDIS_LIBS_value=
ac_cv_env_JANSSON_CFLAGS_set=set
ac_cv_env_JANSSON_CFLAGS_value=-I/usr/local/jansson/include
ac_cv_env_JANSSON_LIBS_set=set
ac_cv_env_JANSSON_LIBS_value='-L/usr/local/jansson/lib -ljansson'
ac_cv_env_OPENSSL_CFLAGS_set=set
ac_cv_env_OPENSSL_CFLAGS_value=-I/usr/local/openssl/include/openssl
ac_cv_env_OPENSSL_LIBS_set=set
ac_cv_env_OPENSSL_LIBS_value='-L/usr/local/openssl/lib -lopenssl'
ac_cv_env_PCRE_CFLAGS_set=
ac_cv_env_PCRE_CFLAGS_value=
ac_cv_env_PCRE_LIBS_set=
ac_cv_env_PCRE_LIBS_value=


pkg_cv_APR_CFLAGS=-I/usr/local/lib64/apr/include
pkg_cv_APR_LIBS='-L/usr/local/lib64/apr/lib -lapr'
pkg_cv_CURL_CFLAGS=-I/usr/local/curl/include
pkg_cv_CURL_LIBS='-L/usr/local/curl/lib -lcurl'
pkg_cv_JANSSON_CFLAGS=-I/usr/local/jansson/include
pkg_cv_JANSSON_LIBS='-L/usr/local/jansson/lib -ljansson'
pkg_cv_OPENSSL_CFLAGS=-I/usr/local/openssl/include/openssl
pkg_cv_OPENSSL_LIBS='-L/usr/local/openssl/lib -lopenssl'
pkg_cv_PCRE_CFLAGS=' '
pkg_cv_PCRE_LIBS='-lpcre  '


## ----------------- ##
## Output variables. ##
## ----------------- ##

APR_CFLAGS='-I/usr/local/lib64/apr/include'
APR_LIBS='-L/usr/local/lib64/apr/lib -lapr'
APXS2='/usr/local/httpd/bin/apxs'
APXS2_OPTS=''
CURL_CFLAGS='-I/usr/local/curl/include'
CURL_LIBS='-L/usr/local/curl/lib -lcurl'
JANSSON_CFLAGS='-I/usr/local/jansson/include'
JANSSON_LIBS='-L/usr/local/jansson/lib -ljansson'
OPENSSL_CFLAGS='-I/usr/local/openssl/include/openssl'
OPENSSL_LIBS='-L/usr/local/openssl/lib -lopenssl'

**Comment by zandbelt** [comment]
My suggestion would be to use the prebuilt binary from the releases page and make sure that you include the path to the special built libraries in to the LD_LIBRARY_PATH before the paths to the regular versions of those libraries.
