### ISSUE TITLE
How to go from here?

### ISSUE THREAD

**Issue by Tomrunning8** [pingidentity/mod_auth_openidc#63]
Need some guidance and direction where to go from here with mod_auth_openidc.

I got Apache and mod_auth_openidc work, sent request and login to OP (Gluu).
OP (Gluu) sent back the following information on the browser header.

Can you give example on how to gather the tokenID and claims\scopes claim that send back from the openID connect provider?  I am not quite sure how to go about it.  

The following strings of information was sent by the Gluu OP server.
https://www.webserver.com/redirect/redirect.html?session_id=3d780f84-0d4a-4a14-9404-1111835e0376&scope=&state=TuZMdWIMasuDsCKZUslBIuEXrBw&code=5091a225-4614-4b74-8522-3dc12cb01c17

As you can see if did not include any claims\scopes.
what is the mod_auth_openidc's syntax and options to request OP to send back all the claims\scopes available for this client?

What I am looking for to do is to capture the returned TokenID, UserID and Claims\scopes information and make decision on how to control my application's access based on those information.   Is this something I can achieve with openid connect?    Perhaps, with some server side language to capture the information and process it (this is where is I am stuck due to not knowing how the information present back from the OP in what form? and in what form the information hold by the Mod_auth_openidc or RP)

Any ideas and hints to go from here will be greatly appreciate.

Thank you.
Y

**Comment by zandbelt** [comment]
Use the `OIDCScope` primitive to configure the requested scopes. You can find out what scopes the OP supports by looking at the Discovery metadata document for your OP, e.g. `https://seed.gluu.org/.well-known/openid-configuration` has:

    "scopes_supported": [
        "address",
        "user_name",
        "email",
        "http://docs.kantarainitiative.org/uma/scopes/prot.json",
        "uma_authorization",
        "uma_protection",
        "http://docs.kantarainitiative.org/uma/scopes/authz.json",
        "openid",
        "clientinfo",
        "myScope",
        "profile",
        "phone"
    ],

Assuming that your `/redirect/` path is setup as the `OIDCRedirectURI` and it is protected by the module, the module will pickup the `id_token` and pass the information in there as HTTP headers to your application.

**Comment by Tomrunning8** [comment]
This is what I have defined in the auth_openidc.conf

OIDCScope "email user_name orderV"
Is that a right format and syntax.

Following are what available from Gluu OP:
"scopes_supported": [
        "http://docs.kantarainitiative.org/uma/scopes/authz.json",
        "uma_protection",
        "phone",
        "user_name",
        "profile",
        "orderV",
        "openid",
        "email",
        "uma_authorization",

**Comment by zandbelt** [comment]
See the docs from here: https://github.com/pingidentity/mod_auth_openidc/blob/master/auth_openidc.conf#L172

The syntax is correct, but it should also contain the "openid" scope.

**Comment by Tomrunning8** [comment]
Sorry,  this is what I had defined in the configuration:
OIDCScope "openid email iname profile orderV"

Regarding to my previous question, trying to understand how data exchange and presenting.
Would you say that Gluu and Mod_auth_openidc send data back and forth via the HTTP and HTTPs
header?  meaning all data encapsulate within the HTTP or HTTPs header?

If that is the case, I can write or select a language to parse those data from the HTTP or HTTPs header (jason or javascript??).
Am I in the right path on how to tackle this problem?

Thank you so much for your assistance.
Y

**Comment by zandbelt** [comment]
Gluu and mod_auth_openidc send data back and forth in HTTP Redirect, POST and backchannel messages according to the OpenID Connect protocol. This is if lesser concern to you. The result is that the verified user identity data is passed in HTTP Headers to you application. If your application is a Java application you can interpret the headers there. The overall functionality is described here: https://github.com/pingidentity/mod_auth_openidc/blob/master/README.md

**Comment by Tomrunning8** [comment]
These are what I have defined in the auth_openidc.conf
Are these the basic requirements to get scopes\claims back from the Gluu provider?

Everything else in auth_openidc.conf are commend out except the following lines:
************************************************************************************************************
OIDCRedirectURI https://www.MyWWW.com/redirect/redirect.html
OIDCCryptoPassphrase mypassword
OIDCProviderAuthorizationEndpoint https://idm.MyWWW.com/oxauth/seam/resource/restv1/oxauth/authorize
OIDCProviderTokenEndpoint https://idm.MyWWW.com/oxauth/seam/resource/restv1/oxauth/token
OIDCProviderTokenEndpointAuth client_secret_basic
OIDCProviderUserInfoEndpoint https://idm.MyWWW.com/oxauth/seam/resource/restv1/oxauth/userinfo
OIDCClientID @!C032.849B.2FA5.5E8C!0001!BCB6.4A42!0008!4ACB.875B
OIDCClientSecret 987654321
OIDCScope "openid email iname profile"

<Location /example/>
   AuthType openid-connect
   Require valid-user
   LogLevel debug
</Location>
***************************************************************************

I am assuming Gluu OP will passed in http header back to the redirect URI then our application using Java to interpret the header there?


Thank you for clear my lack of understanding.
Y

**Comment by Tomrunning8** [comment]
Suppose to look like these

<Location /example/>
   AuthType openid-connect
   Require valid-user
   LogLevel debug
</Location>

**Comment by zandbelt** [comment]
As documented here https://github.com/pingidentity/mod_auth_openidc/blob/master/auth_openidc.conf#L11, your `OIDCRedirectURI` must be a "vanity" URL that is protected by the module. So you'd better use: ` https://www.MyWWW.com/example/redirect_uri`
