### ISSUE TITLE
Issue regarding using request token with Reponse type : code

### ISSUE THREAD

**Issue by Anikynetix** [pingidentity/mod_auth_openidc#64]
Hello!

In order to set up a basic client implementation, the module was configured with necessary endpoints, client id, client secret along with Response type of "code".

The state and code are in the url. However, I could use your input on how to use that to request id_token/access_token using the apache module.

Thanks.

========================================

The url query looks somewhat like this:

http://<mydomain>/redirect/?session_id=993bcd3d-c431-46bc-8045-bae60edf88d4&scope=openid+email+profile&state=7pZmHSjnM-EbcJrEZFR8uZuFot0&code=4bcddcca-b511-4bcc-bb48-b758adeee101

The module is configured in the following manner:

OIDCRedirectURI http://<mydomain>/redirect
OIDCCryptoPassphrase 123456789

OIDCProviderIssuer https://<my domain>
OIDCProviderAuthorizationEndpoint https://<my domain>/oxauth/seam/resource/restv1/oxauth/authorize
OIDCProviderJwksUri https://<my domain>/oxauth/seam/resource/restv1/oxauth/jwks
OIDCProviderTokenEndpoint https://<my domain>/oxauth/seam/resource/restv1/oxauth/token
OIDCProviderTokenEndpointAuth client_secret_post
OIDCProviderUserInfoEndpoint https://<my domain>/oxauth/seam/resource/restv1/oxauth/userinfo

OIDCSSLValidateServer Off
OIDCResponseType "code"

OIDCClientID @!C032.849B.2FA5.5E8C!0001!BCB6.4A42!0008!D0AC.C912
OIDCClientSecret 123456789123456789123456789
OIDCScope "openid email profile"

OIDCOAuthClientID @!C032.849B.2FA5.5E8C!0001!BCB6.4A42!0008!D0AC.C912
OIDCOAuthClientSecret 123456789123456789123456789
OIDCOAuthIntrospectionEndpoint https://<my domain>/oxauth/seam/resource/restv1/introspection
OIDCOAuthIntrospectionEndpointMethod POST
OIDCOAuthIntrospectionEndpointAuth client_secret_basic
OIDCOAuthSSLValidateServer Off

<Location /example/>
AuthType openid-connect
Require valid-user
LogLevel debug
</Location>

<Location /redirect/>
AuthType openid-connect
#Require valid-user
LogLevel debug
</Location>

**Comment by zandbelt** [comment]
The module should pickup the `code`, use that so-called code grant in a backchannel call to the OP to get the `id_token` and `access_token` and supply the resulting claims as HTTP header values to you application. If that is not happening for you, it would be best to turn up the `LogLevel` and analyze/paste the logs here.

**Comment by zandbelt** [comment]
any progress/update on this?

**Comment by Anikynetix** [comment]
Hi,

Seems to be okay now. Haven't been able to produce the error afterwards.

Thanks.
