### ISSUE TITLE
Username without the domain?

### ISSUE THREAD

**Issue by mweidman2** [pingidentity/mod_auth_openidc#67]
The REMOTE_USER seems to always include the @domain.com portion which is an issue when logging into applications which rely on this username because it will show up as a brand new user. Is there an easy way to strip the @domain.com portion from the REMOTE_USER right after authentication? Thanks

**Comment by zandbelt** [comment]
In 1.8.2 a feature was added that allows you to apply a regular expression to the claim that is used to set the remote user. See the docs for `OIDCRemoteUserClaim` in https://github.com/pingidentity/mod_auth_openidc/blob/master/auth_openidc.conf

**Comment by mweidman2** [comment]
Oh, looks like a recent change? Thanks a lot for the fast response, I should have checked to see if there was a new version. The module is great so thanks for your hard work.

**Comment by zandbelt** [comment]
no problem, thanks for making this new feature more visible and searchable ;-)
