### ISSUE TITLE
Can the mod_auth_openidc be configured to return a Authorization: Bearer header in redirect response?

### ISSUE THREAD

**Issue by bertramn** [pingidentity/mod_auth_openidc#69]
I was wondering if mod_auth_openidc can be configured to return a standard `Authorization: Bearer [jwtToken]` Header in the response to the User Agent after the 302 redirect from the Identity Provider?

I am talking about the mod url mapping configured by `OIDCRedirectURI` : `https://[server]/example/redirect_uri`.

I can see the jwtToken is sent as a request header `OIDC_access_token` to the protected application but other than the `mod_auth_openidc_session` cookie in the Response to the user agent there is nothing a javascript application running in the user agent can use to make subsequent XHR requests with a standard `Authorization: Bearer` header.

This is required when building single page applications such as AngularJS which run solely in the clients browser and need to communicate Authorization context to REST services that may not be protected by the mod_auth_openidc but are capable of validating the JWT against the same issuer.

**Comment by bertramn** [comment]
I tried copying the `OIDC_access_token` header and construct a `Authorization: Bearer` on the way out but that did not work :(

```apache
SetEnvIf ^OIDC_access_token$ (.*) AuthTokenFound
SetEnvIf ^OIDC_access_token$ "(.+)" AuthToken=$1
# only add header if the OIDC_access_token is present
SetEnvIf Header add Authorization "Bearer %{AuthToken}e" env=AuthTokenFound
```

**Comment by zandbelt** [comment]
Setting `Authorization: Bearer [token]` in a Headers seems backwards: this header is used to authorize the Client accessing the Resource Server and not the other way around. (I believe your attempt would also put the header in the Request, not the Response).  Putting it in another header that is actually returned in the Response may be more suitable, but I'm not sure the module needs to do that. After all you generate the Javascript yourself; it would not be too hard to pickup the `OIDC_access_token` value and include it in the Javascript returned to the browser.

**Comment by bertramn** [comment]
The User Agent will send the `Authorization` header once presented with it. The single page web application is typically code served by an apache from a protected location. Any JavaScript part of this application runs in the User Agent hence would never see the `OIDC_access_token` header from the server side communication since it is scrubbed. However if the javascript application in the browser would want to get data from an API that is also protected and accepts the same issuer issued claims then a Authorization header would need to be sent there. I tried to draw it up below, hope that this clarifies this question a bit more (I left out the 2 auth redirects to keep it as simple as possible).

![security auth jwt](https://cloud.githubusercontent.com/assets/3828133/7897261/718c719e-0718-11e5-93d9-ac9eaab1db8a.png)

**Comment by bertramn** [comment]
Also `Header add / set` will add response headers as per apache documentation http://httpd.apache.org/docs/2.2/mod/mod_headers.html. But I think when this code runs the server side `OIDC_access_token` header is probably already scrubbed.

**Option 1**
the mod_auth_openidc would set an environment variable on a per request basis and then one would be able to simply add a directive like this into the apache configuration to return the issued token to the client browser.

```apache
SetEnvIf Header set Authorization "Bearer %{OIDCAuthToken}e" env=OIDCAuthToken
```

**Option 2**
a configuration directive for the module to add an `Authorization: Bearer [token]` header to the response sent back to the client whenever this `mod_auth_openidc_session` cookie is sent would probably be more consistent:
```apache
<Location "/e">
  OIDCReturnBearerToken true
  AuthType openid-connect
  ...
</Location>
```

Are one of these options doable?

**Comment by zandbelt** [comment]
Option 1 would not work for the same reason that using the header does not work: `mod_auth_openidc` only does its work after the `SetEnvIf` is executed. You may be able to make this work by appying a workaround as mentioned in: https://github.com/pingidentity/mod_auth_openidc/issues/55#issuecomment-77259613

But: my previous point was that the Javascript may run in the user agent, but is served up by the backend. That backend *does* receive the `OIDC_access_token` header so it should be doable to pick it up on the backend and include it in the Javascript that is returned to the browser.

**Comment by zandbelt** [comment]
After some fiddling, I was able to make Option 1 work for me in the following way:

    <Location "/protected/">
      AuthType openid-connect

      RewriteEngine On
      # a catchall that will incur an internal redirect, hitting the same path again with REDIRECT_PASS set
      RewriteCond %{ENV:REDIRECT_PASS} !1
      RewriteRule .* $1 [L,E=PASS:1]

      # this code is only executed the 2nd time around when the mod_auth_openidc headers/environment will have been set
      Header set Authorization "Bearer %{HTTP_OIDC_ACCESS_TOKEN}e" env=HTTP_OIDC_ACCESS_TOKEN

      Require valid-user
    </Location>

**Comment by istvano** [comment]
Hello,

I have tried this code with the latest version with Apache 2.4 but did not seem to work. I had to change it the following way.
	<Location "/protected">
		AuthType openid-connect
		Header set Authorization "Bearer %{OIDC_ACCESS_TOKEN}e" env=OIDC_ACCESS_TOKEN
		Require valid-user		
	</Location>

I am just adding this here as someone might need it in the future. is there a particular reason why the environment variables do not have the HTTP prefix anymore ?

**Comment by zandbelt** [comment]
See also: See also: https://github.com/pingidentity/mod_auth_openidc/issues/132#issuecomment-282280141

**Comment by dementiacs** [comment]
I couldn't even get it to work using either
Header set Authorization "Bearer %{HTTP_OIDC_ACCESS_TOKEN}e" env=HTTP_OIDC_ACCESS_TOKEN

or 

Header set Authorization "Bearer %{OIDC_ACCESS_TOKEN}e" env=OIDC_ACCESS_TOKEN

and I am using a value of "both" for OIDCPassClaimsAs

**Comment by zandbelt** [comment]
Case matters in environment variables:
```
Header set Authorization "Bearer %{OIDC_access_token}e" env=OIDC_access_token
```
should work.

**Comment by Bodhisatya1** [comment]
[We have deployed mod_auth_openidc-2.3.8-apache-2.4.x-win64 (openidc module) on Apache server. We have a jsp page deployed on Tomcat which is proxied by the Apache server. We intend to receive the access token on this jsp page either is the header or as JSON response. Please advise. The oidc.conf is pasted below.
[httpd.zip](https://github.com/zmartzone/mod_auth_openidc/files/2625001/httpd.zip)
