### ISSUE TITLE
Token Validation Issue ( oidc_proto_parse_idtoken: id_token payload could not be validated )

### ISSUE THREAD

**Issue by FadelChafai** [pingidentity/mod_auth_openidc#73]
Hi
I am attempting to configure my hosted WP server as the OIDC provider, after redirection I have this error :
The OpenID Connect Provider returned an error: Error in handling response type.

This is the log messages :

[Mon Jun 08 10:58:01.446166 2015] [auth_openidc:debug] [pid 21877] src/proto.c(297): [client IP:54585] oidc_proto_validate_nonce: nonce "XrZpDMbUsTEBBbZcoLTEZVncMCEoWcdnEHa19kOIT-o" validated successfully and is now cached for 1210 seconds, referer: https://openid-dev.myWpServer.com/wp-login.php?redirect_to=%2Foauth%2Fauthorize%2F%3Fresponse_type%3Dcode%26scope%3Dopenid%2520email%2520profile%26client_id%3DwlKzFJcEEaHTRn7sddsiIMABzPNT3g%26state%3DdzOj06-VLByK3wyLwyt9dABMn0g%26redirect_uri%3Dhttps%253A%252F%252Fps.dev%252Fadmin%252Fauth.php%26nonce%3DXrZpDMbUsTEBBbZcoLTEZVncMCEoWcdnEHa19kOIT-o

[Mon Jun 08 10:58:01.446217 2015] [auth_openidc:error] [pid 21877] [client IP:54585] oidc_proto_validate_iat: "iat" validation failure (%ld): JWT was issued more than 1434320104 seconds in the future, referer: https://openid-dev.myWpServer.com/wp-login.php?redirect_to=%2Foauth%2Fauthorize%2F%3Fresponse_type%3Dcode%26scope%3Dopenid%2520email%2520profile%26client_id%3DwlKzFJcEEaHTRn7sddsiIMABzPNT3g%26state%3DdzOj06-VLByK3wyLwyt9dABMn0g%26redirect_uri%3Dhttps%253A%252F%252Fps.dev%252Fadmin%252Fauth.php%26nonce%3DXrZpDMbUsTEBBbZcoLTEZVncMCEoWcdnEHa19kOIT-o

[Mon Jun 08 10:58:01.446297 2015] [auth_openidc:error] [pid 21877] [client IP:54585] oidc_proto_parse_idtoken: id_token payload could not be validated, aborting, referer: https://openid-dev.myWpServer.com/wp-login.php?redirect_to=%2Foauth%2Fauthorize%2F%3Fresponse_type%3Dcode%26scope%3Dopenid%2520email%2520profile%26client_id%3DwlKzFJcEEaHTRn7sddsiIMABzPNT3g%26state%3DdzOj06-VLByK3wyLwyt9dABMn0g%26redirect_uri%3Dhttps%253A%252F%252Fps.dev%252Fadmin%252Fauth.php%26nonce%3DXrZpDMbUsTEBBbZcoLTEZVncMCEoWcdnEHa19kOIT-o

Here is my config :

        OIDCProviderMetadataURL https://openid-dev.myWpServer.com/.well-known/openid-configuration/
        OIDCProviderTokenEndpointAuth client_secret_post
        OIDCSSLValidateServer Off
        OIDCClientID wlKzFJcEEaHTRn7sddsiIMABzPNT3g
        OIDCClientSecret …………………………………………………..
        OIDCScope "openid email profile"
 
        OIDCRedirectURI https://ps.dev/admin/auth.php
        OIDCCryptoPassphrase presstalis
        OIDCCookiePath /admin
        <Location /admin>
           AuthType openid-connect
           Require valid-user
           LogLevel debug
        </Location>

libapache2-mod-auth-openidc_1.8.2-1ubuntu1.trusty.1_amd64.deb
ubuntu 14

Thank you

**Comment by zandbelt** [comment]
token validation fails because the `iat` ("issued at") timestamp is too far off; this usually indicates a clock drift between the sender and the receiver; please check the data/time settings on both machines and the `iat` value in the JWT

**Comment by FadelChafai** [comment]
Thank you Hans

**Comment by FadelChafai** [comment]
Hi,

After i get access to my protected area, How i can get the access_token to request the user informations from  https://openid-dev.myWpServer.com/oauth/me/ ?

Thank you

**Comment by zandbelt** [comment]
Please send this type of questions to the mailing list; it does not belong on the issue tracker.

The access token is available to the application in the header `OIDC_access_token`. Depending on the Authorization Server you can get the scopes by executing a token introspection call.
