### ISSUE TITLE
Expose id_token as HTTP header

### ISSUE THREAD

**Issue by nynymike** [pingidentity/mod_auth_openidc#75]
This is a feature request B-)

Perhaps it would be easier to just create a HTTP Header for the id_token. Or maybe its already there somewhere? But what if the OpenID Connect OP has custom scopes or user claims? 

Also, a 1:1 mapping of user claims to headers seems like its just harder to parse than providing the json entry itself.

**Comment by zandbelt** [comment]
See `OIDCPassIDTokenAs ` here: https://github.com/pingidentity/mod_auth_openidc/blob/master/auth_openidc.conf#L497

**Comment by nynymike** [comment]
Hans, you rock!
