### ISSUE TITLE
Return access token to user agent in response header or cookie

### ISSUE THREAD

**Issue by bertramn** [pingidentity/mod_auth_openidc#76]
Would you be able to implement a reliable way to return the access token issued by the OP and managed by the openidc auth module to the client browser (User Agent)?

I tried a number of options as discussed in issue https://github.com/pingidentity/mod_auth_openidc/issues/69 but the method described only works sometimes. The environment variable `HTTP_OIDC_ACCESS_TOKEN` is not always set during the execution of the apache set header or cookie directive.

As described in issue https://github.com/pingidentity/mod_auth_openidc/issues/69, our use case is to access the access token in the user agent using javascript. The apache server is used to serve static files only without any server side code execution such as AJP proxy or php processing.

A few methods I have tried that work only on first time but as soon as one clears the browser cache and hits refresh the custom set cookie / header is not sent in the server response.

```apache
# at vhost global level
Header set Set-Cookie "AccessToken=%{HTTP_OIDC_ACCESS_TOKEN}e" env=HTTP_OIDC_ACCESS_TOKEN
```

Also did this and it clearly shows that the env variable will be null after any subsequent call to the server
```apache
# at vhost global level force the header in every time
Header set AccessToken "%{HTTP_OIDC_ACCESS_TOKEN}e"
```

Here an example of how the request/response flow looks like (trimmed and removed all irrelevant bits).

```

the normal OAuth initiation sequence

...

GET /dev/oidc/redirect_uri?code=grA85S&state=-RyvOt4VQGCXkYr2I78xDYQ4yPU HTTP/1.1
Host: bla.com:443
Cookie: mod_auth_openidc_state_-rararar

HTTP/1.1 302 Found
Connection: close
Content-Length: 310
Content-Type: text/html; charset=iso-8859-1
Date: Wed, 24 Jun 2015 06:47:07 GMT
Location: https://bla.com/dev/app/
Server: Apache
Set-Cookie: mod_auth_openidc_state_-RyvOt4VQGCXkYr2I78xDYQ4yPU=;Path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT;Secure;HttpOnly
Set-Cookie: mod_auth_openidc_session=34adca5b-6a6f-48d8-9e0b-5facf7137c8a;Path=/;Secure;HttpOnly

---------------------------------------------------------------------------------------------------------------------------------------------

GET /dev/app/ HTTP/1.1
Host: bla.com:443
Cookie: mod_auth_openidc_session=34adca5b-6a6f-48d8-9e0b-5facf7137c8a

HTTP/1.1 200 OK
AccessToken: eyJhbGciOiJSUzI1NiJ9.[truncated but valid token]
Connection: close
Content-Length: 4288
Content-Type: text/html; charset=UTF-8
Date: Wed, 24 Jun 2015 06:47:07 GMT

---------------------------------------------------------------------------------------------------------------------------------------------

GET /dev/app/css/app.min.css HTTP/1.1
Host: bla.com:443
Cookie: mod_auth_openidc_session=34adca5b-6a6f-48d8-9e0b-5facf7137c8a
Referer: https://bla.com/dev/app/

HTTP/1.1 200 OK
Accept-Ranges: bytes
AccessToken: (null)    <--------------------------------- !!!!!
Connection: close
Content-Length: 216329
Content-Type: text/css
Date: Wed, 24 Jun 2015 06:47:08 GMT
Last-Modified: Mon, 15 Jun 2015 13:15:39 GMT

---------------------------------------------------------------------------------------------------------------------------------------------

GET /dev/app/lib/angular-resource/angular-resource.min.js HTTP/1.1
Host: bla.com:443
Cookie: mod_auth_openidc_session=34adca5b-6a6f-48d8-9e0b-5facf7137c8a
Referer: https://bla.com/dev/app/

HTTP/1.1 200 OK
Accept-Ranges: bytes
AccessToken: (null)    <--------------------------------- !!!!!
Connection: close
Content-Length: 3595
Content-Type: text/javascript
Date: Wed, 24 Jun 2015 06:47:08 GMT
Last-Modified: Mon, 15 Jun 2015 13:15:39 GMT
```

Also tried the internal rewrite documented at https://github.com/pingidentity/mod_auth_openidc/issues/55#issuecomment-77259613 but that does not always work either reliably.

**Comment by zandbelt** [comment]
I'd prefer to use the `mod_headers` route for this functionality. Putting it in `mod_auth_openidc` would be duplicating functionality. The solution you describe should work, so let's try to debug that.

a. I don't see where this approach goes wrong: you say you clear the browser cache in between: that would certainly invalidate the session, the headers and the cookies.

b. Are you sure that `/dev/app/css` and `/dev/app/lib` are protected?

**Comment by zandbelt** [comment]
Looks like the environment variable does not get set for static content indeed. I did get this to work:

    Header echo ^OIDC_access_token$

That seems to be a good option for you assuming that you're fine with the name of the header being fixed to `OIDC_access_token`.

**Comment by bertramn** [comment]
Hmm I don't think this will work reliably either. I did try something like this before in the vhost root scope but had similar inconsistent results as in the log above.

```apache
SetEnvIf ^OIDC_access_token$ "(.+)" AuthToken=$1
SetEnvIf Header set AccessToken "%{AuthToken}e" env=AuthToken
```

**Comment by zandbelt** [comment]
It does not make sense to me to duplicate functionality that is already there and I would also suggest that it is easy enough to return the token as part of the server side handling code. After all the intent of the module is passing information to the server side application in a secure way.

There is however room for improvement wrt. the reliability of the existence of the headers in combination with other Apache modules. I am working on passing the claims/tokens not just as part of the headers, but also as part of the environment variables. That seems to be a more reliable mechanism when set by `mod_auth_openidc` from the so-called "fixup" phase of Apache. I would be interested in your feedback on that once done.

**Comment by bertramn** [comment]
No problems as long as the environment variables are available consistently to other modules such as mod_headers it will be easy to configure how to return these to the user agent.

Just to confirm, the "application" we are serving with Apache has no server side code and literally consists of static html/js/css files only. The javascript in html and js files served will essentially be executed in the user agent and from there it needs the bearer token collected by the openidc auth module to make XHR ajax requests to an API running on a different domain.

Rationale here is to use the openidc module to force authentication prior to serving the client UI and then use this authentication context from within the client side app to access data from a different resource location that can also validate the bearer token.

**Comment by zandbelt** [comment]
Can you confirm that ed7cab69abbbfb003d0831e140aeea7b2d6b5c1e makes claims & tokens available as environment variables in a consistent way?

Note that this means that you can use `OIDC_access_token` directly to access the variable value rather than an environment variable that gets set from HTTP headers at some point as before (i.e..`HTTP_OIDC_ACCESS_TOKEN`).

E.g. this works for me:
```apache
Header set OIDC_access_token "%{OIDC_access_token}e" env=OIDC_access_token
```

This gives you some more freedom over `Header echo`

**Comment by bertramn** [comment]
thanks, will check it out tomorrow

**Comment by bertramn** [comment]
I can confirm that this is reliably returning the access token. awesome work ! One thing that would be interesting to also have in context is the expiry time of the JWT token such as one could set a cookie in the user agent that expires at that time .. but that is probably another story.

**Comment by zandbelt** [comment]
if there's an expiry time returned by the OP, it should end up in the `OIDC_access_token_expiry` header/variable, see: https://github.com/pingidentity/mod_auth_openidc/commit/4115ac6b2ee9dd0db0c5f6d95e33585e3a8ce2da

**Comment by zandbelt** [comment]
See also: https://github.com/pingidentity/mod_auth_openidc/issues/132#issuecomment-282280141
