### ISSUE TITLE
Session Management 

### ISSUE THREAD

**Issue by Extracreative** [pingidentity/mod_auth_openidc#77]
I'm trying to use session management so if user logs out email account, their also logged out the website when they refresh. Doing the following below it doesn't seem to be doing anything at all, could you advice anything I've missed

I've substitute inside the html tag,
```
<iframe title='empty' style='visibility: hidden;' width='0' height='0' tabindex='-1' id='openidc-op' src='http://www.example.com/sso-session-true?session=iframe_op'></iframe><iframe title='empty' style='visibility: hidden;' width='0' height='0' tabindex='-1' id='openidc-rp' src='http://www.example.com/sso-session-true?session=iframe_rp&amp;poll=5000'></iframe></body>
```
i've added in 
```
OIDCProviderCheckSessionIFrame http://www.example.com/sso-session-true?session=iframe_op

```
i've added in 
```
OIDCProviderEndSessionEndpoint  http://http://www.example.com 
```

**Comment by zandbelt** [comment]
`OIDCProviderCheckSessionIFrame` and `OIDCProviderEndSessionEndpoint` should point to endpoints that your OP provides. So the question is: are you sure that your OP supports OpenID Connect Session Management and are your sure that you use the right endpoints provided by the OP for that? (surely the `OIDCProviderEndSessionEndpoint` URL is malformed)

**Comment by Extracreative** [comment]
Thanks for replying i'm using [GoogleOpenIDConnect] (https://developers.google.com/identity/protocols/OpenIDConnect)

**Comment by zandbelt** [comment]
Google does not support the OpenID Connect Session Management specification (https://openid.net/specs/openid-connect-session-1_0.html).

**Comment by Extracreative** [comment]
Ok, Thank you I take it theres no other alternative
Because my ajax post request fail when I pick a low OIDCSessionMaxDuration
