### ISSUE TITLE
Installation Error : invalid user: ‘www-data’

### ISSUE THREAD

**Issue by FadelChafai** [pingidentity/mod_auth_openidc#78]
Hi,

i got an error when i run : sudo dpkg -i libapache2-mod-auth-openidc_1.8.2-1ubuntu1.trusty.1_amd64.deb
i got this error : 

(Reading database ... 83645 files and directories currently installed.)
Preparing to unpack libapache2-mod-auth-openidc_1.8.2-1ubuntu1.trusty.1_amd64.deb ...
Unpacking libapache2-mod-auth-openidc (1.8.2-1ubuntu1~trusty+1) over (1.8.2-1ubuntu1~trusty+1) ...
Setting up libapache2-mod-auth-openidc (1.8.2-1ubuntu1~trusty+1) ...
chown: invalid user: ‘www-data’
dpkg: error processing package libapache2-mod-auth-openidc (--install):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 libapache2-mod-auth-openidc

How i can install the package with a different user ?

Thank you

**Comment by zandbelt** [comment]
Are you on a non-standard Trusty environment? If so, you can execute the postinstall commands manually:

        chown -R <user> /var/cache/apache2/mod_auth_openidc
        chmod -R go= /var/cache/apache2/mod_auth_openidc

**Comment by FadelChafai** [comment]
Thank you, yes i have a non-standard Trusty

**Comment by zandbelt** [comment]
you're on your own then; you can either apply the commands manually and/or don't install it as a package but as a .so only (either by building yourself or by extracting it from the .deb)
