### ISSUE TITLE
Problem with curl_easy_perform() timeout

### ISSUE THREAD

**Issue by akramfaresCap** [pingidentity/mod_auth_openidc#80]
Hello, i'm getting this error after installing the module:

[Thu Jul 02 15:01:04.645183 2015] [auth_openidc:error] [pid 3151] [client 10.0.2.2:52184] oidc_util_http_call: curl_easy_perform() failed on: https://my_remote_openid_server (Resolving timed out after 5521 milliseconds)
[Thu Jul 02 15:01:04.645236 2015] [auth_openidc:error] [pid 3151] [client 10.0.2.2:52184] oidc_provider_static_config: could not retrieve metadata from url: https://my_remote_openid_server

I'm using "OIDCSSLValidateServer Off".

Do you have an idea about this problem ? Thank's.

**Comment by zandbelt** [comment]
Does https://my_remote_openid_server exist? Try to open it in a browser or commandine curl. If required because the network is slow, you can increase the timeout value with `OIDCHTTPTimeoutShort`.

**Comment by akramfaresCap** [comment]
Thank's, the OIDCHTTPTimeoutShort fixed the problem.
