### ISSUE TITLE
Issue with providing both id_token and access_token

### ISSUE THREAD

**Issue by eddy-geek** [pingidentity/mod_auth_openidc#81]
I am trying to implement a new OP with implicit flow and I am confused by this error in the logs:
`[auth_openidc:error] [pid 16717] [client 127.0.0.1:44078] oidc_proto_validate_response_type: the requested response type was (id_token) but the response contains an "access_token" parameter, referer: https://localhost/redirect"`

(The page displays *The OpenID Connect Provider returned an error: Error in handling response type.*)

The corresponding OP redirect URL does contain both id_token and access_token:

    https://localhost/redirect#
     state=AO8ooHIGq0JQZOFGTGraHWUgAAs
     &access_token=1_-9W.....
     &id_token=eyJhbGciOiJIUzI1...
     &token_type=bearer&expires_in=3600&

This [blog](http://www.thread-safe.com/2011/11/openid-connect-tale-of-two-tokens.html) seems to suggest it is normal to have the 2 tokens, but google seems to give only one...

So, is it my provider who does not respect the spec, or is it mod_auth_openidc who actually wrongly matches "id_token" with "token" in [the code](https://github.com/pingidentity/mod_auth_openidc/blob/cf8c18d376e6bc8c513678f29c9bad00a2539506/src/proto.c#L1302) ?

If it matters, the config currently looks like this:

    OIDCProviderIssuer https://OP.net/LoginService/
    OIDCProviderAuthorizationEndpoint https://OP.net/LoginService/authorize?service=MyService
    OIDCClientID MyService
    OIDCClientSecret mysecret
    OIDCResponseType id_token
    OIDCCryptoPassphrase password
    OIDCRedirectURI https://localhost/redirect

**Comment by zandbelt** [comment]
The article you refer to is a generic article about OpenID Connect. The response_type `id_token` indicates a specific flow called "Implicit" that only returns an `id_token` in the front channel as specified here: http://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthRequest You'll note that it says at `response_type`:

> No Access Token is returned when the value is id_token.

So the server should not return one.

**Comment by eddy-geek** [comment]
Thanks for the quick reply. I guess OP is doing "token" then.  I will try
that on Monday.
