### ISSUE TITLE
Access Control with Google OAuth 2.0

### ISSUE THREAD

**Issue by jos3k4** [pingidentity/mod_auth_openidc#82]
Hello,

I'm trying to have this working but is not clear to me (I've readed all the documentation, also the useful links) how to implement the Client - Server authentication flow.

I understand that this module doesn't implement the frontend for authenticate the user so I have to get the Token by myself (Making a request to Google) this is specified in the documentation - "How the actual client accessing the protected resources got its access token is not relevant to this Apache Resource Server setup."

But my question is when I have my token provided by Google, how can I make a request to the apache server in order to authenticate someone? Thanks in advance.

**Comment by zandbelt** [comment]
The client would send the token as usual in an `Authentication` header in the form `Authentication: Bearer <token`.

Also note that that token does not authenticate a user or a client. It merely allows the one presenting the token to get access to some protected resource. If you want to authenticate users you need the regular OIDC flow.

**Comment by jos3k4** [comment]
Thanks for the fast answer, but I don't want to know about that level of depth yet... I mean how can I create a request with curl for example in order to test that my token is correct? is that possible? Again my problem is that I don't understand after read the documentation how to implement OAuth2 authentication with this module.

It seems to be a great one but I appreciate some help, maybe it can be useful for new users that want to implement this solution and doesn't know how to start.

**Comment by zandbelt** [comment]
You can use the token agains a resource protected by mod_auth_openidc as follows: `curl -H "Authorization: Bearer <token" https://<host>/<protected-resource>`

**Comment by lukwam** [comment]
I have a token that I retrieved from google and have verified that it is valid.

When I use it as such, it works fine:

curl -H "Authorization: Bearer $token" https://www.googleapis.com/plus/v1/people/me

When I use it with my apache server running mod_auth_openidc, I get Permission denied.

All I am changing is the URL, from https://www.googleapis.com/plus/v1/people/me to the one that references my apache server.  When I access my apache url from my browser, it works.  When I access it via CURL with the Authorization: header, it gets permission denied.

Thoughts?
