### ISSUE TITLE
Support for Auth in Redis

### ISSUE THREAD

**Issue by kylesonaty** [pingidentity/mod_auth_openidc#83]
Redis has a [AUTH Command](http://redis.io/commands/auth) that allows a password to be sent before issuing other commands. Can this be supported by the mod_auth_openidc module in the form of an optional config setting.  Here is some more information [here](http://redis.io/topics/security) in the *Authentication feature* section.

**Comment by billpratt** [comment]
:+1:

**Comment by Gonkers** [comment]
:+1:

**Comment by chadagsync** [comment]
![thumbs](https://cloud.githubusercontent.com/assets/6741736/8705416/843b0a6e-2af7-11e5-843d-9d9bc629e52d.JPG)

**Comment by zandbelt** [comment]
check https://github.com/pingidentity/mod_auth_openidc/commit/9d03a7a741bf1101109272c1966759ff3c8d04d5

**Comment by kylesonaty** [comment]
Awesome! I will try it out.

**Comment by zandbelt** [comment]
Does it work for you?

**Comment by kylesonaty** [comment]
Yeah, It has been working so far. Still testing and haven't deployed to production yet but it is working so far. Thanks again!
