### ISSUE TITLE
Module fails with internal server error when redirect/auth is not actioned promptly

### ISSUE THREAD

**Issue by bertramn** [pingidentity/mod_auth_openidc#86]
We are experiencing a few undesirable behaviors and I am not sure exactly how we can stop these. When the mod_auth_openidc detects that an authentication is required and redirects the user agent to the OP. However if the user does not action the logon promptly but say waits for 30 minutes to logon the auth modules fails on the redirect back to the protected resource. The error is an ugly 500 error but what is worse, this type of behavior is completely normal user behavior and we have not found a way to stop it.

It appears that the module is loosing track of the temporary session state that it holds in memory and then it just does not know what to do with the response that comes back from the OP. Following appears in the log.

```
[Sun Aug 02 03:07:53 2015] [error] [client 122.28.136.18] oidc_restore_proto_state: no "mod_auth_openidc_state_A4R8h0aSGTQOyfAldbcNbVU4Zrs" state cookie found, referer: https://login.bla.com/realm1/login
[Sun Aug 02 03:07:53 2015] [error] [client 122.28.136.18] oidc_unsolicited_proto_state: could not parse JWT from state: invalid unsolicited response: [src/jose/apr_jwt.c:173: apr_jwt_base64url_decode_object]: JSON parsing (json_loads) failed: '[' or '{' expected near '\x03' (\x03\x84|\x87F\x92\x194\x0e\xc9\xf0%u\xb7\rmU8f\xbb)\n, referer: https://login.bla.com/realm1/login
[Sun Aug 02 03:07:53 2015] [error] [client 122.28.136.18] oidc_authorization_response_match_state: unable to restore state, referer: https://login.bla.com/realm1/login
[Sun Aug 02 03:07:53 2015] [error] [client 122.28.136.18] client denied by server configuration: /data/www/htdocs/favicon.ico, referer: https://secure.bla.com/oidc/redirect_uri?code=eudpap&state=A4R8h0aSGTQOyfAldbcNbVU4Zrs
```

Any suggestions on how that could be fixed? Is is as simple as setting up REDIS or Memcache?

Many thanks.

**Comment by bertramn** [comment]
So I did a bit of digging through server debug logs and it appears some version of Safari on iOS are not sending the session cookies to the web server when retrieving the favicons (that is if I interpret debug entry in line 3 correctly). I have tried with iOS 8 successfully but Safari on iOS 7 does not seem to include the oidc state cookie. The beautiful web where a single thing is done in 1000 different ways :( ... oh well.

```
[Sun Aug 02 11:35:12 2015] [info] Initial (No.1) HTTPS request received for child 7 (server secure.bla.com:443)
[Sun Aug 02 11:35:12 2015] [debug] src/mod_auth_openidc.c(2214): [client 102.xx.xx.22] oidc_check_user_id: incoming request: "/oidc/redirect_uri?iss=https%3A%2F%2Flogin.bla.com%2Frealm1%2F&target_link_uri=https%3A%2F%2Fsecure.bla.com%2Fapp%2Ffavicon%2Fapple-touch-icon-152x152.png&oidc_callback=https%3A%2F%2Fsecure.bla.com%2Foidc%2Fredirect_uri", ap_is_initial_req(r)=1
[Sun Aug 02 11:35:12 2015] [debug] src/util.c(739): [client 102.xx.xx.22] oidc_util_get_cookie: returning "mod_auth_openidc_session" = <null>
[Sun Aug 02 11:35:12 2015] [debug] src/session.c(83): [client 102.xx.xx.22] oidc_session_load: <null>
[Sun Aug 02 11:35:12 2015] [debug] src/util.c(778): [client 102.xx.xx.22] oidc_util_request_matches_url: comparing "/oidc/redirect_uri"=="/oidc/redirect_uri"
[Sun Aug 02 11:35:12 2015] [debug] src/mod_auth_openidc.c(1560): [client 102.xx.xx.22] oidc_handle_discovery_response: issuer="https://login.bla.com/realm1/", target_link_uri="https://secure.bla.com/app/favicon/apple-touch-icon-152x152.png", login_hint="(null)"
[Sun Aug 02 11:35:12 2015] [debug] src/util.c(1079): [client 102.xx.xx.22] oidc_util_file_read: file read successfully "/var/cache/mod_auth_openidc/metadata/login.bla.com%2Frealm1.provider"
[Sun Aug 02 11:35:12 2015] [debug] src/metadata.c(309): [client 102.xx.xx.22] oidc_metadata_provider_is_valid: provider (https://login.bla.com/realm1) JSON metadata did not contain a "response_modes_supported" array; assuming that "fragment" and "query" are supported
[Sun Aug 02 11:35:12 2015] [debug] src/util.c(1079): [client 102.xx.xx.22] oidc_util_file_read: file read successfully "/var/cache/mod_auth_openidc/metadata/login.bla.com%2Frealm1.conf"
[Sun Aug 02 11:35:12 2015] [debug] src/util.c(1079): [client 102.xx.xx.22] oidc_util_file_read: file read successfully "/var/cache/mod_auth_openidc/metadata/login.bla.com%2Frealm1.client"
[Sun Aug 02 11:35:12 2015] [debug] src/metadata.c(400): [client 102.xx.xx.22] oidc_metadata_client_is_valid: client (https://login.bla.com/realm1) metadata did not contain a "client_secret_expires_at" setting
[Sun Aug 02 11:35:12 2015] [debug] src/mod_auth_openidc.c(1378): [client 102.xx.xx.22] oidc_authenticate_user: enter
[Sun Aug 02 11:35:12 2015] [debug] src/mod_auth_openidc.c(141): [client 102.xx.xx.22] oidc_get_browser_state_hash: enter
[Sun Aug 02 11:35:12 2015] [debug] src/util.c(699): [client 102.xx.xx.22] oidc_util_set_cookie: adding outgoing header: Set-Cookie:
```


The other thing that is a bit confusing is the configuration of the `OIDCDiscoverURL` parameter, the files are actually called something different to the issuer id as well as the discovery URL.

Issuer Id
`https://login.bla.com/realm1/`

Issuer Provider Conf
`login.bla.com%2Frealm1.provider`

Issuer Discovery Config
`OIDCDiscoverURL https://secure.bla.com/oidc/redirect_uri?iss=https%3A%2F%2Flogin.bla.com%2Frealm1%2F`

 I found above working for me without errors but not sure exactly if this is correct because if I change the `OIDCDiscoverURL` to:

`OIDCDiscoverURL https://secure.bla.com/oidc/redirect_uri?iss=login.bla.com%2Frealm1`

.. it also works but with these `oidc_unsolicited_proto_state` warnings from my first post ... hmm.

**Comment by zandbelt** [comment]
You can control the "state timeout" with the `OIDCStateTimeout` primitive as documented here: https://github.com/pingidentity/mod_auth_openidc/blob/master/auth_openidc.conf#L534. That setting is independent of the cache backend.

**Comment by bertramn** [comment]
Hmmm is there a way to redirect the user back to the login screen instead of showing the plain 500 as below?

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, root@localhost and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

Apache Server at secure.bla.com Port 443

**Comment by zandbelt** [comment]
You are probably right that this event should be handled more elegantly.

**Comment by bertramn** [comment]
In my case it would probably suffice if one could configure a redirect URL to a login page but I am not sure if this is always the case.

**Comment by zandbelt** [comment]
see ac9e7f2 which handles this case by sending the user to `OIDCDefaultURL` if set; please verify

**Comment by zandbelt** [comment]
see also #89
