### ISSUE TITLE
mod_auth_openidc Logout from 

### ISSUE THREAD

**Issue by FadelChafai** [pingidentity/mod_auth_openidc#87]
Hi,

I can not seem to disconnect from my application because mod_auth_openidc check my OP and find the session always active.

How can I logout from both of them ( my app and the OP ) after calling <a href="/protected/redirect_uri?logout=https%3A%2F%2Flocalhost%2Floggedout.html">Logout</a>

Thank you

**Comment by zandbelt** [comment]
So called Single Logout, i.e. logout across both RP and OP, can only be achieved when both sides support the logout mechanism that is specified in the OpenID Connect Session Management specification, see https://github.com/pingidentity/mod_auth_openidc/wiki/Session-Management. If the OP does not support Session Management (and thus doesn't expose the required endpoint), mod_auth_openidc will only terminate the local RP session  but it won't be able signal the OP to kill the SSO session there.

**Comment by FadelChafai** [comment]
Thank you
