### ISSUE TITLE
module prevents apache from executing ErrorDocument 401 routing

### ISSUE THREAD

**Issue by bertramn** [pingidentity/mod_auth_openidc#88]
I configured a `ErrorDocument 401` directive in the apache config but the auth module seems to be preventing apache from triggering this rule. I read hat the `OIDCUnAuthAction` was added to provide more options but I am not sure that this functionality will work when the user is authenticated but not authorized to access a protected resource. In the case of configuring option `auth`, the user may end up in an endless redirect loop if s/he is authenticated with the OP but trying to access a protected resource triggers a authorization failure.Redirecting the user to the OP will simply redirect the user back to the protected site. I was also wondering why an authorization failure (not meeting Require rule) is generating a 401, should that not be a 403?

**Comment by zandbelt** [comment]
`OIDCUnAuthAction` specifies the action to be taken when no authentication is provided. The following combination works fine to send a custom 401 document when no authentication is provided:

       OIDCUnAuthAction 401
       ErrorDocument 401 /401.html

The default is `auth` so it will send users to the OP when they are not authenticated. When the `Require` directives are not met, the user will not be resend to the OP but a 401 will be returned (which may indeed better become a 403). That all seems fine,  s what is the behavior you're looking to implement?

**Comment by bertramn** [comment]
I am looking to differentiate the failures of not being authenticated (401) vs you are forbidden to access this resource (403). Currently the both result in 401. I think the main logic would be:

```
IF valid_session AND claim match THEN
  return resource
ELSE IF valid_session AND NO claims match THEN
  return 403
ELSE IF NO valid_session AND context directive to throw 401 THEN
  return 401
ELSE
  redirect 302 to auth
END IF
```

Does that make sense?

**Comment by zandbelt** [comment]
I think it makes sense but I'm a bit hesitant to change the current behavior since the 401 seems to be the default in use by other authentication modules as well. In Apache 2.4 there's a configurable way to get the 403 by using `AuthzSendForbiddenOnFailure On`, see http://httpd.apache.org/docs/2.4/mod/mod_authz_core.html#authzsendforbiddenonfailure

I've tested this and it works for me. Perhaps you can verify this too.

**Comment by zandbelt** [comment]
So I guess the conclusion on this is that you'd need Apache 2.4 to implement the logic you describe. Agreed?
