### ISSUE TITLE
Dynamic client registration

### ISSUE THREAD

**Issue by rebeckag** [pingidentity/mod_auth_openidc#94]
I couldn't find much documentation on how to configure the module to use dynamic client registration. Any additional pointers on required configuration parameters? My simplified Apache config looks like:

    Listen 9000
    LogLevel info
    ServerName localhost:9000

    LoadModule auth_openidc_module /usr/lib/apache2/modules/mod_auth_openidc.so

    <VirtualHost _default_:9000>
    OIDCCryptoPassphrase secret
    OIDCRedirectURI http://localhost:9000/redirect_uri
    OIDCMetadataDir /var/lib/apache2/openid-client-creds
    OIDCSSLValidateServer Off

    <Location />
        AuthType openid-connect
        Require valid-user
    </Location>
    </VirtualHost>

This config results in me getting the discovery page where I can enter the issuer identifier. Then I get the error page and the logs show:

    [Tue Sep 15 06:31:48.855711 2015] [auth_openidc:warn] [pid 7066:tid 139843732502272] [client XXX] oidc_util_file_read: no file found at: "/var/lib/apache2/openid-client-creds/<provider>.client"
    [Tue Sep 15 06:31:48.862428 2015] [auth_openidc:error] [pid 7066:tid 139843732502272] [client XXX] oidc_util_decode_json_and_check_error: JSON parsing returned an error: '[' or '{' expected near end of file
    [Tue Sep 15 06:31:51.223446 2015] [auth_openidc:warn] [pid 7066:tid 139843724109568] [client XXX] oidc_metadata_provider_is_valid: requested issuer (<provider>) does not match the "issuer" value in the provider metadata file: https://<provider>, referer: http://localhost:9000/
    [Tue Sep 15 06:31:51.223507 2015] [auth_openidc:warn] [pid 7066:tid 139843724109568] [client XXX] oidc_util_file_read: no file found at: "/var/lib/apache2/openid-client-creds/<provider>.client", referer: http://localhost:9000/
    [Tue Sep 15 06:31:51.230625 2015] [auth_openidc:error] [pid 7066:tid 139843724109568] [client XXX] oidc_util_decode_json_and_check_error: JSON parsing returned an error: '[' or '{' expected near end of file, referer: http://localhost:9000/

So it seems the module is incorrectly trying to read the static client info (which doesn't exist) instead of dynamically registering with the provider.

**Comment by zandbelt** [comment]
I believe the error may be about a different file (`.provider` or `.conf`) than the `.client` one. Could you increase the debug level to verify? (`LogLevel debug`)

**Comment by rebeckag** [comment]
Thanks for your quick feedback; increasing the logging revealed that no response was received to the registration request. This was due to an error at my provider, not with the module!

**Comment by zandbelt** [comment]
I'm reopening the ticket to remind me that logging around this scenario needs to be enhanced.
