### ISSUE TITLE
Missing .spec file for building RPM redux

### ISSUE THREAD

**Issue by pfiled** [pingidentity/mod_auth_openidc#95]
This was addressed in issue #39, but it doesn't look like the spec file referenced there is being updated. Where can we find the current spec used to build the RPM?

Thanks!

**Comment by zandbelt** [comment]
I build RPMs from: https://github.com/zandbelt/mod-auth-openidc-dist/tree/master/centos
Redhat offered to maintain Fedore packages and those RPMs should get a more official spec file.
