### ISSUE TITLE
Add support for virtual host specific cookies

### ISSUE THREAD

**Issue by scottdear** [pingidentity/mod_auth_openidc#98]
Session ID's for an authenticated user are shared between virtual hosts.  If a user authenticates against and receives a cookie for a virtual domain, that cookie can be replayed, and will work against any virtual host that uses the same session store.  It would improve security if the sessions are specific to the virtual host they are assigned on.  A couple of suggestions would be to either include the virtual host, on the back-end, before the session ID is written, so a session ID will not work across virtual hosts.  Another option would be to include a configurable session prefix that gets pre-pended to the session ID before it is written.  The first (prepending the virtual host) might actually be preferrable as it would allow multiple virtual hosts to be serviced out of a single config file (less apache memory used) as in 

ServerAlias *.foo.com

Then cookie 123 delivered to client, if assigned on www1.foo.com would be written on the back-end as www1.foo.com-123, but set the cookie 123 on the client.  A cookied assigned on www2.foo.com would be written with a back-end session id of www2.foo.com-123 and also written on the client as 123.

**Comment by zandbelt** [comment]
yep, instead of segmenting the shared cache, cookies being replayed at a domain they weren't issued for are now blocked in 265edf58343bd8110bbc477387cb6b3b813377fe ; let me how that works

**Comment by scottdear** [comment]
Roger that.  I'll get the latest version downloaded and run through my 
cookie substitution test then post back with my results shortly.

**Comment by scottdear** [comment]
I ran through the same tests as before.

1. log in to foo.mydomian.com
2. Using cookie editor add a cookie with the values from the foo.mydomain.com domain for bar.mydomain.com.
3. Open the page at bar.mydomain.com, instead of allowing me access it now re-directs me to my loging discovery page.  Closing this out as fixed (if that's OK).

**Comment by zandbelt** [comment]
Ok, thanks for the quick follow-up!

**Comment by scottdear** [comment]
Right back atcha'
