### ISSUE TITLE
"iat" validation failure - timestamp value in miliseconds but expects seconds

### ISSUE THREAD

**Issue by filip-vt** [pingidentity/mod_auth_openidc#99]
I got an issue with the iat value I get back from my Indentity Server (WSO2 in my case).

```
oidc_proto_validate_iat: "iat" validation failure (1446128035311): JWT was issued more than 600 seconds in the future
```

As you can see the value is in miliseconds and I think mod_auth_openidc expects the value to be in seconds (not sure though). I already tried raising OIDCIDTokenIatSlack significantly, but the value overflows (too large) resulting in a negative number.

Is there a way to set it to miliseconds instead? Or disable the iat value check?

**Comment by zandbelt** [comment]
the spec requires `iat` to be specified in seconds, see: http://openid.net/specs/openid-connect-core-1_0.html#IDToken, so that's a bug on the OP side
